-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_197_1_VITIS_LOOP_198_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s2_A_out_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    s2_A_out_ce0 : OUT STD_LOGIC;
    s2_A_out_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    s2_A_out_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    s2_A_out_ce1 : OUT STD_LOGIC;
    s2_A_out_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    s2_B_out_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    s2_B_out_ce0 : OUT STD_LOGIC;
    s2_B_out_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    s2_B_out_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    s2_B_out_ce1 : OUT STD_LOGIC;
    s2_B_out_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    s2_pool_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    s2_pool_ce0 : OUT STD_LOGIC;
    s2_pool_we0 : OUT STD_LOGIC;
    s2_pool_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_2080_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_ce : OUT STD_LOGIC;
    grp_fu_7257_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_7257_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_7257_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_7257_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_7257_p_ce : OUT STD_LOGIC;
    grp_fu_2105_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2105_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2105_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_2105_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_2105_p_ce : OUT STD_LOGIC;
    grp_fu_7261_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_7261_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_7261_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_7261_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_7261_p_ce : OUT STD_LOGIC;
    grp_fu_7265_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_7265_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_7265_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_7265_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_7265_p_ce : OUT STD_LOGIC );
end;


architecture behav of ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_197_1_VITIS_LOOP_198_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_2E0 : STD_LOGIC_VECTOR (9 downto 0) := "1011100000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln197_fu_173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln202_fu_269_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln202_reg_530 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln202_reg_530_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln202_reg_530_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln202_reg_530_pp0_iter3_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln202_reg_530_pp0_iter4_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln202_reg_530_pp0_iter5_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln202_reg_530_pp0_iter6_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln202_reg_530_pp0_iter7_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln202_reg_530_pp0_iter8_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal s2_A_out_load_reg_535 : STD_LOGIC_VECTOR (31 downto 0);
    signal s2_B_out_load_reg_540 : STD_LOGIC_VECTOR (31 downto 0);
    signal s2_A_out_load_1_reg_545 : STD_LOGIC_VECTOR (31 downto 0);
    signal s2_B_out_load_1_reg_550 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_assign_7_reg_555 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_assign_7_reg_555_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal x_assign_8_reg_562 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_assign_8_reg_562_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal v0_fu_337_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal v0_reg_569 : STD_LOGIC_VECTOR (31 downto 0);
    signal v0_reg_569_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal v1_fu_385_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal v1_reg_576 : STD_LOGIC_VECTOR (31 downto 0);
    signal v1_reg_576_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln200_fu_251_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln201_fu_263_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln202_fu_392_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_fu_58 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln198_fu_275_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (4 downto 0);
    signal t_fu_62 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln197_1_fu_211_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_t_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten38_fu_66 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln197_1_fu_179_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten38_load : STD_LOGIC_VECTOR (9 downto 0);
    signal s2_A_out_ce1_local : STD_LOGIC;
    signal s2_A_out_ce0_local : STD_LOGIC;
    signal s2_B_out_ce1_local : STD_LOGIC;
    signal s2_B_out_ce0_local : STD_LOGIC;
    signal s2_pool_we0_local : STD_LOGIC;
    signal select_ln202_fu_478_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal s2_pool_ce0_local : STD_LOGIC;
    signal icmp_ln198_fu_197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln197_fu_191_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln197_fu_203_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_15_fu_243_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_14_fu_227_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln200_2_fu_239_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln201_fu_257_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_s_fu_219_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln200_1_fu_235_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal bitcast_ln36_fu_296_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_299_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln36_fu_309_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln36_2_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln36_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln36_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln36_fu_331_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln36_1_fu_344_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_18_fu_347_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln36_1_fu_357_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln36_4_fu_367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln36_3_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln36_1_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln36_1_fu_379_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln202_fu_396_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln202_1_fu_413_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_20_fu_399_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln202_fu_409_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln202_1_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln202_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_416_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln202_1_fu_426_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln202_3_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln202_2_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln202_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln202_1_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln202_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln202_1_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ecg_cnn_top_faddfsub_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_fadd_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component ecg_cnn_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component ecg_cnn_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    c_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln197_fu_173_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_58 <= add_ln198_fu_275_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_58 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten38_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln197_fu_173_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten38_fu_66 <= add_ln197_1_fu_179_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten38_fu_66 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    t_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln197_fu_173_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    t_fu_62 <= select_ln197_1_fu_211_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    t_fu_62 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln202_reg_530 <= add_ln202_fu_269_p2;
                add_ln202_reg_530_pp0_iter1_reg <= add_ln202_reg_530;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln202_reg_530_pp0_iter2_reg <= add_ln202_reg_530_pp0_iter1_reg;
                add_ln202_reg_530_pp0_iter3_reg <= add_ln202_reg_530_pp0_iter2_reg;
                add_ln202_reg_530_pp0_iter4_reg <= add_ln202_reg_530_pp0_iter3_reg;
                add_ln202_reg_530_pp0_iter5_reg <= add_ln202_reg_530_pp0_iter4_reg;
                add_ln202_reg_530_pp0_iter6_reg <= add_ln202_reg_530_pp0_iter5_reg;
                add_ln202_reg_530_pp0_iter7_reg <= add_ln202_reg_530_pp0_iter6_reg;
                add_ln202_reg_530_pp0_iter8_reg <= add_ln202_reg_530_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                v0_reg_569 <= v0_fu_337_p3;
                v0_reg_569_pp0_iter8_reg <= v0_reg_569;
                v1_reg_576 <= v1_fu_385_p3;
                v1_reg_576_pp0_iter8_reg <= v1_reg_576;
                x_assign_7_reg_555 <= grp_fu_2080_p_dout0;
                x_assign_7_reg_555_pp0_iter6_reg <= x_assign_7_reg_555;
                x_assign_8_reg_562 <= grp_fu_7257_p_dout0;
                x_assign_8_reg_562_pp0_iter6_reg <= x_assign_8_reg_562;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                s2_A_out_load_1_reg_545 <= s2_A_out_q0;
                s2_A_out_load_reg_535 <= s2_A_out_q1;
                s2_B_out_load_1_reg_550 <= s2_B_out_q0;
                s2_B_out_load_reg_540 <= s2_B_out_q1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln197_1_fu_179_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten38_load) + unsigned(ap_const_lv10_1));
    add_ln197_fu_191_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_t_load) + unsigned(ap_const_lv6_1));
    add_ln198_fu_275_p2 <= std_logic_vector(unsigned(select_ln197_fu_203_p3) + unsigned(ap_const_lv5_1));
    add_ln201_fu_257_p2 <= std_logic_vector(unsigned(tmp_14_fu_227_p3) + unsigned(zext_ln200_2_fu_239_p1));
    add_ln202_fu_269_p2 <= std_logic_vector(unsigned(tmp_s_fu_219_p3) + unsigned(zext_ln200_1_fu_235_p1));
    and_ln202_1_fu_472_p2 <= (grp_fu_7265_p_dout0 and and_ln202_fu_466_p2);
    and_ln202_fu_466_p2 <= (or_ln202_fu_442_p2 and or_ln202_1_fu_460_p2);
    and_ln36_1_fu_379_p2 <= (or_ln36_1_fu_373_p2 and grp_fu_7261_p_dout0);
    and_ln36_fu_331_p2 <= (or_ln36_fu_325_p2 and grp_fu_2105_p_dout0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln197_fu_173_p2)
    begin
        if (((icmp_ln197_fu_173_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, c_fu_58, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_58;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten38_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten38_fu_66)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten38_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten38_load <= indvar_flatten38_fu_66;
        end if; 
    end process;


    ap_sig_allocacmp_t_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, t_fu_62)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_t_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_t_load <= t_fu_62;
        end if; 
    end process;

    bitcast_ln202_1_fu_413_p1 <= v1_reg_576_pp0_iter8_reg;
    bitcast_ln202_fu_396_p1 <= v0_reg_569_pp0_iter8_reg;
    bitcast_ln36_1_fu_344_p1 <= x_assign_8_reg_562_pp0_iter6_reg;
    bitcast_ln36_fu_296_p1 <= x_assign_7_reg_555_pp0_iter6_reg;
    grp_fu_2080_p_ce <= ap_const_logic_1;
    grp_fu_2080_p_din0 <= s2_A_out_load_reg_535;
    grp_fu_2080_p_din1 <= s2_B_out_load_reg_540;
    grp_fu_2080_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_2105_p_ce <= ap_const_logic_1;
    grp_fu_2105_p_din0 <= x_assign_7_reg_555;
    grp_fu_2105_p_din1 <= ap_const_lv32_0;
    grp_fu_2105_p_opcode <= ap_const_lv5_2;
    grp_fu_7257_p_ce <= ap_const_logic_1;
    grp_fu_7257_p_din0 <= s2_A_out_load_1_reg_545;
    grp_fu_7257_p_din1 <= s2_B_out_load_1_reg_550;
    grp_fu_7257_p_opcode <= ap_const_lv2_0;
    grp_fu_7261_p_ce <= ap_const_logic_1;
    grp_fu_7261_p_din0 <= x_assign_8_reg_562;
    grp_fu_7261_p_din1 <= ap_const_lv32_0;
    grp_fu_7261_p_opcode <= ap_const_lv5_2;
    grp_fu_7265_p_ce <= ap_const_logic_1;
    grp_fu_7265_p_din0 <= v0_reg_569;
    grp_fu_7265_p_din1 <= v1_reg_576;
    grp_fu_7265_p_opcode <= ap_const_lv5_2;
    icmp_ln197_fu_173_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten38_load = ap_const_lv10_2E0) else "0";
    icmp_ln198_fu_197_p2 <= "1" when (ap_sig_allocacmp_c_load = ap_const_lv5_10) else "0";
    icmp_ln202_1_fu_436_p2 <= "1" when (trunc_ln202_fu_409_p1 = ap_const_lv23_0) else "0";
    icmp_ln202_2_fu_448_p2 <= "0" when (tmp_21_fu_416_p4 = ap_const_lv8_FF) else "1";
    icmp_ln202_3_fu_454_p2 <= "1" when (trunc_ln202_1_fu_426_p1 = ap_const_lv23_0) else "0";
    icmp_ln202_fu_430_p2 <= "0" when (tmp_20_fu_399_p4 = ap_const_lv8_FF) else "1";
    icmp_ln36_2_fu_319_p2 <= "1" when (trunc_ln36_fu_309_p1 = ap_const_lv23_0) else "0";
    icmp_ln36_3_fu_361_p2 <= "0" when (tmp_18_fu_347_p4 = ap_const_lv8_FF) else "1";
    icmp_ln36_4_fu_367_p2 <= "1" when (trunc_ln36_1_fu_357_p1 = ap_const_lv23_0) else "0";
    icmp_ln36_fu_313_p2 <= "0" when (tmp_16_fu_299_p4 = ap_const_lv8_FF) else "1";
    or_ln202_1_fu_460_p2 <= (icmp_ln202_3_fu_454_p2 or icmp_ln202_2_fu_448_p2);
    or_ln202_fu_442_p2 <= (icmp_ln202_fu_430_p2 or icmp_ln202_1_fu_436_p2);
    or_ln36_1_fu_373_p2 <= (icmp_ln36_4_fu_367_p2 or icmp_ln36_3_fu_361_p2);
    or_ln36_fu_325_p2 <= (icmp_ln36_fu_313_p2 or icmp_ln36_2_fu_319_p2);
    s2_A_out_address0 <= zext_ln201_fu_263_p1(11 - 1 downto 0);
    s2_A_out_address1 <= zext_ln200_fu_251_p1(11 - 1 downto 0);
    s2_A_out_ce0 <= s2_A_out_ce0_local;

    s2_A_out_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s2_A_out_ce0_local <= ap_const_logic_1;
        else 
            s2_A_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    s2_A_out_ce1 <= s2_A_out_ce1_local;

    s2_A_out_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s2_A_out_ce1_local <= ap_const_logic_1;
        else 
            s2_A_out_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    s2_B_out_address0 <= zext_ln201_fu_263_p1(11 - 1 downto 0);
    s2_B_out_address1 <= zext_ln200_fu_251_p1(11 - 1 downto 0);
    s2_B_out_ce0 <= s2_B_out_ce0_local;

    s2_B_out_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s2_B_out_ce0_local <= ap_const_logic_1;
        else 
            s2_B_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    s2_B_out_ce1 <= s2_B_out_ce1_local;

    s2_B_out_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s2_B_out_ce1_local <= ap_const_logic_1;
        else 
            s2_B_out_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    s2_pool_address0 <= zext_ln202_fu_392_p1(10 - 1 downto 0);
    s2_pool_ce0 <= s2_pool_ce0_local;

    s2_pool_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            s2_pool_ce0_local <= ap_const_logic_1;
        else 
            s2_pool_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    s2_pool_d0 <= select_ln202_fu_478_p3;
    s2_pool_we0 <= s2_pool_we0_local;

    s2_pool_we0_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            s2_pool_we0_local <= ap_const_logic_1;
        else 
            s2_pool_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln197_1_fu_211_p3 <= 
        add_ln197_fu_191_p2 when (icmp_ln198_fu_197_p2(0) = '1') else 
        ap_sig_allocacmp_t_load;
    select_ln197_fu_203_p3 <= 
        ap_const_lv5_0 when (icmp_ln198_fu_197_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    select_ln202_fu_478_p3 <= 
        v0_reg_569_pp0_iter8_reg when (and_ln202_1_fu_472_p2(0) = '1') else 
        v1_reg_576_pp0_iter8_reg;
    tmp_14_fu_227_p3 <= (select_ln197_1_fu_211_p3 & ap_const_lv5_10);
    tmp_15_fu_243_p3 <= (select_ln197_1_fu_211_p3 & select_ln197_fu_203_p3);
    tmp_16_fu_299_p4 <= bitcast_ln36_fu_296_p1(30 downto 23);
    tmp_18_fu_347_p4 <= bitcast_ln36_1_fu_344_p1(30 downto 23);
    tmp_20_fu_399_p4 <= bitcast_ln202_fu_396_p1(30 downto 23);
    tmp_21_fu_416_p4 <= bitcast_ln202_1_fu_413_p1(30 downto 23);
    tmp_s_fu_219_p3 <= (select_ln197_1_fu_211_p3 & ap_const_lv4_0);
    trunc_ln202_1_fu_426_p1 <= bitcast_ln202_1_fu_413_p1(23 - 1 downto 0);
    trunc_ln202_fu_409_p1 <= bitcast_ln202_fu_396_p1(23 - 1 downto 0);
    trunc_ln36_1_fu_357_p1 <= bitcast_ln36_1_fu_344_p1(23 - 1 downto 0);
    trunc_ln36_fu_309_p1 <= bitcast_ln36_fu_296_p1(23 - 1 downto 0);
    v0_fu_337_p3 <= 
        x_assign_7_reg_555_pp0_iter6_reg when (and_ln36_fu_331_p2(0) = '1') else 
        ap_const_lv32_0;
    v1_fu_385_p3 <= 
        x_assign_8_reg_562_pp0_iter6_reg when (and_ln36_1_fu_379_p2(0) = '1') else 
        ap_const_lv32_0;
    zext_ln200_1_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln197_fu_203_p3),10));
    zext_ln200_2_fu_239_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln197_fu_203_p3),11));
    zext_ln200_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_243_p3),64));
    zext_ln201_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln201_fu_257_p2),64));
    zext_ln202_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln202_reg_530_pp0_iter8_reg),64));
end behav;
