-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s1_seq_out_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    s1_seq_out_ce0 : OUT STD_LOGIC;
    s1_seq_out_we0 : OUT STD_LOGIC;
    s1_seq_out_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_in_2d_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ecg_cnn_top_float_float_in_2d_2_ce0 : OUT STD_LOGIC;
    ecg_cnn_top_float_float_in_2d_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_2080_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_ce : OUT STD_LOGIC;
    grp_fu_2084_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2084_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2084_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2084_p_ce : OUT STD_LOGIC;
    grp_fu_2102_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2102_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2102_p_ce : OUT STD_LOGIC;
    grp_fu_2105_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2105_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2105_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_2105_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_2105_p_ce : OUT STD_LOGIC );
end;


architecture behav of ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv32_3C1822EC : STD_LOGIC_VECTOR (31 downto 0) := "00111100000110000010001011101100";
    constant ap_const_lv14_28B0 : STD_LOGIC_VECTOR (13 downto 0) := "10100010110000";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv7_38 : STD_LOGIC_VECTOR (6 downto 0) := "0111000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv9_1C9 : STD_LOGIC_VECTOR (8 downto 0) := "111001001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv9_BA : STD_LOGIC_VECTOR (8 downto 0) := "010111010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln47_reg_572 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal s1_conv_seq_w_3_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal s1_conv_seq_w_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal s1_bn_seq_scale_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal s1_bn_seq_scale_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal s1_bn_seq_bias_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal s1_bn_seq_bias_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln47_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_572_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_572_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_572_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_572_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_572_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_572_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_572_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_reg_576 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_reg_576_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_reg_576_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_581 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_581_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_581_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_581_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_581_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal k_mid2_fu_284_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_mid2_reg_586 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_mid2_reg_586_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal k_mid2_reg_586_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln48_fu_292_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln48_reg_591 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln48_reg_591_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln48_reg_591_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln48_reg_591_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln48_reg_591_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln50_1_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_602 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_602_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_602_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_602_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_602_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_602_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_602_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_602_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_reg_602_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln38_fu_373_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln38_reg_606 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal sext_ln38_2_fu_379_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal conv1_i_i_reg_616 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln47_1_fu_392_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln47_1_reg_621 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln47_1_reg_621_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln47_1_reg_621_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln53_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_626 : STD_LOGIC_VECTOR (0 downto 0);
    signal v_fu_434_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_reg_636 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i_i_reg_641 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i_reg_646 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_mid2_fu_444_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln48_fu_459_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_reg_656 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln57_fu_466_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln57_reg_661 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln57_reg_661_pp0_iter6_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln57_reg_661_pp0_iter7_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln57_reg_661_pp0_iter8_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal acc_2_reg_671 : STD_LOGIC_VECTOR (31 downto 0);
    signal s1_bn_seq_scale_load_reg_676 : STD_LOGIC_VECTOR (31 downto 0);
    signal s1_bn_seq_bias_load_reg_686 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i19_i_reg_691 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_assign_1_reg_696 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal zext_ln54_fu_318_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln53_fu_418_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln57_2_fu_477_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_fu_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_load : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal k_fu_84 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln50_fu_323_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_k_load : STD_LOGIC_VECTOR (2 downto 0);
    signal oc_fu_88 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_sig_allocacmp_oc_load : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_fu_92 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln48_1_fu_341_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (6 downto 0);
    signal t_fu_96 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal indvar_flatten24_fu_100 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal add_ln47_1_fu_228_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_sig_allocacmp_indvar_flatten24_load : STD_LOGIC_VECTOR (13 downto 0);
    signal s1_conv_seq_w_3_ce0_local : STD_LOGIC;
    signal ecg_cnn_top_float_float_in_2d_2_ce0_local : STD_LOGIC;
    signal s1_bn_seq_scale_ce0_local : STD_LOGIC;
    signal s1_bn_seq_bias_ce0_local : STD_LOGIC;
    signal s1_seq_out_we0_local : STD_LOGIC;
    signal select_ln36_fu_522_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal s1_seq_out_ce0_local : STD_LOGIC;
    signal grp_fu_169_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_169_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal grp_fu_173_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_173_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln50_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln47_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln47_fu_246_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln47_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln48_fu_272_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_304_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln57_fu_300_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln54_fu_312_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln48_1_fu_335_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln38_fu_369_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln47_fu_386_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln52_fu_403_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln52_fu_408_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln47_fu_399_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln52_1_fu_412_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_s_fu_452_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln57_1_fu_463_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal bitcast_ln36_fu_481_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_484_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln36_fu_494_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln36_1_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln36_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln36_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln36_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_00001 : BOOLEAN;
    signal ap_block_pp0_stage2_00001 : BOOLEAN;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter7_stage1 : STD_LOGIC;
    signal ap_idle_pp0_0to6 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to8 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ecg_cnn_top_faddfsub_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_sitofp_32s_32_4_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_s1_conv_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_s1_bn_secud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_s1_bn_sedEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    s1_conv_seq_w_3_U : component ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_s1_conv_bkb
    generic map (
        DataWidth => 8,
        AddressRange => 56,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => s1_conv_seq_w_3_address0,
        ce0 => s1_conv_seq_w_3_ce0_local,
        q0 => s1_conv_seq_w_3_q0);

    s1_bn_seq_scale_U : component ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_s1_bn_secud
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => s1_bn_seq_scale_address0,
        ce0 => s1_bn_seq_scale_ce0_local,
        q0 => s1_bn_seq_scale_q0);

    s1_bn_seq_bias_U : component ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_s1_bn_sedEe
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => s1_bn_seq_bias_address0,
        ce0 => s1_bn_seq_bias_ce0_local,
        q0 => s1_bn_seq_bias_q0);

    flow_control_loop_pipe_sequential_init_U : component ecg_cnn_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                acc_fu_80 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                acc_fu_80 <= grp_fu_2080_p_dout0;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage1))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage1))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter5_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage1))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter6_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage1))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter7_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage1))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
            end if; 
        end if;
    end process;

    indvar_flatten24_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln47_fu_222_p2 = ap_const_lv1_0))) then 
                    indvar_flatten24_fu_100 <= add_ln47_1_fu_228_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten24_fu_100 <= ap_const_lv14_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln47_fu_222_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_92 <= select_ln48_1_fu_341_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_92 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    k_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln47_fu_222_p2 = ap_const_lv1_0))) then 
                    k_fu_84 <= add_ln50_fu_323_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_84 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    oc_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln47_fu_222_p2 = ap_const_lv1_0))) then 
                    oc_fu_88 <= select_ln48_fu_292_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    oc_fu_88 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    t_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                t_fu_96 <= ap_const_lv8_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                t_fu_96 <= select_ln47_1_fu_392_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                acc_2_reg_671 <= grp_fu_2080_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln38_reg_606 <= add_ln38_fu_373_p2;
                icmp_ln53_reg_626 <= icmp_ln53_fu_423_p2;
                s1_bn_seq_bias_load_reg_686 <= s1_bn_seq_bias_q0;
                s1_bn_seq_scale_load_reg_676 <= s1_bn_seq_scale_q0;
                select_ln47_1_reg_621 <= select_ln47_1_fu_392_p3;
                select_ln47_1_reg_621_pp0_iter3_reg <= select_ln47_1_reg_621;
                select_ln47_1_reg_621_pp0_iter4_reg <= select_ln47_1_reg_621_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln57_reg_661 <= add_ln57_fu_466_p2;
                add_ln57_reg_661_pp0_iter6_reg <= add_ln57_reg_661;
                add_ln57_reg_661_pp0_iter7_reg <= add_ln57_reg_661_pp0_iter6_reg;
                add_ln57_reg_661_pp0_iter8_reg <= add_ln57_reg_661_pp0_iter7_reg;
                empty_reg_581 <= empty_fu_278_p2;
                empty_reg_581_pp0_iter1_reg <= empty_reg_581;
                empty_reg_581_pp0_iter2_reg <= empty_reg_581_pp0_iter1_reg;
                empty_reg_581_pp0_iter3_reg <= empty_reg_581_pp0_iter2_reg;
                empty_reg_581_pp0_iter4_reg <= empty_reg_581_pp0_iter3_reg;
                icmp_ln47_reg_572 <= icmp_ln47_fu_222_p2;
                icmp_ln47_reg_572_pp0_iter1_reg <= icmp_ln47_reg_572;
                icmp_ln47_reg_572_pp0_iter2_reg <= icmp_ln47_reg_572_pp0_iter1_reg;
                icmp_ln47_reg_572_pp0_iter3_reg <= icmp_ln47_reg_572_pp0_iter2_reg;
                icmp_ln47_reg_572_pp0_iter4_reg <= icmp_ln47_reg_572_pp0_iter3_reg;
                icmp_ln47_reg_572_pp0_iter5_reg <= icmp_ln47_reg_572_pp0_iter4_reg;
                icmp_ln47_reg_572_pp0_iter6_reg <= icmp_ln47_reg_572_pp0_iter5_reg;
                icmp_ln47_reg_572_pp0_iter7_reg <= icmp_ln47_reg_572_pp0_iter6_reg;
                icmp_ln48_reg_576 <= icmp_ln48_fu_240_p2;
                icmp_ln48_reg_576_pp0_iter1_reg <= icmp_ln48_reg_576;
                icmp_ln48_reg_576_pp0_iter2_reg <= icmp_ln48_reg_576_pp0_iter1_reg;
                icmp_ln50_1_reg_602 <= icmp_ln50_1_fu_329_p2;
                icmp_ln50_1_reg_602_pp0_iter1_reg <= icmp_ln50_1_reg_602;
                icmp_ln50_1_reg_602_pp0_iter2_reg <= icmp_ln50_1_reg_602_pp0_iter1_reg;
                icmp_ln50_1_reg_602_pp0_iter3_reg <= icmp_ln50_1_reg_602_pp0_iter2_reg;
                icmp_ln50_1_reg_602_pp0_iter4_reg <= icmp_ln50_1_reg_602_pp0_iter3_reg;
                icmp_ln50_1_reg_602_pp0_iter5_reg <= icmp_ln50_1_reg_602_pp0_iter4_reg;
                icmp_ln50_1_reg_602_pp0_iter6_reg <= icmp_ln50_1_reg_602_pp0_iter5_reg;
                icmp_ln50_1_reg_602_pp0_iter7_reg <= icmp_ln50_1_reg_602_pp0_iter6_reg;
                icmp_ln50_1_reg_602_pp0_iter8_reg <= icmp_ln50_1_reg_602_pp0_iter7_reg;
                k_mid2_reg_586 <= k_mid2_fu_284_p3;
                k_mid2_reg_586_pp0_iter1_reg <= k_mid2_reg_586;
                k_mid2_reg_586_pp0_iter2_reg <= k_mid2_reg_586_pp0_iter1_reg;
                select_ln48_reg_591 <= select_ln48_fu_292_p3;
                select_ln48_reg_591_pp0_iter1_reg <= select_ln48_reg_591;
                select_ln48_reg_591_pp0_iter2_reg <= select_ln48_reg_591_pp0_iter1_reg;
                select_ln48_reg_591_pp0_iter3_reg <= select_ln48_reg_591_pp0_iter2_reg;
                select_ln48_reg_591_pp0_iter4_reg <= select_ln48_reg_591_pp0_iter3_reg;
                    zext_ln48_reg_656(3 downto 0) <= zext_ln48_fu_459_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                conv1_i_i_reg_616 <= grp_fu_2102_p_dout0;
                v_reg_636 <= v_fu_434_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                mul_i19_i_reg_691 <= grp_fu_2084_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                mul_i_i_reg_641 <= grp_fu_2084_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                mul_i_reg_646 <= grp_fu_2084_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                x_assign_1_reg_696 <= grp_fu_2080_p_dout0;
            end if;
        end if;
    end process;
    zext_ln48_reg_656(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_block_pp0_stage1_subdone, ap_condition_exit_pp0_iter7_stage1, ap_idle_pp0_0to6, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to8, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to8 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    acc_mid2_fu_444_p3 <= 
        ap_const_lv32_0 when (empty_reg_581_pp0_iter4_reg(0) = '1') else 
        ap_sig_allocacmp_acc_load;
    add_ln38_fu_373_p2 <= std_logic_vector(signed(sext_ln38_fu_369_p1) + signed(ap_const_lv9_1C9));
    add_ln47_1_fu_228_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten24_load) + unsigned(ap_const_lv14_1));
    add_ln47_fu_386_p2 <= std_logic_vector(unsigned(t_fu_96) + unsigned(ap_const_lv8_1));
    add_ln48_1_fu_335_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv7_1));
    add_ln48_fu_272_p2 <= std_logic_vector(unsigned(select_ln47_fu_246_p3) + unsigned(ap_const_lv4_1));
    add_ln50_fu_323_p2 <= std_logic_vector(unsigned(k_mid2_fu_284_p3) + unsigned(ap_const_lv3_1));
    add_ln52_1_fu_412_p2 <= std_logic_vector(signed(sext_ln52_fu_408_p1) + signed(zext_ln47_fu_399_p1));
    add_ln52_fu_403_p2 <= std_logic_vector(unsigned(k_mid2_reg_586_pp0_iter2_reg) + unsigned(ap_const_lv3_5));
    add_ln54_fu_312_p2 <= std_logic_vector(unsigned(tmp_1_fu_304_p3) + unsigned(zext_ln57_fu_300_p1));
    add_ln57_fu_466_p2 <= std_logic_vector(unsigned(tmp_s_fu_452_p3) + unsigned(zext_ln57_1_fu_463_p1));
    and_ln36_fu_516_p2 <= (or_ln36_fu_510_p2 and grp_fu_2105_p_dout0);
    and_ln47_fu_266_p2 <= (xor_ln47_fu_254_p2 and icmp_ln50_fu_260_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln47_reg_572)
    begin
        if (((icmp_ln47_reg_572 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter7_stage1_assign_proc : process(ap_enable_reg_pp0_iter7, icmp_ln47_reg_572_pp0_iter7_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln47_reg_572_pp0_iter7_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter7_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter7_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to6_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to6 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to8_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to8 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to8 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_acc_load_assign_proc : process(ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, acc_fu_80, grp_fu_2080_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_sig_allocacmp_acc_load <= grp_fu_2080_p_dout0;
        else 
            ap_sig_allocacmp_acc_load <= acc_fu_80;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten24_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten24_fu_100)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten24_load <= ap_const_lv14_0;
        else 
            ap_sig_allocacmp_indvar_flatten24_load <= indvar_flatten24_fu_100;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_92)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_92;
        end if; 
    end process;


    ap_sig_allocacmp_k_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_k_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_k_load <= k_fu_84;
        end if; 
    end process;


    ap_sig_allocacmp_oc_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, oc_fu_88)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_oc_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_oc_load <= oc_fu_88;
        end if; 
    end process;

    bitcast_ln36_fu_481_p1 <= x_assign_1_reg_696;
    ecg_cnn_top_float_float_in_2d_2_address0 <= zext_ln53_fu_418_p1(8 - 1 downto 0);
    ecg_cnn_top_float_float_in_2d_2_ce0 <= ecg_cnn_top_float_float_in_2d_2_ce0_local;

    ecg_cnn_top_float_float_in_2d_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ecg_cnn_top_float_float_in_2d_2_ce0_local <= ap_const_logic_1;
        else 
            ecg_cnn_top_float_float_in_2d_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_278_p2 <= (icmp_ln48_fu_240_p2 or and_ln47_fu_266_p2);

    grp_fu_169_p0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, acc_mid2_fu_444_p3, mul_i19_i_reg_691, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_169_p0 <= mul_i19_i_reg_691;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_169_p0 <= acc_mid2_fu_444_p3;
        else 
            grp_fu_169_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_169_p1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, mul_i_reg_646, s1_bn_seq_bias_load_reg_686, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_169_p1 <= s1_bn_seq_bias_load_reg_686;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_169_p1 <= mul_i_reg_646;
        else 
            grp_fu_169_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_173_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, conv1_i_i_reg_616, v_reg_636, acc_2_reg_671, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_173_p0 <= acc_2_reg_671;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_173_p0 <= v_reg_636;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_173_p0 <= conv1_i_i_reg_616;
        else 
            grp_fu_173_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_173_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, mul_i_i_reg_641, s1_bn_seq_scale_load_reg_676, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_173_p1 <= s1_bn_seq_scale_load_reg_676;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_173_p1 <= mul_i_i_reg_641;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_173_p1 <= ap_const_lv32_3C1822EC;
        else 
            grp_fu_173_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_2080_p_ce <= ap_const_logic_1;
    grp_fu_2080_p_din0 <= grp_fu_169_p0;
    grp_fu_2080_p_din1 <= grp_fu_169_p1;
    grp_fu_2080_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_2084_p_ce <= ap_const_logic_1;
    grp_fu_2084_p_din0 <= grp_fu_173_p0;
    grp_fu_2084_p_din1 <= grp_fu_173_p1;
    grp_fu_2102_p_ce <= ap_const_logic_1;
    grp_fu_2102_p_din0 <= sext_ln38_2_fu_379_p1;
    grp_fu_2105_p_ce <= ap_const_logic_1;
    grp_fu_2105_p_din0 <= x_assign_1_reg_696;
    grp_fu_2105_p_din1 <= ap_const_lv32_0;
    grp_fu_2105_p_opcode <= ap_const_lv5_2;
    icmp_ln36_1_fu_504_p2 <= "1" when (trunc_ln36_fu_494_p1 = ap_const_lv23_0) else "0";
    icmp_ln36_fu_498_p2 <= "0" when (tmp_4_fu_484_p4 = ap_const_lv8_FF) else "1";
    icmp_ln47_fu_222_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten24_load = ap_const_lv14_28B0) else "0";
    icmp_ln48_fu_240_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv7_38) else "0";
    icmp_ln50_1_fu_329_p2 <= "1" when (add_ln50_fu_323_p2 = ap_const_lv3_7) else "0";
    icmp_ln50_fu_260_p2 <= "1" when (ap_sig_allocacmp_k_load = ap_const_lv3_7) else "0";
    icmp_ln53_fu_423_p2 <= "1" when (unsigned(add_ln52_1_fu_412_p2) < unsigned(ap_const_lv9_BA)) else "0";
    k_mid2_fu_284_p3 <= 
        ap_const_lv3_0 when (empty_fu_278_p2(0) = '1') else 
        ap_sig_allocacmp_k_load;
    or_ln36_fu_510_p2 <= (icmp_ln36_fu_498_p2 or icmp_ln36_1_fu_504_p2);
    s1_bn_seq_bias_address0 <= zext_ln48_reg_656(3 - 1 downto 0);

    s1_bn_seq_bias_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s1_bn_seq_bias_ce0_local <= ap_const_logic_1;
        else 
            s1_bn_seq_bias_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    s1_bn_seq_scale_address0 <= zext_ln48_fu_459_p1(3 - 1 downto 0);

    s1_bn_seq_scale_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s1_bn_seq_scale_ce0_local <= ap_const_logic_1;
        else 
            s1_bn_seq_scale_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    s1_conv_seq_w_3_address0 <= zext_ln54_fu_318_p1(6 - 1 downto 0);

    s1_conv_seq_w_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s1_conv_seq_w_3_ce0_local <= ap_const_logic_1;
        else 
            s1_conv_seq_w_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    s1_seq_out_address0 <= zext_ln57_2_fu_477_p1(11 - 1 downto 0);
    s1_seq_out_ce0 <= s1_seq_out_ce0_local;

    s1_seq_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            s1_seq_out_ce0_local <= ap_const_logic_1;
        else 
            s1_seq_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    s1_seq_out_d0 <= select_ln36_fu_522_p3;
    s1_seq_out_we0 <= s1_seq_out_we0_local;

    s1_seq_out_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, icmp_ln50_1_reg_602_pp0_iter8_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln50_1_reg_602_pp0_iter8_reg = ap_const_lv1_1))) then 
            s1_seq_out_we0_local <= ap_const_logic_1;
        else 
            s1_seq_out_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln36_fu_522_p3 <= 
        x_assign_1_reg_696 when (and_ln36_fu_516_p2(0) = '1') else 
        ap_const_lv32_0;
    select_ln47_1_fu_392_p3 <= 
        add_ln47_fu_386_p2 when (icmp_ln48_reg_576_pp0_iter2_reg(0) = '1') else 
        t_fu_96;
    select_ln47_fu_246_p3 <= 
        ap_const_lv4_0 when (icmp_ln48_fu_240_p2(0) = '1') else 
        ap_sig_allocacmp_oc_load;
    select_ln48_1_fu_341_p3 <= 
        ap_const_lv7_1 when (icmp_ln48_fu_240_p2(0) = '1') else 
        add_ln48_1_fu_335_p2;
    select_ln48_fu_292_p3 <= 
        add_ln48_fu_272_p2 when (and_ln47_fu_266_p2(0) = '1') else 
        select_ln47_fu_246_p3;
        sext_ln38_2_fu_379_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln38_reg_606),32));

        sext_ln38_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(s1_conv_seq_w_3_q0),9));

        sext_ln52_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln52_fu_403_p2),9));

    tmp_1_fu_304_p3 <= (k_mid2_fu_284_p3 & ap_const_lv3_0);
    tmp_4_fu_484_p4 <= bitcast_ln36_fu_481_p1(30 downto 23);
    tmp_s_fu_452_p3 <= (select_ln47_1_reg_621_pp0_iter4_reg & ap_const_lv3_0);
    trunc_ln36_fu_494_p1 <= bitcast_ln36_fu_481_p1(23 - 1 downto 0);
    v_fu_434_p3 <= 
        ecg_cnn_top_float_float_in_2d_2_q0 when (icmp_ln53_reg_626(0) = '1') else 
        ap_const_lv32_0;
    xor_ln47_fu_254_p2 <= (icmp_ln48_fu_240_p2 xor ap_const_lv1_1);
    zext_ln47_fu_399_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln47_1_fu_392_p3),9));
    zext_ln48_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln48_reg_591_pp0_iter4_reg),64));
    zext_ln53_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln52_1_fu_412_p2),64));
    zext_ln54_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln54_fu_312_p2),64));
    zext_ln57_1_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln48_reg_591_pp0_iter4_reg),11));
    zext_ln57_2_fu_477_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln57_reg_661_pp0_iter8_reg),64));
    zext_ln57_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln48_fu_292_p3),6));
end behav;
