-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_231_5_VITIS_LOOP_232_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tmp_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    tmp_1_ce0 : OUT STD_LOGIC;
    tmp_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    tmp_1_ce1 : OUT STD_LOGIC;
    tmp_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp_1_address2 : OUT STD_LOGIC_VECTOR (10 downto 0);
    tmp_1_ce2 : OUT STD_LOGIC;
    tmp_1_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    s3_out_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    s3_out_ce0 : OUT STD_LOGIC;
    s3_out_we0 : OUT STD_LOGIC;
    s3_out_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2105_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2105_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2105_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_2105_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_2105_p_ce : OUT STD_LOGIC );
end;


architecture behav of ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_231_5_VITIS_LOOP_232_6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_2E0 : STD_LOGIC_VECTOR (9 downto 0) := "1011100000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln231_fu_139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln236_fu_209_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln236_reg_380 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln236_reg_380_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln236_reg_380_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_10_fu_215_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_10_reg_385 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_10_reg_385_pp0_iter1_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln235_fu_228_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln235_reg_395 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln235_reg_395_pp0_iter1_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln236_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln236_reg_415 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln236_1_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln236_1_reg_420 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln236_2_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln236_2_reg_425 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln236_3_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln236_3_reg_430 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln234_fu_223_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln235_fu_234_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln234_1_fu_346_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln236_2_fu_351_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_fu_52 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln232_fu_239_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (5 downto 0);
    signal t_fu_56 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal select_ln231_1_fu_177_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_t_load : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten45_fu_60 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln231_1_fu_145_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten45_load : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_1_ce2_local : STD_LOGIC;
    signal tmp_1_ce1_local : STD_LOGIC;
    signal tmp_1_ce0_local : STD_LOGIC;
    signal s3_out_we0_local : STD_LOGIC;
    signal s3_out_ce0_local : STD_LOGIC;
    signal icmp_ln232_fu_163_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln231_fu_157_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln231_fu_169_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_185_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln236_1_fu_205_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_9_fu_193_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln236_fu_201_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal bitcast_ln236_fu_260_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln236_1_fu_278_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_264_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln236_fu_274_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_12_fu_282_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln236_1_fu_292_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln236_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln236_1_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln236_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln236_1_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln236_fu_340_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ecg_cnn_top_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component ecg_cnn_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component ecg_cnn_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    c_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln231_fu_139_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_52 <= add_ln232_fu_239_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_52 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten45_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln231_fu_139_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten45_fu_60 <= add_ln231_1_fu_145_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten45_fu_60 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    t_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln231_fu_139_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    t_fu_56 <= select_ln231_1_fu_177_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    t_fu_56 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln235_reg_395 <= add_ln235_fu_228_p2;
                add_ln235_reg_395_pp0_iter1_reg <= add_ln235_reg_395;
                add_ln236_reg_380 <= add_ln236_fu_209_p2;
                add_ln236_reg_380_pp0_iter1_reg <= add_ln236_reg_380;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln236_1_reg_420 <= icmp_ln236_1_fu_302_p2;
                icmp_ln236_2_reg_425 <= icmp_ln236_2_fu_308_p2;
                icmp_ln236_3_reg_430 <= icmp_ln236_3_fu_314_p2;
                icmp_ln236_reg_415 <= icmp_ln236_fu_296_p2;
                tmp_10_reg_385 <= tmp_10_fu_215_p3;
                tmp_10_reg_385_pp0_iter1_reg <= tmp_10_reg_385;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln236_reg_380_pp0_iter2_reg <= add_ln236_reg_380_pp0_iter1_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln231_1_fu_145_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten45_load) + unsigned(ap_const_lv10_1));
    add_ln231_fu_157_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_t_load) + unsigned(ap_const_lv5_1));
    add_ln232_fu_239_p2 <= std_logic_vector(unsigned(select_ln231_fu_169_p3) + unsigned(ap_const_lv6_1));
    add_ln235_fu_228_p2 <= std_logic_vector(unsigned(tmp_9_fu_193_p3) + unsigned(zext_ln236_fu_201_p1));
    add_ln236_fu_209_p2 <= std_logic_vector(unsigned(tmp_s_fu_185_p3) + unsigned(zext_ln236_1_fu_205_p1));
    and_ln236_1_fu_334_p2 <= (grp_fu_2105_p_dout0 and and_ln236_fu_328_p2);
    and_ln236_fu_328_p2 <= (or_ln236_fu_320_p2 and or_ln236_1_fu_324_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln231_fu_139_p2)
    begin
        if (((icmp_ln231_fu_139_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, c_fu_52, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_52;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten45_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten45_fu_60)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten45_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten45_load <= indvar_flatten45_fu_60;
        end if; 
    end process;


    ap_sig_allocacmp_t_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, t_fu_56)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_t_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_t_load <= t_fu_56;
        end if; 
    end process;

    bitcast_ln236_1_fu_278_p1 <= tmp_1_q1;
    bitcast_ln236_fu_260_p1 <= tmp_1_q2;
    grp_fu_2105_p_ce <= ap_const_logic_1;
    grp_fu_2105_p_din0 <= tmp_1_q2;
    grp_fu_2105_p_din1 <= tmp_1_q1;
    grp_fu_2105_p_opcode <= ap_const_lv5_2;
    icmp_ln231_fu_139_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten45_load = ap_const_lv10_2E0) else "0";
    icmp_ln232_fu_163_p2 <= "1" when (ap_sig_allocacmp_c_load = ap_const_lv6_20) else "0";
    icmp_ln236_1_fu_302_p2 <= "1" when (trunc_ln236_fu_274_p1 = ap_const_lv23_0) else "0";
    icmp_ln236_2_fu_308_p2 <= "0" when (tmp_12_fu_282_p4 = ap_const_lv8_FF) else "1";
    icmp_ln236_3_fu_314_p2 <= "1" when (trunc_ln236_1_fu_292_p1 = ap_const_lv23_0) else "0";
    icmp_ln236_fu_296_p2 <= "0" when (tmp_11_fu_264_p4 = ap_const_lv8_FF) else "1";
    or_ln236_1_fu_324_p2 <= (icmp_ln236_3_reg_430 or icmp_ln236_2_reg_425);
    or_ln236_fu_320_p2 <= (icmp_ln236_reg_415 or icmp_ln236_1_reg_420);
    s3_out_address0 <= zext_ln236_2_fu_351_p1(10 - 1 downto 0);
    s3_out_ce0 <= s3_out_ce0_local;

    s3_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            s3_out_ce0_local <= ap_const_logic_1;
        else 
            s3_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    s3_out_d0 <= tmp_1_q0;
    s3_out_we0 <= s3_out_we0_local;

    s3_out_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            s3_out_we0_local <= ap_const_logic_1;
        else 
            s3_out_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln231_1_fu_177_p3 <= 
        add_ln231_fu_157_p2 when (icmp_ln232_fu_163_p2(0) = '1') else 
        ap_sig_allocacmp_t_load;
    select_ln231_fu_169_p3 <= 
        ap_const_lv6_0 when (icmp_ln232_fu_163_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    select_ln236_fu_340_p3 <= 
        tmp_10_reg_385_pp0_iter1_reg when (and_ln236_1_fu_334_p2(0) = '1') else 
        add_ln235_reg_395_pp0_iter1_reg;
    tmp_10_fu_215_p3 <= (select_ln231_1_fu_177_p3 & select_ln231_fu_169_p3);
    tmp_11_fu_264_p4 <= bitcast_ln236_fu_260_p1(30 downto 23);
    tmp_12_fu_282_p4 <= bitcast_ln236_1_fu_278_p1(30 downto 23);
    tmp_1_address0 <= zext_ln234_1_fu_346_p1(11 - 1 downto 0);
    tmp_1_address1 <= zext_ln235_fu_234_p1(11 - 1 downto 0);
    tmp_1_address2 <= zext_ln234_fu_223_p1(11 - 1 downto 0);
    tmp_1_ce0 <= tmp_1_ce0_local;

    tmp_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tmp_1_ce0_local <= ap_const_logic_1;
        else 
            tmp_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_ce1 <= tmp_1_ce1_local;

    tmp_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tmp_1_ce1_local <= ap_const_logic_1;
        else 
            tmp_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_ce2 <= tmp_1_ce2_local;

    tmp_1_ce2_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tmp_1_ce2_local <= ap_const_logic_1;
        else 
            tmp_1_ce2_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_9_fu_193_p3 <= (select_ln231_1_fu_177_p3 & ap_const_lv6_20);
    tmp_s_fu_185_p3 <= (select_ln231_1_fu_177_p3 & ap_const_lv5_0);
    trunc_ln236_1_fu_292_p1 <= bitcast_ln236_1_fu_278_p1(23 - 1 downto 0);
    trunc_ln236_fu_274_p1 <= bitcast_ln236_fu_260_p1(23 - 1 downto 0);
    zext_ln234_1_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln236_fu_340_p3),64));
    zext_ln234_fu_223_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_215_p3),64));
    zext_ln235_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln235_fu_228_p2),64));
    zext_ln236_1_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln231_fu_169_p3),10));
    zext_ln236_2_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln236_reg_380_pp0_iter2_reg),64));
    zext_ln236_fu_201_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln231_fu_169_p3),11));
end behav;
