// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_113_1_VITIS_LOOP_114_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s1_A_out_address0,
        s1_A_out_ce0,
        s1_A_out_q0,
        s1_A_out_address1,
        s1_A_out_ce1,
        s1_A_out_q1,
        s1_B_out_address0,
        s1_B_out_ce0,
        s1_B_out_q0,
        s1_B_out_address1,
        s1_B_out_ce1,
        s1_B_out_q1,
        s1_pool_address0,
        s1_pool_ce0,
        s1_pool_we0,
        s1_pool_d0,
        grp_fu_2080_p_din0,
        grp_fu_2080_p_din1,
        grp_fu_2080_p_opcode,
        grp_fu_2080_p_dout0,
        grp_fu_2080_p_ce,
        grp_fu_7257_p_din0,
        grp_fu_7257_p_din1,
        grp_fu_7257_p_opcode,
        grp_fu_7257_p_dout0,
        grp_fu_7257_p_ce,
        grp_fu_2105_p_din0,
        grp_fu_2105_p_din1,
        grp_fu_2105_p_opcode,
        grp_fu_2105_p_dout0,
        grp_fu_2105_p_ce,
        grp_fu_7261_p_din0,
        grp_fu_7261_p_din1,
        grp_fu_7261_p_opcode,
        grp_fu_7261_p_dout0,
        grp_fu_7261_p_ce,
        grp_fu_7265_p_din0,
        grp_fu_7265_p_din1,
        grp_fu_7265_p_opcode,
        grp_fu_7265_p_dout0,
        grp_fu_7265_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] s1_A_out_address0;
output   s1_A_out_ce0;
input  [31:0] s1_A_out_q0;
output  [10:0] s1_A_out_address1;
output   s1_A_out_ce1;
input  [31:0] s1_A_out_q1;
output  [10:0] s1_B_out_address0;
output   s1_B_out_ce0;
input  [31:0] s1_B_out_q0;
output  [10:0] s1_B_out_address1;
output   s1_B_out_ce1;
input  [31:0] s1_B_out_q1;
output  [9:0] s1_pool_address0;
output   s1_pool_ce0;
output   s1_pool_we0;
output  [31:0] s1_pool_d0;
output  [31:0] grp_fu_2080_p_din0;
output  [31:0] grp_fu_2080_p_din1;
output  [0:0] grp_fu_2080_p_opcode;
input  [31:0] grp_fu_2080_p_dout0;
output   grp_fu_2080_p_ce;
output  [31:0] grp_fu_7257_p_din0;
output  [31:0] grp_fu_7257_p_din1;
output  [1:0] grp_fu_7257_p_opcode;
input  [31:0] grp_fu_7257_p_dout0;
output   grp_fu_7257_p_ce;
output  [31:0] grp_fu_2105_p_din0;
output  [31:0] grp_fu_2105_p_din1;
output  [4:0] grp_fu_2105_p_opcode;
input  [0:0] grp_fu_2105_p_dout0;
output   grp_fu_2105_p_ce;
output  [31:0] grp_fu_7261_p_din0;
output  [31:0] grp_fu_7261_p_din1;
output  [4:0] grp_fu_7261_p_opcode;
input  [0:0] grp_fu_7261_p_dout0;
output   grp_fu_7261_p_ce;
output  [31:0] grp_fu_7265_p_din0;
output  [31:0] grp_fu_7265_p_din1;
output  [4:0] grp_fu_7265_p_opcode;
input  [0:0] grp_fu_7265_p_dout0;
output   grp_fu_7265_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln113_fu_173_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [9:0] add_ln118_fu_269_p2;
reg   [9:0] add_ln118_reg_530;
reg   [9:0] add_ln118_reg_530_pp0_iter1_reg;
reg   [9:0] add_ln118_reg_530_pp0_iter2_reg;
reg   [9:0] add_ln118_reg_530_pp0_iter3_reg;
reg   [9:0] add_ln118_reg_530_pp0_iter4_reg;
reg   [9:0] add_ln118_reg_530_pp0_iter5_reg;
reg   [9:0] add_ln118_reg_530_pp0_iter6_reg;
reg   [9:0] add_ln118_reg_530_pp0_iter7_reg;
reg   [9:0] add_ln118_reg_530_pp0_iter8_reg;
reg   [31:0] s1_A_out_load_reg_535;
reg   [31:0] s1_B_out_load_reg_540;
reg   [31:0] s1_A_out_load_1_reg_545;
reg   [31:0] s1_B_out_load_1_reg_550;
reg   [31:0] x_assign_2_reg_555;
reg   [31:0] x_assign_2_reg_555_pp0_iter6_reg;
reg   [31:0] x_assign_3_reg_562;
reg   [31:0] x_assign_3_reg_562_pp0_iter6_reg;
wire   [31:0] v0_fu_337_p3;
reg   [31:0] v0_reg_569;
reg   [31:0] v0_reg_569_pp0_iter8_reg;
wire   [31:0] v1_fu_385_p3;
reg   [31:0] v1_reg_576;
reg   [31:0] v1_reg_576_pp0_iter8_reg;
wire   [63:0] zext_ln116_fu_251_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln117_fu_263_p1;
wire   [63:0] zext_ln118_fu_392_p1;
reg   [3:0] c_fu_58;
wire   [3:0] add_ln114_fu_275_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_c_load;
reg   [6:0] t_fu_62;
wire   [6:0] select_ln113_1_fu_211_p3;
reg   [6:0] ap_sig_allocacmp_t_load;
reg   [9:0] indvar_flatten31_fu_66;
wire   [9:0] add_ln113_1_fu_179_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten31_load;
reg    s1_A_out_ce1_local;
reg    s1_A_out_ce0_local;
reg    s1_B_out_ce1_local;
reg    s1_B_out_ce0_local;
reg    s1_pool_we0_local;
wire   [31:0] select_ln118_fu_478_p3;
reg    s1_pool_ce0_local;
wire   [0:0] icmp_ln114_fu_197_p2;
wire   [6:0] add_ln113_fu_191_p2;
wire   [3:0] select_ln113_fu_203_p3;
wire   [10:0] tmp_25_fu_243_p3;
wire   [10:0] tmp_24_fu_227_p3;
wire   [10:0] zext_ln116_2_fu_239_p1;
wire   [10:0] add_ln117_fu_257_p2;
wire   [9:0] tmp_23_fu_219_p3;
wire   [9:0] zext_ln116_1_fu_235_p1;
wire   [31:0] bitcast_ln36_1_fu_296_p1;
wire   [7:0] tmp_9_fu_299_p4;
wire   [22:0] trunc_ln36_fu_309_p1;
wire   [0:0] icmp_ln36_3_fu_319_p2;
wire   [0:0] icmp_ln36_2_fu_313_p2;
wire   [0:0] or_ln36_1_fu_325_p2;
wire   [0:0] and_ln36_1_fu_331_p2;
wire   [31:0] bitcast_ln36_fu_344_p1;
wire   [7:0] tmp_10_fu_347_p4;
wire   [22:0] trunc_ln36_2_fu_357_p1;
wire   [0:0] icmp_ln36_fu_367_p2;
wire   [0:0] icmp_ln36_4_fu_361_p2;
wire   [0:0] or_ln36_fu_373_p2;
wire   [0:0] and_ln36_fu_379_p2;
wire   [31:0] bitcast_ln118_fu_396_p1;
wire   [31:0] bitcast_ln118_1_fu_413_p1;
wire   [7:0] tmp_12_fu_399_p4;
wire   [22:0] trunc_ln118_fu_409_p1;
wire   [0:0] icmp_ln118_1_fu_436_p2;
wire   [0:0] icmp_ln118_fu_430_p2;
wire   [7:0] tmp_13_fu_416_p4;
wire   [22:0] trunc_ln118_1_fu_426_p1;
wire   [0:0] icmp_ln118_3_fu_454_p2;
wire   [0:0] icmp_ln118_2_fu_448_p2;
wire   [0:0] or_ln118_fu_442_p2;
wire   [0:0] or_ln118_1_fu_460_p2;
wire   [0:0] and_ln118_fu_466_p2;
wire   [0:0] and_ln118_1_fu_472_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 c_fu_58 = 4'd0;
#0 t_fu_62 = 7'd0;
#0 indvar_flatten31_fu_66 = 10'd0;
#0 ap_done_reg = 1'b0;
end

ecg_cnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln113_fu_173_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_58 <= add_ln114_fu_275_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_58 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln113_fu_173_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten31_fu_66 <= add_ln113_1_fu_179_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten31_fu_66 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln113_fu_173_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_62 <= select_ln113_1_fu_211_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_62 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln118_reg_530 <= add_ln118_fu_269_p2;
        add_ln118_reg_530_pp0_iter1_reg <= add_ln118_reg_530;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln118_reg_530_pp0_iter2_reg <= add_ln118_reg_530_pp0_iter1_reg;
        add_ln118_reg_530_pp0_iter3_reg <= add_ln118_reg_530_pp0_iter2_reg;
        add_ln118_reg_530_pp0_iter4_reg <= add_ln118_reg_530_pp0_iter3_reg;
        add_ln118_reg_530_pp0_iter5_reg <= add_ln118_reg_530_pp0_iter4_reg;
        add_ln118_reg_530_pp0_iter6_reg <= add_ln118_reg_530_pp0_iter5_reg;
        add_ln118_reg_530_pp0_iter7_reg <= add_ln118_reg_530_pp0_iter6_reg;
        add_ln118_reg_530_pp0_iter8_reg <= add_ln118_reg_530_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        v0_reg_569 <= v0_fu_337_p3;
        v0_reg_569_pp0_iter8_reg <= v0_reg_569;
        v1_reg_576 <= v1_fu_385_p3;
        v1_reg_576_pp0_iter8_reg <= v1_reg_576;
        x_assign_2_reg_555 <= grp_fu_2080_p_dout0;
        x_assign_2_reg_555_pp0_iter6_reg <= x_assign_2_reg_555;
        x_assign_3_reg_562 <= grp_fu_7257_p_dout0;
        x_assign_3_reg_562_pp0_iter6_reg <= x_assign_3_reg_562;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s1_A_out_load_1_reg_545 <= s1_A_out_q0;
        s1_A_out_load_reg_535 <= s1_A_out_q1;
        s1_B_out_load_1_reg_550 <= s1_B_out_q0;
        s1_B_out_load_reg_540 <= s1_B_out_q1;
    end
end

always @ (*) begin
    if (((icmp_ln113_fu_173_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 4'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten31_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten31_load = indvar_flatten31_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_t_load = 7'd0;
    end else begin
        ap_sig_allocacmp_t_load = t_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s1_A_out_ce0_local = 1'b1;
    end else begin
        s1_A_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s1_A_out_ce1_local = 1'b1;
    end else begin
        s1_A_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s1_B_out_ce0_local = 1'b1;
    end else begin
        s1_B_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s1_B_out_ce1_local = 1'b1;
    end else begin
        s1_B_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        s1_pool_ce0_local = 1'b1;
    end else begin
        s1_pool_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        s1_pool_we0_local = 1'b1;
    end else begin
        s1_pool_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln113_1_fu_179_p2 = (ap_sig_allocacmp_indvar_flatten31_load + 10'd1);

assign add_ln113_fu_191_p2 = (ap_sig_allocacmp_t_load + 7'd1);

assign add_ln114_fu_275_p2 = (select_ln113_fu_203_p3 + 4'd1);

assign add_ln117_fu_257_p2 = (tmp_24_fu_227_p3 + zext_ln116_2_fu_239_p1);

assign add_ln118_fu_269_p2 = (tmp_23_fu_219_p3 + zext_ln116_1_fu_235_p1);

assign and_ln118_1_fu_472_p2 = (grp_fu_7265_p_dout0 & and_ln118_fu_466_p2);

assign and_ln118_fu_466_p2 = (or_ln118_fu_442_p2 & or_ln118_1_fu_460_p2);

assign and_ln36_1_fu_331_p2 = (or_ln36_1_fu_325_p2 & grp_fu_2105_p_dout0);

assign and_ln36_fu_379_p2 = (or_ln36_fu_373_p2 & grp_fu_7261_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln118_1_fu_413_p1 = v1_reg_576_pp0_iter8_reg;

assign bitcast_ln118_fu_396_p1 = v0_reg_569_pp0_iter8_reg;

assign bitcast_ln36_1_fu_296_p1 = x_assign_2_reg_555_pp0_iter6_reg;

assign bitcast_ln36_fu_344_p1 = x_assign_3_reg_562_pp0_iter6_reg;

assign grp_fu_2080_p_ce = 1'b1;

assign grp_fu_2080_p_din0 = s1_A_out_load_reg_535;

assign grp_fu_2080_p_din1 = s1_B_out_load_reg_540;

assign grp_fu_2080_p_opcode = 2'd0;

assign grp_fu_2105_p_ce = 1'b1;

assign grp_fu_2105_p_din0 = x_assign_2_reg_555;

assign grp_fu_2105_p_din1 = 32'd0;

assign grp_fu_2105_p_opcode = 5'd2;

assign grp_fu_7257_p_ce = 1'b1;

assign grp_fu_7257_p_din0 = s1_A_out_load_1_reg_545;

assign grp_fu_7257_p_din1 = s1_B_out_load_1_reg_550;

assign grp_fu_7257_p_opcode = 2'd0;

assign grp_fu_7261_p_ce = 1'b1;

assign grp_fu_7261_p_din0 = x_assign_3_reg_562;

assign grp_fu_7261_p_din1 = 32'd0;

assign grp_fu_7261_p_opcode = 5'd2;

assign grp_fu_7265_p_ce = 1'b1;

assign grp_fu_7265_p_din0 = v0_reg_569;

assign grp_fu_7265_p_din1 = v1_reg_576;

assign grp_fu_7265_p_opcode = 5'd2;

assign icmp_ln113_fu_173_p2 = ((ap_sig_allocacmp_indvar_flatten31_load == 10'd744) ? 1'b1 : 1'b0);

assign icmp_ln114_fu_197_p2 = ((ap_sig_allocacmp_c_load == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln118_1_fu_436_p2 = ((trunc_ln118_fu_409_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln118_2_fu_448_p2 = ((tmp_13_fu_416_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln118_3_fu_454_p2 = ((trunc_ln118_1_fu_426_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln118_fu_430_p2 = ((tmp_12_fu_399_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln36_2_fu_313_p2 = ((tmp_9_fu_299_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln36_3_fu_319_p2 = ((trunc_ln36_fu_309_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln36_4_fu_361_p2 = ((tmp_10_fu_347_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_367_p2 = ((trunc_ln36_2_fu_357_p1 == 23'd0) ? 1'b1 : 1'b0);

assign or_ln118_1_fu_460_p2 = (icmp_ln118_3_fu_454_p2 | icmp_ln118_2_fu_448_p2);

assign or_ln118_fu_442_p2 = (icmp_ln118_fu_430_p2 | icmp_ln118_1_fu_436_p2);

assign or_ln36_1_fu_325_p2 = (icmp_ln36_3_fu_319_p2 | icmp_ln36_2_fu_313_p2);

assign or_ln36_fu_373_p2 = (icmp_ln36_fu_367_p2 | icmp_ln36_4_fu_361_p2);

assign s1_A_out_address0 = zext_ln117_fu_263_p1;

assign s1_A_out_address1 = zext_ln116_fu_251_p1;

assign s1_A_out_ce0 = s1_A_out_ce0_local;

assign s1_A_out_ce1 = s1_A_out_ce1_local;

assign s1_B_out_address0 = zext_ln117_fu_263_p1;

assign s1_B_out_address1 = zext_ln116_fu_251_p1;

assign s1_B_out_ce0 = s1_B_out_ce0_local;

assign s1_B_out_ce1 = s1_B_out_ce1_local;

assign s1_pool_address0 = zext_ln118_fu_392_p1;

assign s1_pool_ce0 = s1_pool_ce0_local;

assign s1_pool_d0 = select_ln118_fu_478_p3;

assign s1_pool_we0 = s1_pool_we0_local;

assign select_ln113_1_fu_211_p3 = ((icmp_ln114_fu_197_p2[0:0] == 1'b1) ? add_ln113_fu_191_p2 : ap_sig_allocacmp_t_load);

assign select_ln113_fu_203_p3 = ((icmp_ln114_fu_197_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_c_load);

assign select_ln118_fu_478_p3 = ((and_ln118_1_fu_472_p2[0:0] == 1'b1) ? v0_reg_569_pp0_iter8_reg : v1_reg_576_pp0_iter8_reg);

assign tmp_10_fu_347_p4 = {{bitcast_ln36_fu_344_p1[30:23]}};

assign tmp_12_fu_399_p4 = {{bitcast_ln118_fu_396_p1[30:23]}};

assign tmp_13_fu_416_p4 = {{bitcast_ln118_1_fu_413_p1[30:23]}};

assign tmp_23_fu_219_p3 = {{select_ln113_1_fu_211_p3}, {3'd0}};

assign tmp_24_fu_227_p3 = {{select_ln113_1_fu_211_p3}, {4'd8}};

assign tmp_25_fu_243_p3 = {{select_ln113_1_fu_211_p3}, {select_ln113_fu_203_p3}};

assign tmp_9_fu_299_p4 = {{bitcast_ln36_1_fu_296_p1[30:23]}};

assign trunc_ln118_1_fu_426_p1 = bitcast_ln118_1_fu_413_p1[22:0];

assign trunc_ln118_fu_409_p1 = bitcast_ln118_fu_396_p1[22:0];

assign trunc_ln36_2_fu_357_p1 = bitcast_ln36_fu_344_p1[22:0];

assign trunc_ln36_fu_309_p1 = bitcast_ln36_1_fu_296_p1[22:0];

assign v0_fu_337_p3 = ((and_ln36_1_fu_331_p2[0:0] == 1'b1) ? x_assign_2_reg_555_pp0_iter6_reg : 32'd0);

assign v1_fu_385_p3 = ((and_ln36_fu_379_p2[0:0] == 1'b1) ? x_assign_3_reg_562_pp0_iter6_reg : 32'd0);

assign zext_ln116_1_fu_235_p1 = select_ln113_fu_203_p3;

assign zext_ln116_2_fu_239_p1 = select_ln113_fu_203_p3;

assign zext_ln116_fu_251_p1 = tmp_25_fu_243_p3;

assign zext_ln117_fu_263_p1 = add_ln117_fu_257_p2;

assign zext_ln118_fu_392_p1 = add_ln118_reg_530_pp0_iter8_reg;

endmodule //ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_113_1_VITIS_LOOP_114_2
