// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ecg_cnn_top_float_float_fc2_out_load,
        ecg_cnn_top_float_float_fc2_out_19_load,
        ecg_cnn_top_float_float_fc2_out_20_load,
        ecg_cnn_top_float_float_fc2_out_21_load,
        ecg_cnn_top_float_float_fc2_out_22_load,
        ecg_cnn_top_float_float_fc2_out_23_load,
        ecg_cnn_top_float_float_fc2_out_24_load,
        ecg_cnn_top_float_float_fc2_out_25_load,
        ecg_cnn_top_float_float_fc2_out_26_load,
        ecg_cnn_top_float_float_fc2_out_27_load,
        p_ZZ11ecg_cnn_topPfS_E7fc2_out_10_load,
        ecg_cnn_top_float_float_fc2_out_56,
        ecg_cnn_top_float_float_fc2_out_57,
        ecg_cnn_top_float_float_fc2_out_58,
        ecg_cnn_top_float_float_fc2_out_59,
        ecg_cnn_top_float_float_fc2_out_60,
        p_ZZ11ecg_cnn_topPfS_E7fc2_out_16_load,
        p_ZZ11ecg_cnn_topPfS_E7fc2_out_17_load,
        p_ZZ11ecg_cnn_topPfS_E7fc2_out_18_load,
        p_ZZ11ecg_cnn_topPfS_E7fc2_out_19_load,
        p_ZZ11ecg_cnn_topPfS_E7fc2_out_20_load,
        ecg_cnn_top_float_float_fc2_out_61,
        ecg_cnn_top_float_float_fc2_out_62,
        ecg_cnn_top_float_float_fc2_out_63,
        ecg_cnn_top_float_float_fc2_out_64,
        ecg_cnn_top_float_float_fc2_out_65,
        p_ZZ11ecg_cnn_topPfS_E7fc2_out_26_load,
        p_ZZ11ecg_cnn_topPfS_E7fc2_out_27_load,
        p_ZZ11ecg_cnn_topPfS_E7fc2_out_28_load,
        p_ZZ11ecg_cnn_topPfS_E7fc2_out_29_load,
        p_ZZ11ecg_cnn_topPfS_E7fc2_out_30_load,
        ecg_cnn_top_float_float_fc2_out,
        mux_case_411816011_out,
        mux_case_411816011_out_ap_vld,
        mux_case_31161559_out,
        mux_case_31161559_out_ap_vld,
        mux_case_21141507_out,
        mux_case_21141507_out_ap_vld,
        mux_case_11121455_out,
        mux_case_11121455_out_ap_vld,
        mx_33_out,
        mx_33_out_ap_vld,
        grp_fu_2080_p_din0,
        grp_fu_2080_p_din1,
        grp_fu_2080_p_opcode,
        grp_fu_2080_p_dout0,
        grp_fu_2080_p_ce,
        grp_fu_2084_p_din0,
        grp_fu_2084_p_din1,
        grp_fu_2084_p_dout0,
        grp_fu_2084_p_ce,
        grp_fu_2102_p_din0,
        grp_fu_2102_p_dout0,
        grp_fu_2102_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] ecg_cnn_top_float_float_fc2_out_load;
input  [31:0] ecg_cnn_top_float_float_fc2_out_19_load;
input  [31:0] ecg_cnn_top_float_float_fc2_out_20_load;
input  [31:0] ecg_cnn_top_float_float_fc2_out_21_load;
input  [31:0] ecg_cnn_top_float_float_fc2_out_22_load;
input  [31:0] ecg_cnn_top_float_float_fc2_out_23_load;
input  [31:0] ecg_cnn_top_float_float_fc2_out_24_load;
input  [31:0] ecg_cnn_top_float_float_fc2_out_25_load;
input  [31:0] ecg_cnn_top_float_float_fc2_out_26_load;
input  [31:0] ecg_cnn_top_float_float_fc2_out_27_load;
input  [31:0] p_ZZ11ecg_cnn_topPfS_E7fc2_out_10_load;
input  [31:0] ecg_cnn_top_float_float_fc2_out_56;
input  [31:0] ecg_cnn_top_float_float_fc2_out_57;
input  [31:0] ecg_cnn_top_float_float_fc2_out_58;
input  [31:0] ecg_cnn_top_float_float_fc2_out_59;
input  [31:0] ecg_cnn_top_float_float_fc2_out_60;
input  [31:0] p_ZZ11ecg_cnn_topPfS_E7fc2_out_16_load;
input  [31:0] p_ZZ11ecg_cnn_topPfS_E7fc2_out_17_load;
input  [31:0] p_ZZ11ecg_cnn_topPfS_E7fc2_out_18_load;
input  [31:0] p_ZZ11ecg_cnn_topPfS_E7fc2_out_19_load;
input  [31:0] p_ZZ11ecg_cnn_topPfS_E7fc2_out_20_load;
input  [31:0] ecg_cnn_top_float_float_fc2_out_61;
input  [31:0] ecg_cnn_top_float_float_fc2_out_62;
input  [31:0] ecg_cnn_top_float_float_fc2_out_63;
input  [31:0] ecg_cnn_top_float_float_fc2_out_64;
input  [31:0] ecg_cnn_top_float_float_fc2_out_65;
input  [31:0] p_ZZ11ecg_cnn_topPfS_E7fc2_out_26_load;
input  [31:0] p_ZZ11ecg_cnn_topPfS_E7fc2_out_27_load;
input  [31:0] p_ZZ11ecg_cnn_topPfS_E7fc2_out_28_load;
input  [31:0] p_ZZ11ecg_cnn_topPfS_E7fc2_out_29_load;
input  [31:0] p_ZZ11ecg_cnn_topPfS_E7fc2_out_30_load;
input  [31:0] ecg_cnn_top_float_float_fc2_out;
output  [31:0] mux_case_411816011_out;
output   mux_case_411816011_out_ap_vld;
output  [31:0] mux_case_31161559_out;
output   mux_case_31161559_out_ap_vld;
output  [31:0] mux_case_21141507_out;
output   mux_case_21141507_out_ap_vld;
output  [31:0] mux_case_11121455_out;
output   mux_case_11121455_out_ap_vld;
output  [31:0] mx_33_out;
output   mx_33_out_ap_vld;
output  [31:0] grp_fu_2080_p_din0;
output  [31:0] grp_fu_2080_p_din1;
output  [0:0] grp_fu_2080_p_opcode;
input  [31:0] grp_fu_2080_p_dout0;
output   grp_fu_2080_p_ce;
output  [31:0] grp_fu_2084_p_din0;
output  [31:0] grp_fu_2084_p_din1;
input  [31:0] grp_fu_2084_p_dout0;
output   grp_fu_2084_p_ce;
output  [31:0] grp_fu_2102_p_din0;
input  [31:0] grp_fu_2102_p_dout0;
output   grp_fu_2102_p_ce;

reg ap_idle;
reg mux_case_411816011_out_ap_vld;
reg mux_case_31161559_out_ap_vld;
reg mux_case_21141507_out_ap_vld;
reg mux_case_11121455_out_ap_vld;
reg mx_33_out_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln325_reg_1229;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] output_w_address0;
wire   [7:0] output_w_q0;
wire   [2:0] output_b_address0;
wire   [7:0] output_b_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln325_fu_567_p2;
reg   [0:0] icmp_ln325_reg_1229_pp0_iter1_reg;
reg   [0:0] icmp_ln325_reg_1229_pp0_iter2_reg;
reg   [0:0] icmp_ln325_reg_1229_pp0_iter3_reg;
reg   [0:0] icmp_ln325_reg_1229_pp0_iter4_reg;
wire   [0:0] icmp_ln327_fu_591_p2;
reg   [0:0] icmp_ln327_reg_1233;
reg   [0:0] icmp_ln327_reg_1233_pp0_iter1_reg;
reg   [0:0] icmp_ln327_reg_1233_pp0_iter2_reg;
reg   [0:0] icmp_ln327_reg_1233_pp0_iter3_reg;
reg   [0:0] icmp_ln327_reg_1233_pp0_iter4_reg;
wire   [2:0] select_ln325_6_fu_605_p3;
reg   [2:0] select_ln325_6_reg_1242;
reg   [2:0] select_ln325_6_reg_1242_pp0_iter1_reg;
reg   [2:0] select_ln325_6_reg_1242_pp0_iter2_reg;
reg   [2:0] select_ln325_6_reg_1242_pp0_iter3_reg;
reg   [2:0] select_ln325_6_reg_1242_pp0_iter4_reg;
reg   [2:0] select_ln325_6_reg_1242_pp0_iter5_reg;
wire   [0:0] first_iter_6_fu_613_p2;
reg   [0:0] first_iter_6_reg_1246;
reg   [0:0] first_iter_6_reg_1246_pp0_iter1_reg;
reg   [0:0] first_iter_6_reg_1246_pp0_iter2_reg;
reg   [0:0] first_iter_6_reg_1246_pp0_iter3_reg;
reg   [0:0] first_iter_6_reg_1246_pp0_iter4_reg;
wire   [31:0] tmp_5_fu_661_p67;
reg   [31:0] tmp_5_reg_1260;
reg   [31:0] tmp_5_reg_1260_pp0_iter1_reg;
reg   [31:0] tmp_5_reg_1260_pp0_iter2_reg;
reg   [31:0] tmp_5_reg_1260_pp0_iter3_reg;
wire   [0:0] icmp_ln327_1_fu_803_p2;
reg   [0:0] icmp_ln327_1_reg_1265;
reg   [0:0] icmp_ln327_1_reg_1265_pp0_iter1_reg;
reg   [0:0] icmp_ln327_1_reg_1265_pp0_iter2_reg;
reg   [0:0] icmp_ln327_1_reg_1265_pp0_iter3_reg;
reg   [0:0] icmp_ln327_1_reg_1265_pp0_iter4_reg;
reg   [0:0] icmp_ln327_1_reg_1265_pp0_iter5_reg;
reg   [7:0] output_b_load_reg_1269;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [8:0] add_ln38_1_fu_840_p2;
reg   [8:0] add_ln38_1_reg_1274;
wire   [8:0] add_ln38_fu_849_p2;
reg   [8:0] add_ln38_reg_1279;
wire    ap_block_pp0_stage2_11001;
wire  signed [31:0] sext_ln38_5_fu_855_p1;
wire  signed [31:0] sext_ln38_3_fu_859_p1;
reg   [31:0] conv1_i26_i_reg_1294;
reg   [31:0] conv1_i_i_reg_1299;
reg   [31:0] mul_i27_i_reg_1304;
reg   [31:0] acc_3_reg_1309;
reg   [31:0] acc_3_reg_1309_pp0_iter4_reg;
reg   [31:0] mul_i_reg_1314;
wire   [63:0] zext_ln325_fu_619_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln329_1_fu_652_p1;
reg   [5:0] i_fu_202;
wire   [5:0] add_ln327_fu_797_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i_load;
reg   [2:0] o_2_fu_206;
reg   [2:0] ap_sig_allocacmp_o_2_load;
reg   [31:0] empty_fu_210;
wire   [31:0] select_ln325_5_fu_929_p3;
reg   [31:0] mux_case_1112144_fu_214;
wire   [31:0] select_ln325_4_fu_922_p3;
reg   [31:0] mux_case_2114149_fu_218;
wire   [31:0] select_ln325_3_fu_915_p3;
reg   [31:0] mux_case_3116154_fu_222;
wire   [31:0] select_ln325_2_fu_908_p3;
reg   [31:0] mux_case_4118159_fu_226;
wire   [31:0] select_ln325_1_fu_901_p3;
reg   [7:0] indvar_flatten59_fu_230;
wire   [7:0] add_ln325_1_fu_573_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten59_load;
reg   [31:0] acc_fu_234;
reg   [31:0] ap_sig_allocacmp_acc_load;
wire    ap_block_pp0_stage2;
reg   [31:0] mx_33_fu_238;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [31:0] mux_case_11121455_fu_242;
reg   [31:0] mux_case_21141507_fu_246;
reg   [31:0] mux_case_31161559_fu_250;
reg   [31:0] mux_case_411816011_fu_254;
wire    ap_block_pp0_stage2_01001;
reg    output_b_ce0_local;
reg    output_w_ce0_local;
reg   [31:0] grp_fu_515_p0;
reg   [31:0] grp_fu_515_p1;
wire    ap_block_pp0_stage1;
reg  signed [31:0] grp_fu_521_p0;
wire   [2:0] add_ln325_fu_585_p2;
wire   [5:0] select_ln325_fu_597_p3;
wire   [7:0] tmp_fu_632_p3;
wire   [7:0] zext_ln329_fu_628_p1;
wire   [7:0] add_ln329_1_fu_640_p2;
wire   [7:0] zext_ln326_fu_624_p1;
wire   [7:0] add_ln329_fu_646_p2;
wire   [31:0] tmp_5_fu_661_p65;
wire   [4:0] tmp_5_fu_661_p66;
wire  signed [8:0] sext_ln38_4_fu_836_p1;
wire  signed [8:0] sext_ln38_fu_846_p1;
wire    ap_block_pp0_stage2_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to5;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] tmp_5_fu_661_p1;
wire   [4:0] tmp_5_fu_661_p3;
wire   [4:0] tmp_5_fu_661_p5;
wire   [4:0] tmp_5_fu_661_p7;
wire   [4:0] tmp_5_fu_661_p9;
wire   [4:0] tmp_5_fu_661_p11;
wire   [4:0] tmp_5_fu_661_p13;
wire   [4:0] tmp_5_fu_661_p15;
wire   [4:0] tmp_5_fu_661_p17;
wire   [4:0] tmp_5_fu_661_p19;
wire   [4:0] tmp_5_fu_661_p21;
wire   [4:0] tmp_5_fu_661_p23;
wire   [4:0] tmp_5_fu_661_p25;
wire   [4:0] tmp_5_fu_661_p27;
wire   [4:0] tmp_5_fu_661_p29;
wire   [4:0] tmp_5_fu_661_p31;
wire  signed [4:0] tmp_5_fu_661_p33;
wire  signed [4:0] tmp_5_fu_661_p35;
wire  signed [4:0] tmp_5_fu_661_p37;
wire  signed [4:0] tmp_5_fu_661_p39;
wire  signed [4:0] tmp_5_fu_661_p41;
wire  signed [4:0] tmp_5_fu_661_p43;
wire  signed [4:0] tmp_5_fu_661_p45;
wire  signed [4:0] tmp_5_fu_661_p47;
wire  signed [4:0] tmp_5_fu_661_p49;
wire  signed [4:0] tmp_5_fu_661_p51;
wire  signed [4:0] tmp_5_fu_661_p53;
wire  signed [4:0] tmp_5_fu_661_p55;
wire  signed [4:0] tmp_5_fu_661_p57;
wire  signed [4:0] tmp_5_fu_661_p59;
wire  signed [4:0] tmp_5_fu_661_p61;
wire  signed [4:0] tmp_5_fu_661_p63;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_202 = 6'd0;
#0 o_2_fu_206 = 3'd0;
#0 empty_fu_210 = 32'd0;
#0 mux_case_1112144_fu_214 = 32'd0;
#0 mux_case_2114149_fu_218 = 32'd0;
#0 mux_case_3116154_fu_222 = 32'd0;
#0 mux_case_4118159_fu_226 = 32'd0;
#0 indvar_flatten59_fu_230 = 8'd0;
#0 acc_fu_234 = 32'd0;
#0 mx_33_fu_238 = 32'd0;
#0 mux_case_11121455_fu_242 = 32'd0;
#0 mux_case_21141507_fu_246 = 32'd0;
#0 mux_case_31161559_fu_250 = 32'd0;
#0 mux_case_411816011_fu_254 = 32'd0;
#0 ap_done_reg = 1'b0;
end

ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2_output_w_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 160 ),
    .AddressWidth( 8 ))
output_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(output_w_address0),
    .ce0(output_w_ce0_local),
    .q0(output_w_q0)
);

ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2_output_b_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
output_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(output_b_address0),
    .ce0(output_b_ce0_local),
    .q0(output_b_q0)
);

(* dissolve_hierarchy = "yes" *) ecg_cnn_top_sparsemux_65_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 32 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 32 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 32 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 32 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 32 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 32 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 32 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_65_5_32_1_1_U257(
    .din0(ecg_cnn_top_float_float_fc2_out_load),
    .din1(ecg_cnn_top_float_float_fc2_out_19_load),
    .din2(ecg_cnn_top_float_float_fc2_out_20_load),
    .din3(ecg_cnn_top_float_float_fc2_out_21_load),
    .din4(ecg_cnn_top_float_float_fc2_out_22_load),
    .din5(ecg_cnn_top_float_float_fc2_out_23_load),
    .din6(ecg_cnn_top_float_float_fc2_out_24_load),
    .din7(ecg_cnn_top_float_float_fc2_out_25_load),
    .din8(ecg_cnn_top_float_float_fc2_out_26_load),
    .din9(ecg_cnn_top_float_float_fc2_out_27_load),
    .din10(p_ZZ11ecg_cnn_topPfS_E7fc2_out_10_load),
    .din11(ecg_cnn_top_float_float_fc2_out_56),
    .din12(ecg_cnn_top_float_float_fc2_out_57),
    .din13(ecg_cnn_top_float_float_fc2_out_58),
    .din14(ecg_cnn_top_float_float_fc2_out_59),
    .din15(ecg_cnn_top_float_float_fc2_out_60),
    .din16(p_ZZ11ecg_cnn_topPfS_E7fc2_out_16_load),
    .din17(p_ZZ11ecg_cnn_topPfS_E7fc2_out_17_load),
    .din18(p_ZZ11ecg_cnn_topPfS_E7fc2_out_18_load),
    .din19(p_ZZ11ecg_cnn_topPfS_E7fc2_out_19_load),
    .din20(p_ZZ11ecg_cnn_topPfS_E7fc2_out_20_load),
    .din21(ecg_cnn_top_float_float_fc2_out_61),
    .din22(ecg_cnn_top_float_float_fc2_out_62),
    .din23(ecg_cnn_top_float_float_fc2_out_63),
    .din24(ecg_cnn_top_float_float_fc2_out_64),
    .din25(ecg_cnn_top_float_float_fc2_out_65),
    .din26(p_ZZ11ecg_cnn_topPfS_E7fc2_out_26_load),
    .din27(p_ZZ11ecg_cnn_topPfS_E7fc2_out_27_load),
    .din28(p_ZZ11ecg_cnn_topPfS_E7fc2_out_28_load),
    .din29(p_ZZ11ecg_cnn_topPfS_E7fc2_out_29_load),
    .din30(p_ZZ11ecg_cnn_topPfS_E7fc2_out_30_load),
    .din31(ecg_cnn_top_float_float_fc2_out),
    .def(tmp_5_fu_661_p65),
    .sel(tmp_5_fu_661_p66),
    .dout(tmp_5_fu_661_p67)
);

ecg_cnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        if (((ap_enable_reg_pp0_iter4 == 1'b1) & (first_iter_6_reg_1246_pp0_iter4_reg == 1'd1))) begin
            acc_fu_234 <= acc_3_reg_1309_pp0_iter4_reg;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            acc_fu_234 <= grp_fu_2080_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_fu_210 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            empty_fu_210 <= select_ln325_5_fu_929_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln325_fu_567_p2 == 1'd0))) begin
            i_fu_202 <= add_ln327_fu_797_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_202 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln325_fu_567_p2 == 1'd0))) begin
            indvar_flatten59_fu_230 <= add_ln325_1_fu_573_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten59_fu_230 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            mux_case_1112144_fu_214 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            mux_case_1112144_fu_214 <= select_ln325_4_fu_922_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd0) & ~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd1) & ~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd2) & ~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd2) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd3) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        mux_case_11121455_fu_242 <= select_ln325_4_fu_922_p3;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter5_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter5_reg == 3'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mux_case_11121455_fu_242 <= grp_fu_2080_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            mux_case_2114149_fu_218 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            mux_case_2114149_fu_218 <= select_ln325_3_fu_915_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd0) & ~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd1) & ~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd2) & ~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd3) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        mux_case_21141507_fu_246 <= select_ln325_3_fu_915_p3;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter5_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter5_reg == 3'd2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mux_case_21141507_fu_246 <= grp_fu_2080_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            mux_case_3116154_fu_222 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            mux_case_3116154_fu_222 <= select_ln325_2_fu_908_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd0) & ~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd1) & ~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd2) & ~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd2) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        mux_case_31161559_fu_250 <= select_ln325_2_fu_908_p3;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter5_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter5_reg == 3'd3) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mux_case_31161559_fu_250 <= grp_fu_2080_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            mux_case_4118159_fu_226 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            mux_case_4118159_fu_226 <= select_ln325_1_fu_901_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd2) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd3) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        mux_case_411816011_fu_254 <= select_ln325_1_fu_901_p3;
    end else if ((~(select_ln325_6_reg_1242_pp0_iter5_reg == 3'd3) & ~(select_ln325_6_reg_1242_pp0_iter5_reg == 3'd2) & ~(select_ln325_6_reg_1242_pp0_iter5_reg == 3'd1) & ~(select_ln325_6_reg_1242_pp0_iter5_reg == 3'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter5_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mux_case_411816011_fu_254 <= grp_fu_2080_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd0) & ~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd1) & ~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd2) & ~(select_ln325_6_reg_1242_pp0_iter4_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd2) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter4_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter4_reg == 3'd3) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        mx_33_fu_238 <= select_ln325_5_fu_929_p3;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln327_1_reg_1265_pp0_iter5_reg == 1'd1) & (select_ln325_6_reg_1242_pp0_iter5_reg == 3'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mx_33_fu_238 <= grp_fu_2080_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln325_fu_567_p2 == 1'd0))) begin
            o_2_fu_206 <= select_ln325_6_fu_605_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            o_2_fu_206 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_3_reg_1309 <= grp_fu_2084_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_3_reg_1309_pp0_iter4_reg <= acc_3_reg_1309;
        first_iter_6_reg_1246 <= first_iter_6_fu_613_p2;
        first_iter_6_reg_1246_pp0_iter1_reg <= first_iter_6_reg_1246;
        first_iter_6_reg_1246_pp0_iter2_reg <= first_iter_6_reg_1246_pp0_iter1_reg;
        first_iter_6_reg_1246_pp0_iter3_reg <= first_iter_6_reg_1246_pp0_iter2_reg;
        first_iter_6_reg_1246_pp0_iter4_reg <= first_iter_6_reg_1246_pp0_iter3_reg;
        icmp_ln325_reg_1229 <= icmp_ln325_fu_567_p2;
        icmp_ln325_reg_1229_pp0_iter1_reg <= icmp_ln325_reg_1229;
        icmp_ln325_reg_1229_pp0_iter2_reg <= icmp_ln325_reg_1229_pp0_iter1_reg;
        icmp_ln325_reg_1229_pp0_iter3_reg <= icmp_ln325_reg_1229_pp0_iter2_reg;
        icmp_ln325_reg_1229_pp0_iter4_reg <= icmp_ln325_reg_1229_pp0_iter3_reg;
        icmp_ln327_1_reg_1265 <= icmp_ln327_1_fu_803_p2;
        icmp_ln327_1_reg_1265_pp0_iter1_reg <= icmp_ln327_1_reg_1265;
        icmp_ln327_1_reg_1265_pp0_iter2_reg <= icmp_ln327_1_reg_1265_pp0_iter1_reg;
        icmp_ln327_1_reg_1265_pp0_iter3_reg <= icmp_ln327_1_reg_1265_pp0_iter2_reg;
        icmp_ln327_1_reg_1265_pp0_iter4_reg <= icmp_ln327_1_reg_1265_pp0_iter3_reg;
        icmp_ln327_1_reg_1265_pp0_iter5_reg <= icmp_ln327_1_reg_1265_pp0_iter4_reg;
        icmp_ln327_reg_1233 <= icmp_ln327_fu_591_p2;
        icmp_ln327_reg_1233_pp0_iter1_reg <= icmp_ln327_reg_1233;
        icmp_ln327_reg_1233_pp0_iter2_reg <= icmp_ln327_reg_1233_pp0_iter1_reg;
        icmp_ln327_reg_1233_pp0_iter3_reg <= icmp_ln327_reg_1233_pp0_iter2_reg;
        icmp_ln327_reg_1233_pp0_iter4_reg <= icmp_ln327_reg_1233_pp0_iter3_reg;
        select_ln325_6_reg_1242 <= select_ln325_6_fu_605_p3;
        select_ln325_6_reg_1242_pp0_iter1_reg <= select_ln325_6_reg_1242;
        select_ln325_6_reg_1242_pp0_iter2_reg <= select_ln325_6_reg_1242_pp0_iter1_reg;
        select_ln325_6_reg_1242_pp0_iter3_reg <= select_ln325_6_reg_1242_pp0_iter2_reg;
        select_ln325_6_reg_1242_pp0_iter4_reg <= select_ln325_6_reg_1242_pp0_iter3_reg;
        select_ln325_6_reg_1242_pp0_iter5_reg <= select_ln325_6_reg_1242_pp0_iter4_reg;
        tmp_5_reg_1260 <= tmp_5_fu_661_p67;
        tmp_5_reg_1260_pp0_iter1_reg <= tmp_5_reg_1260;
        tmp_5_reg_1260_pp0_iter2_reg <= tmp_5_reg_1260_pp0_iter1_reg;
        tmp_5_reg_1260_pp0_iter3_reg <= tmp_5_reg_1260_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln38_1_reg_1274 <= add_ln38_1_fu_840_p2;
        output_b_load_reg_1269 <= output_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln38_reg_1279 <= add_ln38_fu_849_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        conv1_i26_i_reg_1294 <= grp_fu_2102_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_i_i_reg_1299 <= grp_fu_2102_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul_i27_i_reg_1304 <= grp_fu_2084_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_i_reg_1314 <= grp_fu_2084_p_dout0;
    end
end

always @ (*) begin
    if (((icmp_ln325_reg_1229 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        if (((ap_enable_reg_pp0_iter4 == 1'b1) & (first_iter_6_reg_1246_pp0_iter4_reg == 1'd1))) begin
            ap_sig_allocacmp_acc_load = acc_3_reg_1309_pp0_iter4_reg;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            ap_sig_allocacmp_acc_load = grp_fu_2080_p_dout0;
        end else begin
            ap_sig_allocacmp_acc_load = acc_fu_234;
        end
    end else begin
        ap_sig_allocacmp_acc_load = acc_fu_234;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 6'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_202;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten59_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten59_load = indvar_flatten59_fu_230;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_o_2_load = 3'd0;
    end else begin
        ap_sig_allocacmp_o_2_load = o_2_fu_206;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_515_p0 = tmp_5_reg_1260_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_515_p0 = conv1_i_i_reg_1299;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_515_p0 = conv1_i26_i_reg_1294;
    end else begin
        grp_fu_515_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_515_p1 = mul_i27_i_reg_1304;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_515_p1 = 32'd986407615;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_515_p1 = 32'd1000021459;
    end else begin
        grp_fu_515_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_521_p0 = sext_ln38_3_fu_859_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_521_p0 = sext_ln38_5_fu_855_p1;
    end else begin
        grp_fu_521_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln325_reg_1229_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mux_case_11121455_out_ap_vld = 1'b1;
    end else begin
        mux_case_11121455_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln325_reg_1229_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mux_case_21141507_out_ap_vld = 1'b1;
    end else begin
        mux_case_21141507_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln325_reg_1229_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mux_case_31161559_out_ap_vld = 1'b1;
    end else begin
        mux_case_31161559_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln325_reg_1229_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mux_case_411816011_out_ap_vld = 1'b1;
    end else begin
        mux_case_411816011_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln325_reg_1229_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mx_33_out_ap_vld = 1'b1;
    end else begin
        mx_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_b_ce0_local = 1'b1;
    end else begin
        output_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_w_ce0_local = 1'b1;
    end else begin
        output_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln325_1_fu_573_p2 = (ap_sig_allocacmp_indvar_flatten59_load + 8'd1);

assign add_ln325_fu_585_p2 = (ap_sig_allocacmp_o_2_load + 3'd1);

assign add_ln327_fu_797_p2 = (select_ln325_fu_597_p3 + 6'd1);

assign add_ln329_1_fu_640_p2 = (tmp_fu_632_p3 + zext_ln329_fu_628_p1);

assign add_ln329_fu_646_p2 = (add_ln329_1_fu_640_p2 + zext_ln326_fu_624_p1);

assign add_ln38_1_fu_840_p2 = ($signed(sext_ln38_4_fu_836_p1) + $signed(9'd493));

assign add_ln38_fu_849_p2 = ($signed(sext_ln38_fu_846_p1) + $signed(9'd8));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_ready = ap_ready_sig;

assign first_iter_6_fu_613_p2 = ((select_ln325_fu_597_p3 == 6'd0) ? 1'b1 : 1'b0);

assign grp_fu_2080_p_ce = 1'b1;

assign grp_fu_2080_p_din0 = ap_sig_allocacmp_acc_load;

assign grp_fu_2080_p_din1 = mul_i_reg_1314;

assign grp_fu_2080_p_opcode = 2'd0;

assign grp_fu_2084_p_ce = 1'b1;

assign grp_fu_2084_p_din0 = grp_fu_515_p0;

assign grp_fu_2084_p_din1 = grp_fu_515_p1;

assign grp_fu_2102_p_ce = 1'b1;

assign grp_fu_2102_p_din0 = grp_fu_521_p0;

assign icmp_ln325_fu_567_p2 = ((ap_sig_allocacmp_indvar_flatten59_load == 8'd160) ? 1'b1 : 1'b0);

assign icmp_ln327_1_fu_803_p2 = ((add_ln327_fu_797_p2 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln327_fu_591_p2 = ((ap_sig_allocacmp_i_load == 6'd32) ? 1'b1 : 1'b0);

assign mux_case_11121455_out = mux_case_11121455_fu_242;

assign mux_case_21141507_out = mux_case_21141507_fu_246;

assign mux_case_31161559_out = mux_case_31161559_fu_250;

assign mux_case_411816011_out = mux_case_411816011_fu_254;

assign mx_33_out = mx_33_fu_238;

assign output_b_address0 = zext_ln325_fu_619_p1;

assign output_w_address0 = zext_ln329_1_fu_652_p1;

assign select_ln325_1_fu_901_p3 = ((icmp_ln327_reg_1233_pp0_iter4_reg[0:0] == 1'b1) ? mux_case_411816011_fu_254 : mux_case_4118159_fu_226);

assign select_ln325_2_fu_908_p3 = ((icmp_ln327_reg_1233_pp0_iter4_reg[0:0] == 1'b1) ? mux_case_31161559_fu_250 : mux_case_3116154_fu_222);

assign select_ln325_3_fu_915_p3 = ((icmp_ln327_reg_1233_pp0_iter4_reg[0:0] == 1'b1) ? mux_case_21141507_fu_246 : mux_case_2114149_fu_218);

assign select_ln325_4_fu_922_p3 = ((icmp_ln327_reg_1233_pp0_iter4_reg[0:0] == 1'b1) ? mux_case_11121455_fu_242 : mux_case_1112144_fu_214);

assign select_ln325_5_fu_929_p3 = ((icmp_ln327_reg_1233_pp0_iter4_reg[0:0] == 1'b1) ? mx_33_fu_238 : empty_fu_210);

assign select_ln325_6_fu_605_p3 = ((icmp_ln327_fu_591_p2[0:0] == 1'b1) ? add_ln325_fu_585_p2 : ap_sig_allocacmp_o_2_load);

assign select_ln325_fu_597_p3 = ((icmp_ln327_fu_591_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_i_load);

assign sext_ln38_3_fu_859_p1 = $signed(add_ln38_reg_1279);

assign sext_ln38_4_fu_836_p1 = $signed(output_w_q0);

assign sext_ln38_5_fu_855_p1 = $signed(add_ln38_1_reg_1274);

assign sext_ln38_fu_846_p1 = $signed(output_b_load_reg_1269);

assign tmp_5_fu_661_p65 = 'bx;

assign tmp_5_fu_661_p66 = select_ln325_fu_597_p3[4:0];

assign tmp_fu_632_p3 = {{select_ln325_fu_597_p3}, {2'd0}};

assign zext_ln325_fu_619_p1 = select_ln325_6_fu_605_p3;

assign zext_ln326_fu_624_p1 = select_ln325_6_fu_605_p3;

assign zext_ln329_1_fu_652_p1 = add_ln329_fu_646_p2;

assign zext_ln329_fu_628_p1 = select_ln325_fu_597_p3;

endmodule //ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2
