-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_296_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    acc_27 : IN STD_LOGIC_VECTOR (31 downto 0);
    zext_ln294 : IN STD_LOGIC_VECTOR (5 downto 0);
    ecg_cnn_top_float_float_gap_out_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_1_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_2_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_4_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_5_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_6_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_7_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_8_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_9_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_10_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_93 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_94 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_95 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_96 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_97 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_16_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_17_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_18_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_19_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_20_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_98 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_99 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_100 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_101 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_102 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_26_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_27_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_28_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_29_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_30_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_103 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_104 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_105 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_106 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_107 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_36_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_37_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_38_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_39_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_40_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_108 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_109 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_110 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_111 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_112 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_46_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_47_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_48_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_49_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_50_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_113 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_114 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_115 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_116 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_117 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_56_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_57_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_58_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_59_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7gap_out_60_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_118 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out_119 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_gap_out : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_31_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_31_out_ap_vld : OUT STD_LOGIC;
    grp_fu_2080_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_2080_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_ce : OUT STD_LOGIC;
    grp_fu_2084_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2084_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2084_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2084_p_ce : OUT STD_LOGIC;
    grp_fu_2102_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2102_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2102_p_ce : OUT STD_LOGIC );
end;


architecture behav of ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_296_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_3C3D80DF : STD_LOGIC_VECTOR (31 downto 0) := "00111100001111011000000011011111";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv9_1FE : STD_LOGIC_VECTOR (8 downto 0) := "111111110";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln296_reg_1093 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal fc1_w_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal fc1_w_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln296_fu_753_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln296_reg_1093_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln296_reg_1093_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln296_reg_1093_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln296_reg_1093_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_782_p131 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_reg_1102 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_reg_1102_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_reg_1102_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_reg_1102_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln38_fu_1055_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln38_reg_1107 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal sext_ln38_7_fu_1061_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal conv1_i12_i_reg_1117 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i13_i_reg_1122 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i8_reg_1127 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal zext_ln298_fu_777_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal acc_fu_304 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_load_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter4_stage1 : STD_LOGIC;
    signal ap_idle_pp0_0to3 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal i_fu_308 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln296_fu_759_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal fc1_w_ce0_local : STD_LOGIC;
    signal grp_fu_732_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_732_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal trunc_ln296_fu_765_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln_fu_769_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_2_fu_782_p129 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln38_fu_1051_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage1_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to5 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_2_fu_782_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p17 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p19 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p21 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p23 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p25 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p27 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p29 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p31 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p33 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p35 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p37 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p39 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p41 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p43 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p45 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p47 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p49 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p51 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p53 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p55 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p57 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p59 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p61 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p63 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p65 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p67 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p69 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p71 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p73 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p75 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p77 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p79 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p81 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p83 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p85 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p87 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p89 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p91 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p93 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p95 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p97 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p99 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p101 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p103 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p105 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p107 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p109 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p111 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p113 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p115 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p117 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p119 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p121 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p123 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p125 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_782_p127 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component ecg_cnn_top_faddfsub_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_sitofp_32s_32_4_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_sparsemux_129_6_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (5 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (5 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (5 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (5 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (5 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (5 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (5 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (5 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (5 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (5 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (5 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (5 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (5 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (5 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (5 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (5 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (5 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (5 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (5 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (5 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (5 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (5 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (5 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (5 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (5 downto 0);
        din24_WIDTH : INTEGER;
        CASE25 : STD_LOGIC_VECTOR (5 downto 0);
        din25_WIDTH : INTEGER;
        CASE26 : STD_LOGIC_VECTOR (5 downto 0);
        din26_WIDTH : INTEGER;
        CASE27 : STD_LOGIC_VECTOR (5 downto 0);
        din27_WIDTH : INTEGER;
        CASE28 : STD_LOGIC_VECTOR (5 downto 0);
        din28_WIDTH : INTEGER;
        CASE29 : STD_LOGIC_VECTOR (5 downto 0);
        din29_WIDTH : INTEGER;
        CASE30 : STD_LOGIC_VECTOR (5 downto 0);
        din30_WIDTH : INTEGER;
        CASE31 : STD_LOGIC_VECTOR (5 downto 0);
        din31_WIDTH : INTEGER;
        CASE32 : STD_LOGIC_VECTOR (5 downto 0);
        din32_WIDTH : INTEGER;
        CASE33 : STD_LOGIC_VECTOR (5 downto 0);
        din33_WIDTH : INTEGER;
        CASE34 : STD_LOGIC_VECTOR (5 downto 0);
        din34_WIDTH : INTEGER;
        CASE35 : STD_LOGIC_VECTOR (5 downto 0);
        din35_WIDTH : INTEGER;
        CASE36 : STD_LOGIC_VECTOR (5 downto 0);
        din36_WIDTH : INTEGER;
        CASE37 : STD_LOGIC_VECTOR (5 downto 0);
        din37_WIDTH : INTEGER;
        CASE38 : STD_LOGIC_VECTOR (5 downto 0);
        din38_WIDTH : INTEGER;
        CASE39 : STD_LOGIC_VECTOR (5 downto 0);
        din39_WIDTH : INTEGER;
        CASE40 : STD_LOGIC_VECTOR (5 downto 0);
        din40_WIDTH : INTEGER;
        CASE41 : STD_LOGIC_VECTOR (5 downto 0);
        din41_WIDTH : INTEGER;
        CASE42 : STD_LOGIC_VECTOR (5 downto 0);
        din42_WIDTH : INTEGER;
        CASE43 : STD_LOGIC_VECTOR (5 downto 0);
        din43_WIDTH : INTEGER;
        CASE44 : STD_LOGIC_VECTOR (5 downto 0);
        din44_WIDTH : INTEGER;
        CASE45 : STD_LOGIC_VECTOR (5 downto 0);
        din45_WIDTH : INTEGER;
        CASE46 : STD_LOGIC_VECTOR (5 downto 0);
        din46_WIDTH : INTEGER;
        CASE47 : STD_LOGIC_VECTOR (5 downto 0);
        din47_WIDTH : INTEGER;
        CASE48 : STD_LOGIC_VECTOR (5 downto 0);
        din48_WIDTH : INTEGER;
        CASE49 : STD_LOGIC_VECTOR (5 downto 0);
        din49_WIDTH : INTEGER;
        CASE50 : STD_LOGIC_VECTOR (5 downto 0);
        din50_WIDTH : INTEGER;
        CASE51 : STD_LOGIC_VECTOR (5 downto 0);
        din51_WIDTH : INTEGER;
        CASE52 : STD_LOGIC_VECTOR (5 downto 0);
        din52_WIDTH : INTEGER;
        CASE53 : STD_LOGIC_VECTOR (5 downto 0);
        din53_WIDTH : INTEGER;
        CASE54 : STD_LOGIC_VECTOR (5 downto 0);
        din54_WIDTH : INTEGER;
        CASE55 : STD_LOGIC_VECTOR (5 downto 0);
        din55_WIDTH : INTEGER;
        CASE56 : STD_LOGIC_VECTOR (5 downto 0);
        din56_WIDTH : INTEGER;
        CASE57 : STD_LOGIC_VECTOR (5 downto 0);
        din57_WIDTH : INTEGER;
        CASE58 : STD_LOGIC_VECTOR (5 downto 0);
        din58_WIDTH : INTEGER;
        CASE59 : STD_LOGIC_VECTOR (5 downto 0);
        din59_WIDTH : INTEGER;
        CASE60 : STD_LOGIC_VECTOR (5 downto 0);
        din60_WIDTH : INTEGER;
        CASE61 : STD_LOGIC_VECTOR (5 downto 0);
        din61_WIDTH : INTEGER;
        CASE62 : STD_LOGIC_VECTOR (5 downto 0);
        din62_WIDTH : INTEGER;
        CASE63 : STD_LOGIC_VECTOR (5 downto 0);
        din63_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        din16 : IN STD_LOGIC_VECTOR (31 downto 0);
        din17 : IN STD_LOGIC_VECTOR (31 downto 0);
        din18 : IN STD_LOGIC_VECTOR (31 downto 0);
        din19 : IN STD_LOGIC_VECTOR (31 downto 0);
        din20 : IN STD_LOGIC_VECTOR (31 downto 0);
        din21 : IN STD_LOGIC_VECTOR (31 downto 0);
        din22 : IN STD_LOGIC_VECTOR (31 downto 0);
        din23 : IN STD_LOGIC_VECTOR (31 downto 0);
        din24 : IN STD_LOGIC_VECTOR (31 downto 0);
        din25 : IN STD_LOGIC_VECTOR (31 downto 0);
        din26 : IN STD_LOGIC_VECTOR (31 downto 0);
        din27 : IN STD_LOGIC_VECTOR (31 downto 0);
        din28 : IN STD_LOGIC_VECTOR (31 downto 0);
        din29 : IN STD_LOGIC_VECTOR (31 downto 0);
        din30 : IN STD_LOGIC_VECTOR (31 downto 0);
        din31 : IN STD_LOGIC_VECTOR (31 downto 0);
        din32 : IN STD_LOGIC_VECTOR (31 downto 0);
        din33 : IN STD_LOGIC_VECTOR (31 downto 0);
        din34 : IN STD_LOGIC_VECTOR (31 downto 0);
        din35 : IN STD_LOGIC_VECTOR (31 downto 0);
        din36 : IN STD_LOGIC_VECTOR (31 downto 0);
        din37 : IN STD_LOGIC_VECTOR (31 downto 0);
        din38 : IN STD_LOGIC_VECTOR (31 downto 0);
        din39 : IN STD_LOGIC_VECTOR (31 downto 0);
        din40 : IN STD_LOGIC_VECTOR (31 downto 0);
        din41 : IN STD_LOGIC_VECTOR (31 downto 0);
        din42 : IN STD_LOGIC_VECTOR (31 downto 0);
        din43 : IN STD_LOGIC_VECTOR (31 downto 0);
        din44 : IN STD_LOGIC_VECTOR (31 downto 0);
        din45 : IN STD_LOGIC_VECTOR (31 downto 0);
        din46 : IN STD_LOGIC_VECTOR (31 downto 0);
        din47 : IN STD_LOGIC_VECTOR (31 downto 0);
        din48 : IN STD_LOGIC_VECTOR (31 downto 0);
        din49 : IN STD_LOGIC_VECTOR (31 downto 0);
        din50 : IN STD_LOGIC_VECTOR (31 downto 0);
        din51 : IN STD_LOGIC_VECTOR (31 downto 0);
        din52 : IN STD_LOGIC_VECTOR (31 downto 0);
        din53 : IN STD_LOGIC_VECTOR (31 downto 0);
        din54 : IN STD_LOGIC_VECTOR (31 downto 0);
        din55 : IN STD_LOGIC_VECTOR (31 downto 0);
        din56 : IN STD_LOGIC_VECTOR (31 downto 0);
        din57 : IN STD_LOGIC_VECTOR (31 downto 0);
        din58 : IN STD_LOGIC_VECTOR (31 downto 0);
        din59 : IN STD_LOGIC_VECTOR (31 downto 0);
        din60 : IN STD_LOGIC_VECTOR (31 downto 0);
        din61 : IN STD_LOGIC_VECTOR (31 downto 0);
        din62 : IN STD_LOGIC_VECTOR (31 downto 0);
        din63 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_296_2_fc1_w_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component ecg_cnn_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fc1_w_U : component ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_296_2_fc1_w_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => fc1_w_address0,
        ce0 => fc1_w_ce0_local,
        q0 => fc1_w_q0);

    sparsemux_129_6_32_1_1_U112 : component ecg_cnn_top_sparsemux_129_6_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 32,
        CASE1 => "000001",
        din1_WIDTH => 32,
        CASE2 => "000010",
        din2_WIDTH => 32,
        CASE3 => "000011",
        din3_WIDTH => 32,
        CASE4 => "000100",
        din4_WIDTH => 32,
        CASE5 => "000101",
        din5_WIDTH => 32,
        CASE6 => "000110",
        din6_WIDTH => 32,
        CASE7 => "000111",
        din7_WIDTH => 32,
        CASE8 => "001000",
        din8_WIDTH => 32,
        CASE9 => "001001",
        din9_WIDTH => 32,
        CASE10 => "001010",
        din10_WIDTH => 32,
        CASE11 => "001011",
        din11_WIDTH => 32,
        CASE12 => "001100",
        din12_WIDTH => 32,
        CASE13 => "001101",
        din13_WIDTH => 32,
        CASE14 => "001110",
        din14_WIDTH => 32,
        CASE15 => "001111",
        din15_WIDTH => 32,
        CASE16 => "010000",
        din16_WIDTH => 32,
        CASE17 => "010001",
        din17_WIDTH => 32,
        CASE18 => "010010",
        din18_WIDTH => 32,
        CASE19 => "010011",
        din19_WIDTH => 32,
        CASE20 => "010100",
        din20_WIDTH => 32,
        CASE21 => "010101",
        din21_WIDTH => 32,
        CASE22 => "010110",
        din22_WIDTH => 32,
        CASE23 => "010111",
        din23_WIDTH => 32,
        CASE24 => "011000",
        din24_WIDTH => 32,
        CASE25 => "011001",
        din25_WIDTH => 32,
        CASE26 => "011010",
        din26_WIDTH => 32,
        CASE27 => "011011",
        din27_WIDTH => 32,
        CASE28 => "011100",
        din28_WIDTH => 32,
        CASE29 => "011101",
        din29_WIDTH => 32,
        CASE30 => "011110",
        din30_WIDTH => 32,
        CASE31 => "011111",
        din31_WIDTH => 32,
        CASE32 => "100000",
        din32_WIDTH => 32,
        CASE33 => "100001",
        din33_WIDTH => 32,
        CASE34 => "100010",
        din34_WIDTH => 32,
        CASE35 => "100011",
        din35_WIDTH => 32,
        CASE36 => "100100",
        din36_WIDTH => 32,
        CASE37 => "100101",
        din37_WIDTH => 32,
        CASE38 => "100110",
        din38_WIDTH => 32,
        CASE39 => "100111",
        din39_WIDTH => 32,
        CASE40 => "101000",
        din40_WIDTH => 32,
        CASE41 => "101001",
        din41_WIDTH => 32,
        CASE42 => "101010",
        din42_WIDTH => 32,
        CASE43 => "101011",
        din43_WIDTH => 32,
        CASE44 => "101100",
        din44_WIDTH => 32,
        CASE45 => "101101",
        din45_WIDTH => 32,
        CASE46 => "101110",
        din46_WIDTH => 32,
        CASE47 => "101111",
        din47_WIDTH => 32,
        CASE48 => "110000",
        din48_WIDTH => 32,
        CASE49 => "110001",
        din49_WIDTH => 32,
        CASE50 => "110010",
        din50_WIDTH => 32,
        CASE51 => "110011",
        din51_WIDTH => 32,
        CASE52 => "110100",
        din52_WIDTH => 32,
        CASE53 => "110101",
        din53_WIDTH => 32,
        CASE54 => "110110",
        din54_WIDTH => 32,
        CASE55 => "110111",
        din55_WIDTH => 32,
        CASE56 => "111000",
        din56_WIDTH => 32,
        CASE57 => "111001",
        din57_WIDTH => 32,
        CASE58 => "111010",
        din58_WIDTH => 32,
        CASE59 => "111011",
        din59_WIDTH => 32,
        CASE60 => "111100",
        din60_WIDTH => 32,
        CASE61 => "111101",
        din61_WIDTH => 32,
        CASE62 => "111110",
        din62_WIDTH => 32,
        CASE63 => "111111",
        din63_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => ecg_cnn_top_float_float_gap_out_load,
        din1 => ecg_cnn_top_float_float_gap_out_1_load,
        din2 => ecg_cnn_top_float_float_gap_out_2_load,
        din3 => ecg_cnn_top_float_float_gap_out_3_load,
        din4 => ecg_cnn_top_float_float_gap_out_4_load,
        din5 => ecg_cnn_top_float_float_gap_out_5_load,
        din6 => ecg_cnn_top_float_float_gap_out_6_load,
        din7 => ecg_cnn_top_float_float_gap_out_7_load,
        din8 => ecg_cnn_top_float_float_gap_out_8_load,
        din9 => ecg_cnn_top_float_float_gap_out_9_load,
        din10 => p_ZZ11ecg_cnn_topPfS_E7gap_out_10_load,
        din11 => ecg_cnn_top_float_float_gap_out_93,
        din12 => ecg_cnn_top_float_float_gap_out_94,
        din13 => ecg_cnn_top_float_float_gap_out_95,
        din14 => ecg_cnn_top_float_float_gap_out_96,
        din15 => ecg_cnn_top_float_float_gap_out_97,
        din16 => p_ZZ11ecg_cnn_topPfS_E7gap_out_16_load,
        din17 => p_ZZ11ecg_cnn_topPfS_E7gap_out_17_load,
        din18 => p_ZZ11ecg_cnn_topPfS_E7gap_out_18_load,
        din19 => p_ZZ11ecg_cnn_topPfS_E7gap_out_19_load,
        din20 => p_ZZ11ecg_cnn_topPfS_E7gap_out_20_load,
        din21 => ecg_cnn_top_float_float_gap_out_98,
        din22 => ecg_cnn_top_float_float_gap_out_99,
        din23 => ecg_cnn_top_float_float_gap_out_100,
        din24 => ecg_cnn_top_float_float_gap_out_101,
        din25 => ecg_cnn_top_float_float_gap_out_102,
        din26 => p_ZZ11ecg_cnn_topPfS_E7gap_out_26_load,
        din27 => p_ZZ11ecg_cnn_topPfS_E7gap_out_27_load,
        din28 => p_ZZ11ecg_cnn_topPfS_E7gap_out_28_load,
        din29 => p_ZZ11ecg_cnn_topPfS_E7gap_out_29_load,
        din30 => p_ZZ11ecg_cnn_topPfS_E7gap_out_30_load,
        din31 => ecg_cnn_top_float_float_gap_out_103,
        din32 => ecg_cnn_top_float_float_gap_out_104,
        din33 => ecg_cnn_top_float_float_gap_out_105,
        din34 => ecg_cnn_top_float_float_gap_out_106,
        din35 => ecg_cnn_top_float_float_gap_out_107,
        din36 => p_ZZ11ecg_cnn_topPfS_E7gap_out_36_load,
        din37 => p_ZZ11ecg_cnn_topPfS_E7gap_out_37_load,
        din38 => p_ZZ11ecg_cnn_topPfS_E7gap_out_38_load,
        din39 => p_ZZ11ecg_cnn_topPfS_E7gap_out_39_load,
        din40 => p_ZZ11ecg_cnn_topPfS_E7gap_out_40_load,
        din41 => ecg_cnn_top_float_float_gap_out_108,
        din42 => ecg_cnn_top_float_float_gap_out_109,
        din43 => ecg_cnn_top_float_float_gap_out_110,
        din44 => ecg_cnn_top_float_float_gap_out_111,
        din45 => ecg_cnn_top_float_float_gap_out_112,
        din46 => p_ZZ11ecg_cnn_topPfS_E7gap_out_46_load,
        din47 => p_ZZ11ecg_cnn_topPfS_E7gap_out_47_load,
        din48 => p_ZZ11ecg_cnn_topPfS_E7gap_out_48_load,
        din49 => p_ZZ11ecg_cnn_topPfS_E7gap_out_49_load,
        din50 => p_ZZ11ecg_cnn_topPfS_E7gap_out_50_load,
        din51 => ecg_cnn_top_float_float_gap_out_113,
        din52 => ecg_cnn_top_float_float_gap_out_114,
        din53 => ecg_cnn_top_float_float_gap_out_115,
        din54 => ecg_cnn_top_float_float_gap_out_116,
        din55 => ecg_cnn_top_float_float_gap_out_117,
        din56 => p_ZZ11ecg_cnn_topPfS_E7gap_out_56_load,
        din57 => p_ZZ11ecg_cnn_topPfS_E7gap_out_57_load,
        din58 => p_ZZ11ecg_cnn_topPfS_E7gap_out_58_load,
        din59 => p_ZZ11ecg_cnn_topPfS_E7gap_out_59_load,
        din60 => p_ZZ11ecg_cnn_topPfS_E7gap_out_60_load,
        din61 => ecg_cnn_top_float_float_gap_out_118,
        din62 => ecg_cnn_top_float_float_gap_out_119,
        din63 => ecg_cnn_top_float_float_gap_out,
        def => tmp_2_fu_782_p129,
        sel => trunc_ln296_fu_765_p1,
        dout => tmp_2_fu_782_p131);

    flow_control_loop_pipe_sequential_init_U : component ecg_cnn_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_304_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                acc_fu_304 <= acc_27;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                acc_fu_304 <= grp_fu_2080_p_dout0;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage1))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage1))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    i_fu_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln296_fu_753_p2 = ap_const_lv1_0))) then 
                    i_fu_308 <= add_ln296_fu_759_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_308 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln38_reg_1107 <= add_ln38_fu_1055_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                conv1_i12_i_reg_1117 <= grp_fu_2102_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln296_reg_1093 <= icmp_ln296_fu_753_p2;
                icmp_ln296_reg_1093_pp0_iter1_reg <= icmp_ln296_reg_1093;
                icmp_ln296_reg_1093_pp0_iter2_reg <= icmp_ln296_reg_1093_pp0_iter1_reg;
                icmp_ln296_reg_1093_pp0_iter3_reg <= icmp_ln296_reg_1093_pp0_iter2_reg;
                icmp_ln296_reg_1093_pp0_iter4_reg <= icmp_ln296_reg_1093_pp0_iter3_reg;
                tmp_2_reg_1102 <= tmp_2_fu_782_p131;
                tmp_2_reg_1102_pp0_iter1_reg <= tmp_2_reg_1102;
                tmp_2_reg_1102_pp0_iter2_reg <= tmp_2_reg_1102_pp0_iter1_reg;
                tmp_2_reg_1102_pp0_iter3_reg <= tmp_2_reg_1102_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                mul_i13_i_reg_1122 <= grp_fu_2084_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                mul_i8_reg_1127 <= grp_fu_2084_p_dout0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_block_pp0_stage1_subdone, ap_condition_exit_pp0_iter4_stage1, ap_idle_pp0_0to3, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to5, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to5 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if (((ap_idle_pp0_0to3 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    acc_31_out <= acc_fu_304;

    acc_31_out_ap_vld_assign_proc : process(icmp_ln296_reg_1093_pp0_iter4_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln296_reg_1093_pp0_iter4_reg = ap_const_lv1_1))) then 
            acc_31_out_ap_vld <= ap_const_logic_1;
        else 
            acc_31_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln296_fu_759_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv7_1));
    add_ln38_fu_1055_p2 <= std_logic_vector(signed(sext_ln38_fu_1051_p1) + signed(ap_const_lv9_1FE));
    add_ln_fu_769_p3 <= (trunc_ln296_fu_765_p1 & zext_ln294);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln296_reg_1093)
    begin
        if (((icmp_ln296_reg_1093 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter4_stage1_assign_proc : process(ap_enable_reg_pp0_iter4, icmp_ln296_reg_1093_pp0_iter4_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln296_reg_1093_pp0_iter4_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter4_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter4_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready_pp0_iter4_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to5 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to5 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_acc_load_4_assign_proc : process(ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, acc_fu_304, ap_block_pp0_stage1, grp_fu_2080_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_sig_allocacmp_acc_load_4 <= grp_fu_2080_p_dout0;
        else 
            ap_sig_allocacmp_acc_load_4 <= acc_fu_304;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_308)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_308;
        end if; 
    end process;

    fc1_w_address0 <= zext_ln298_fu_777_p1(12 - 1 downto 0);

    fc1_w_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fc1_w_ce0_local <= ap_const_logic_1;
        else 
            fc1_w_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_2080_p_ce <= ap_const_logic_1;
    grp_fu_2080_p_din0 <= ap_sig_allocacmp_acc_load_4;
    grp_fu_2080_p_din1 <= mul_i8_reg_1127;
    grp_fu_2080_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_2084_p_ce <= ap_const_logic_1;
    grp_fu_2084_p_din0 <= grp_fu_732_p0;
    grp_fu_2084_p_din1 <= grp_fu_732_p1;
    grp_fu_2102_p_ce <= ap_const_logic_1;
    grp_fu_2102_p_din0 <= sext_ln38_7_fu_1061_p1;

    grp_fu_732_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, tmp_2_reg_1102_pp0_iter3_reg, ap_CS_fsm_pp0_stage1, conv1_i12_i_reg_1117, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_732_p0 <= tmp_2_reg_1102_pp0_iter3_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_732_p0 <= conv1_i12_i_reg_1117;
        else 
            grp_fu_732_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_732_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, mul_i13_i_reg_1122, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_732_p1 <= mul_i13_i_reg_1122;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_732_p1 <= ap_const_lv32_3C3D80DF;
        else 
            grp_fu_732_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln296_fu_753_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv7_40) else "0";
        sext_ln38_7_fu_1061_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln38_reg_1107),32));

        sext_ln38_fu_1051_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(fc1_w_q0),9));

    tmp_2_fu_782_p129 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln296_fu_765_p1 <= ap_sig_allocacmp_i_2(6 - 1 downto 0);
    zext_ln298_fu_777_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln_fu_769_p3),64));
end behav;
