-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity ecg_cnn_top_fc2_b_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of ecg_cnn_top_fc2_b_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11110101", 1 => "11110000", 2 => "10000000", 3 => "00110000", 
    4 => "10101101", 5 => "11110101", 6 => "11101100", 7 => "11110001", 
    8 => "10111001", 9 => "00001111", 10 => "10011111", 11 => "10110001", 
    12 => "11011100", 13 => "00000101", 14 => "11010111", 15 => "10011000", 
    16 => "01010000", 17 => "11011000", 18 => "11001010", 19 => "01000111", 
    20 => "10110001", 21 => "10101101", 22 => "10100100", 23 => "11010110", 
    24 => "10101010", 25 => "11010001", 26 => "10111101", 27 => "10100110", 
    28 => "01111111", 29 => "11110110", 30 => "11010100", 31 => "11111001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

