-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity ecg_cnn_top_fc2_bn_bias_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of ecg_cnn_top_fc2_bn_bias_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111111000101001100000010101111", 1 => "00111111001000100011110101110011", 2 => "00111111000101010100110011011011", 3 => "00111111010000110001100111100100", 
    4 => "00111111000010101100110100111100", 5 => "00111111001110100000110100010010", 6 => "00111111000110101011111011100100", 7 => "00111111000111110111101000010000", 
    8 => "00111111000100111110010000101010", 9 => "00111111001001111101011111000110", 10 => "00111111001000111001101111110100", 11 => "00111111001010111100100011000101", 
    12 => "00111111010011010011000000100110", 13 => "00111111001001101111101010011010", 14 => "00111111001000001101010101010011", 15 => "00111111000110110011110101100010", 
    16 => "00111111001000100101011101101011", 17 => "00111111000100000001000111111101", 18 => "00111111001100100100111111101101", 19 => "00111111001010000000001100110101", 
    20 => "00111111001111001111010000000101", 21 => "00111111000001101101101011111101", 22 => "00111111001011111111000110000010", 23 => "00111111001110010111001101111010", 
    24 => "00111111000111001011100011111000", 25 => "00111111001011010111011000101100", 26 => "00111111000111010001111011100011", 27 => "00111111001111001111010100110100", 
    28 => "00111111000011011110111110110101", 29 => "00111111001010010110101101001111", 30 => "00111111000100110110011111001110", 31 => "00111111000110010101000100000001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

