-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ecg_cnn_top_float_float_fc2_out_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_19_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_20_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_21_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_22_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_23_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_24_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_25_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_26_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_27_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7fc2_out_10_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_56 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_57 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_58 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_59 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_60 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7fc2_out_16_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7fc2_out_17_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7fc2_out_18_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7fc2_out_19_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7fc2_out_20_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_61 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_62 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_63 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_64 : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out_65 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7fc2_out_26_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7fc2_out_27_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7fc2_out_28_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7fc2_out_29_load : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ11ecg_cnn_topPfS_E7fc2_out_30_load : IN STD_LOGIC_VECTOR (31 downto 0);
    ecg_cnn_top_float_float_fc2_out : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_411816011_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_411816011_out_ap_vld : OUT STD_LOGIC;
    mux_case_31161559_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_31161559_out_ap_vld : OUT STD_LOGIC;
    mux_case_21141507_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_21141507_out_ap_vld : OUT STD_LOGIC;
    mux_case_11121455_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_11121455_out_ap_vld : OUT STD_LOGIC;
    mx_33_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mx_33_out_ap_vld : OUT STD_LOGIC;
    grp_fu_2080_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_2080_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2080_p_ce : OUT STD_LOGIC;
    grp_fu_2084_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2084_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2084_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2084_p_ce : OUT STD_LOGIC;
    grp_fu_2102_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2102_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2102_p_ce : OUT STD_LOGIC );
end;


architecture behav of ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_3B9B1DD3 : STD_LOGIC_VECTOR (31 downto 0) := "00111011100110110001110111010011";
    constant ap_const_lv32_3ACB62BF : STD_LOGIC_VECTOR (31 downto 0) := "00111010110010110110001010111111";
    constant ap_const_lv8_A0 : STD_LOGIC_VECTOR (7 downto 0) := "10100000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv9_1ED : STD_LOGIC_VECTOR (8 downto 0) := "111101101";
    constant ap_const_lv9_8 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln325_reg_1229 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal output_w_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal output_w_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal output_b_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal output_b_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln325_fu_567_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln325_reg_1229_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln325_reg_1229_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln325_reg_1229_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln325_reg_1229_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln327_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln327_reg_1233 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln327_reg_1233_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln327_reg_1233_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln327_reg_1233_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln327_reg_1233_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln325_6_fu_605_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln325_6_reg_1242 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln325_6_reg_1242_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln325_6_reg_1242_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln325_6_reg_1242_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln325_6_reg_1242_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln325_6_reg_1242_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal first_iter_6_fu_613_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_6_reg_1246 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_6_reg_1246_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_6_reg_1246_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_6_reg_1246_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_6_reg_1246_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_661_p67 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_reg_1260 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_reg_1260_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_reg_1260_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_reg_1260_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln327_1_fu_803_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln327_1_reg_1265 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln327_1_reg_1265_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln327_1_reg_1265_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln327_1_reg_1265_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln327_1_reg_1265_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln327_1_reg_1265_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal output_b_load_reg_1269 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal add_ln38_1_fu_840_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln38_1_reg_1274 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln38_fu_849_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln38_reg_1279 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal sext_ln38_5_fu_855_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln38_3_fu_859_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv1_i26_i_reg_1294 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv1_i_i_reg_1299 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i27_i_reg_1304 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_3_reg_1309 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_3_reg_1309_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i_reg_1314 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln325_fu_619_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln329_1_fu_652_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_202 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln327_fu_797_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (5 downto 0);
    signal o_2_fu_206 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal ap_sig_allocacmp_o_2_load : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_fu_210 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln325_5_fu_929_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_1112144_fu_214 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln325_4_fu_922_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_2114149_fu_218 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln325_3_fu_915_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_3116154_fu_222 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln325_2_fu_908_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_4118159_fu_226 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln325_1_fu_901_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten59_fu_230 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln325_1_fu_573_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten59_load : STD_LOGIC_VECTOR (7 downto 0);
    signal acc_fu_234 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_acc_load : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal mx_33_fu_238 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal mux_case_11121455_fu_242 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal mux_case_21141507_fu_246 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal mux_case_31161559_fu_250 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal mux_case_411816011_fu_254 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage2_01001 : BOOLEAN;
    signal output_b_ce0_local : STD_LOGIC;
    signal output_w_ce0_local : STD_LOGIC;
    signal grp_fu_515_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_515_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal grp_fu_521_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln325_fu_585_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln325_fu_597_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_632_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln329_fu_628_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln329_1_fu_640_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln326_fu_624_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln329_fu_646_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_661_p65 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_661_p66 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln38_4_fu_836_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln38_fu_846_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage2_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to5 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_5_fu_661_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p5 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p7 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p9 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p11 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p13 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p15 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p17 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p19 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p21 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p23 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p25 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p27 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p29 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p31 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p35 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p37 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p39 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p41 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p43 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p45 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p47 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p49 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p51 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p53 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p55 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p57 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p59 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p61 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_661_p63 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component ecg_cnn_top_faddfsub_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_sitofp_32s_32_4_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_sparsemux_65_5_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (4 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (4 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (4 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (4 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (4 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (4 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (4 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (4 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (4 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (4 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (4 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (4 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (4 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (4 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (4 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (4 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (4 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (4 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (4 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (4 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (4 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (4 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (4 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (4 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (4 downto 0);
        din24_WIDTH : INTEGER;
        CASE25 : STD_LOGIC_VECTOR (4 downto 0);
        din25_WIDTH : INTEGER;
        CASE26 : STD_LOGIC_VECTOR (4 downto 0);
        din26_WIDTH : INTEGER;
        CASE27 : STD_LOGIC_VECTOR (4 downto 0);
        din27_WIDTH : INTEGER;
        CASE28 : STD_LOGIC_VECTOR (4 downto 0);
        din28_WIDTH : INTEGER;
        CASE29 : STD_LOGIC_VECTOR (4 downto 0);
        din29_WIDTH : INTEGER;
        CASE30 : STD_LOGIC_VECTOR (4 downto 0);
        din30_WIDTH : INTEGER;
        CASE31 : STD_LOGIC_VECTOR (4 downto 0);
        din31_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        din16 : IN STD_LOGIC_VECTOR (31 downto 0);
        din17 : IN STD_LOGIC_VECTOR (31 downto 0);
        din18 : IN STD_LOGIC_VECTOR (31 downto 0);
        din19 : IN STD_LOGIC_VECTOR (31 downto 0);
        din20 : IN STD_LOGIC_VECTOR (31 downto 0);
        din21 : IN STD_LOGIC_VECTOR (31 downto 0);
        din22 : IN STD_LOGIC_VECTOR (31 downto 0);
        din23 : IN STD_LOGIC_VECTOR (31 downto 0);
        din24 : IN STD_LOGIC_VECTOR (31 downto 0);
        din25 : IN STD_LOGIC_VECTOR (31 downto 0);
        din26 : IN STD_LOGIC_VECTOR (31 downto 0);
        din27 : IN STD_LOGIC_VECTOR (31 downto 0);
        din28 : IN STD_LOGIC_VECTOR (31 downto 0);
        din29 : IN STD_LOGIC_VECTOR (31 downto 0);
        din30 : IN STD_LOGIC_VECTOR (31 downto 0);
        din31 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2_output_w_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2_output_b_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component ecg_cnn_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    output_w_U : component ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2_output_w_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 160,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => output_w_address0,
        ce0 => output_w_ce0_local,
        q0 => output_w_q0);

    output_b_U : component ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2_output_b_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => output_b_address0,
        ce0 => output_b_ce0_local,
        q0 => output_b_q0);

    sparsemux_65_5_32_1_1_U257 : component ecg_cnn_top_sparsemux_65_5_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000",
        din0_WIDTH => 32,
        CASE1 => "00001",
        din1_WIDTH => 32,
        CASE2 => "00010",
        din2_WIDTH => 32,
        CASE3 => "00011",
        din3_WIDTH => 32,
        CASE4 => "00100",
        din4_WIDTH => 32,
        CASE5 => "00101",
        din5_WIDTH => 32,
        CASE6 => "00110",
        din6_WIDTH => 32,
        CASE7 => "00111",
        din7_WIDTH => 32,
        CASE8 => "01000",
        din8_WIDTH => 32,
        CASE9 => "01001",
        din9_WIDTH => 32,
        CASE10 => "01010",
        din10_WIDTH => 32,
        CASE11 => "01011",
        din11_WIDTH => 32,
        CASE12 => "01100",
        din12_WIDTH => 32,
        CASE13 => "01101",
        din13_WIDTH => 32,
        CASE14 => "01110",
        din14_WIDTH => 32,
        CASE15 => "01111",
        din15_WIDTH => 32,
        CASE16 => "10000",
        din16_WIDTH => 32,
        CASE17 => "10001",
        din17_WIDTH => 32,
        CASE18 => "10010",
        din18_WIDTH => 32,
        CASE19 => "10011",
        din19_WIDTH => 32,
        CASE20 => "10100",
        din20_WIDTH => 32,
        CASE21 => "10101",
        din21_WIDTH => 32,
        CASE22 => "10110",
        din22_WIDTH => 32,
        CASE23 => "10111",
        din23_WIDTH => 32,
        CASE24 => "11000",
        din24_WIDTH => 32,
        CASE25 => "11001",
        din25_WIDTH => 32,
        CASE26 => "11010",
        din26_WIDTH => 32,
        CASE27 => "11011",
        din27_WIDTH => 32,
        CASE28 => "11100",
        din28_WIDTH => 32,
        CASE29 => "11101",
        din29_WIDTH => 32,
        CASE30 => "11110",
        din30_WIDTH => 32,
        CASE31 => "11111",
        din31_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 5,
        dout_WIDTH => 32)
    port map (
        din0 => ecg_cnn_top_float_float_fc2_out_load,
        din1 => ecg_cnn_top_float_float_fc2_out_19_load,
        din2 => ecg_cnn_top_float_float_fc2_out_20_load,
        din3 => ecg_cnn_top_float_float_fc2_out_21_load,
        din4 => ecg_cnn_top_float_float_fc2_out_22_load,
        din5 => ecg_cnn_top_float_float_fc2_out_23_load,
        din6 => ecg_cnn_top_float_float_fc2_out_24_load,
        din7 => ecg_cnn_top_float_float_fc2_out_25_load,
        din8 => ecg_cnn_top_float_float_fc2_out_26_load,
        din9 => ecg_cnn_top_float_float_fc2_out_27_load,
        din10 => p_ZZ11ecg_cnn_topPfS_E7fc2_out_10_load,
        din11 => ecg_cnn_top_float_float_fc2_out_56,
        din12 => ecg_cnn_top_float_float_fc2_out_57,
        din13 => ecg_cnn_top_float_float_fc2_out_58,
        din14 => ecg_cnn_top_float_float_fc2_out_59,
        din15 => ecg_cnn_top_float_float_fc2_out_60,
        din16 => p_ZZ11ecg_cnn_topPfS_E7fc2_out_16_load,
        din17 => p_ZZ11ecg_cnn_topPfS_E7fc2_out_17_load,
        din18 => p_ZZ11ecg_cnn_topPfS_E7fc2_out_18_load,
        din19 => p_ZZ11ecg_cnn_topPfS_E7fc2_out_19_load,
        din20 => p_ZZ11ecg_cnn_topPfS_E7fc2_out_20_load,
        din21 => ecg_cnn_top_float_float_fc2_out_61,
        din22 => ecg_cnn_top_float_float_fc2_out_62,
        din23 => ecg_cnn_top_float_float_fc2_out_63,
        din24 => ecg_cnn_top_float_float_fc2_out_64,
        din25 => ecg_cnn_top_float_float_fc2_out_65,
        din26 => p_ZZ11ecg_cnn_topPfS_E7fc2_out_26_load,
        din27 => p_ZZ11ecg_cnn_topPfS_E7fc2_out_27_load,
        din28 => p_ZZ11ecg_cnn_topPfS_E7fc2_out_28_load,
        din29 => p_ZZ11ecg_cnn_topPfS_E7fc2_out_29_load,
        din30 => p_ZZ11ecg_cnn_topPfS_E7fc2_out_30_load,
        din31 => ecg_cnn_top_float_float_fc2_out,
        def => tmp_5_fu_661_p65,
        sel => tmp_5_fu_661_p66,
        dout => tmp_5_fu_661_p67);

    flow_control_loop_pipe_sequential_init_U : component ecg_cnn_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (first_iter_6_reg_1246_pp0_iter4_reg = ap_const_lv1_1))) then 
                    acc_fu_234 <= acc_3_reg_1309_pp0_iter4_reg;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    acc_fu_234 <= grp_fu_2080_p_dout0;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_210_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_fu_210 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    empty_fu_210 <= select_ln325_5_fu_929_p3;
                end if;
            end if; 
        end if;
    end process;

    i_fu_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln325_fu_567_p2 = ap_const_lv1_0))) then 
                    i_fu_202 <= add_ln327_fu_797_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_202 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten59_fu_230_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln325_fu_567_p2 = ap_const_lv1_0))) then 
                    indvar_flatten59_fu_230 <= add_ln325_1_fu_573_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten59_fu_230 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    mux_case_1112144_fu_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    mux_case_1112144_fu_214 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    mux_case_1112144_fu_214 <= select_ln325_4_fu_922_p3;
                end if;
            end if; 
        end if;
    end process;

    mux_case_11121455_fu_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_0)) and not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_1)) and not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_2)) and not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_3)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 
    = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                mux_case_11121455_fu_242 <= select_ln325_4_fu_922_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter5_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter5_reg = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                mux_case_11121455_fu_242 <= grp_fu_2080_p_dout0;
            end if; 
        end if;
    end process;

    mux_case_2114149_fu_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    mux_case_2114149_fu_218 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    mux_case_2114149_fu_218 <= select_ln325_3_fu_915_p3;
                end if;
            end if; 
        end if;
    end process;

    mux_case_21141507_fu_246_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_0)) and not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_1)) and not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_2)) and not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_3)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 
    = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                mux_case_21141507_fu_246 <= select_ln325_3_fu_915_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter5_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter5_reg = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                mux_case_21141507_fu_246 <= grp_fu_2080_p_dout0;
            end if; 
        end if;
    end process;

    mux_case_3116154_fu_222_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    mux_case_3116154_fu_222 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    mux_case_3116154_fu_222 <= select_ln325_2_fu_908_p3;
                end if;
            end if; 
        end if;
    end process;

    mux_case_31161559_fu_250_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_0)) and not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_1)) and not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_2)) and not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_3)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 
    = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                mux_case_31161559_fu_250 <= select_ln325_2_fu_908_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter5_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter5_reg = ap_const_lv3_3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                mux_case_31161559_fu_250 <= grp_fu_2080_p_dout0;
            end if; 
        end if;
    end process;

    mux_case_4118159_fu_226_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    mux_case_4118159_fu_226 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    mux_case_4118159_fu_226 <= select_ln325_1_fu_901_p3;
                end if;
            end if; 
        end if;
    end process;

    mux_case_411816011_fu_254_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_3) 
    and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                mux_case_411816011_fu_254 <= select_ln325_1_fu_901_p3;
            elsif ((not((select_ln325_6_reg_1242_pp0_iter5_reg = ap_const_lv3_3)) and not((select_ln325_6_reg_1242_pp0_iter5_reg = ap_const_lv3_2)) and not((select_ln325_6_reg_1242_pp0_iter5_reg = ap_const_lv3_1)) and not((select_ln325_6_reg_1242_pp0_iter5_reg = ap_const_lv3_0)) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter5_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                mux_case_411816011_fu_254 <= grp_fu_2080_p_dout0;
            end if; 
        end if;
    end process;

    mx_33_fu_238_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_0)) and not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_1)) and not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_2)) and not((select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_3)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 
    = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter4_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter4_reg = ap_const_lv3_3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                mx_33_fu_238 <= select_ln325_5_fu_929_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln327_1_reg_1265_pp0_iter5_reg = ap_const_lv1_1) and (select_ln325_6_reg_1242_pp0_iter5_reg = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                mx_33_fu_238 <= grp_fu_2080_p_dout0;
            end if; 
        end if;
    end process;

    o_2_fu_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln325_fu_567_p2 = ap_const_lv1_0))) then 
                    o_2_fu_206 <= select_ln325_6_fu_605_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    o_2_fu_206 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                acc_3_reg_1309 <= grp_fu_2084_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                acc_3_reg_1309_pp0_iter4_reg <= acc_3_reg_1309;
                first_iter_6_reg_1246 <= first_iter_6_fu_613_p2;
                first_iter_6_reg_1246_pp0_iter1_reg <= first_iter_6_reg_1246;
                first_iter_6_reg_1246_pp0_iter2_reg <= first_iter_6_reg_1246_pp0_iter1_reg;
                first_iter_6_reg_1246_pp0_iter3_reg <= first_iter_6_reg_1246_pp0_iter2_reg;
                first_iter_6_reg_1246_pp0_iter4_reg <= first_iter_6_reg_1246_pp0_iter3_reg;
                icmp_ln325_reg_1229 <= icmp_ln325_fu_567_p2;
                icmp_ln325_reg_1229_pp0_iter1_reg <= icmp_ln325_reg_1229;
                icmp_ln325_reg_1229_pp0_iter2_reg <= icmp_ln325_reg_1229_pp0_iter1_reg;
                icmp_ln325_reg_1229_pp0_iter3_reg <= icmp_ln325_reg_1229_pp0_iter2_reg;
                icmp_ln325_reg_1229_pp0_iter4_reg <= icmp_ln325_reg_1229_pp0_iter3_reg;
                icmp_ln327_1_reg_1265 <= icmp_ln327_1_fu_803_p2;
                icmp_ln327_1_reg_1265_pp0_iter1_reg <= icmp_ln327_1_reg_1265;
                icmp_ln327_1_reg_1265_pp0_iter2_reg <= icmp_ln327_1_reg_1265_pp0_iter1_reg;
                icmp_ln327_1_reg_1265_pp0_iter3_reg <= icmp_ln327_1_reg_1265_pp0_iter2_reg;
                icmp_ln327_1_reg_1265_pp0_iter4_reg <= icmp_ln327_1_reg_1265_pp0_iter3_reg;
                icmp_ln327_1_reg_1265_pp0_iter5_reg <= icmp_ln327_1_reg_1265_pp0_iter4_reg;
                icmp_ln327_reg_1233 <= icmp_ln327_fu_591_p2;
                icmp_ln327_reg_1233_pp0_iter1_reg <= icmp_ln327_reg_1233;
                icmp_ln327_reg_1233_pp0_iter2_reg <= icmp_ln327_reg_1233_pp0_iter1_reg;
                icmp_ln327_reg_1233_pp0_iter3_reg <= icmp_ln327_reg_1233_pp0_iter2_reg;
                icmp_ln327_reg_1233_pp0_iter4_reg <= icmp_ln327_reg_1233_pp0_iter3_reg;
                select_ln325_6_reg_1242 <= select_ln325_6_fu_605_p3;
                select_ln325_6_reg_1242_pp0_iter1_reg <= select_ln325_6_reg_1242;
                select_ln325_6_reg_1242_pp0_iter2_reg <= select_ln325_6_reg_1242_pp0_iter1_reg;
                select_ln325_6_reg_1242_pp0_iter3_reg <= select_ln325_6_reg_1242_pp0_iter2_reg;
                select_ln325_6_reg_1242_pp0_iter4_reg <= select_ln325_6_reg_1242_pp0_iter3_reg;
                select_ln325_6_reg_1242_pp0_iter5_reg <= select_ln325_6_reg_1242_pp0_iter4_reg;
                tmp_5_reg_1260 <= tmp_5_fu_661_p67;
                tmp_5_reg_1260_pp0_iter1_reg <= tmp_5_reg_1260;
                tmp_5_reg_1260_pp0_iter2_reg <= tmp_5_reg_1260_pp0_iter1_reg;
                tmp_5_reg_1260_pp0_iter3_reg <= tmp_5_reg_1260_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln38_1_reg_1274 <= add_ln38_1_fu_840_p2;
                output_b_load_reg_1269 <= output_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                add_ln38_reg_1279 <= add_ln38_fu_849_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                conv1_i26_i_reg_1294 <= grp_fu_2102_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                conv1_i_i_reg_1299 <= grp_fu_2102_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                mul_i27_i_reg_1304 <= grp_fu_2084_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                mul_i_reg_1314 <= grp_fu_2084_p_dout0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to5, ap_block_pp0_stage1_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to5 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln325_1_fu_573_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten59_load) + unsigned(ap_const_lv8_1));
    add_ln325_fu_585_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_o_2_load) + unsigned(ap_const_lv3_1));
    add_ln327_fu_797_p2 <= std_logic_vector(unsigned(select_ln325_fu_597_p3) + unsigned(ap_const_lv6_1));
    add_ln329_1_fu_640_p2 <= std_logic_vector(unsigned(tmp_fu_632_p3) + unsigned(zext_ln329_fu_628_p1));
    add_ln329_fu_646_p2 <= std_logic_vector(unsigned(add_ln329_1_fu_640_p2) + unsigned(zext_ln326_fu_624_p1));
    add_ln38_1_fu_840_p2 <= std_logic_vector(signed(sext_ln38_4_fu_836_p1) + signed(ap_const_lv9_1ED));
    add_ln38_fu_849_p2 <= std_logic_vector(signed(sext_ln38_fu_846_p1) + signed(ap_const_lv9_8));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln325_reg_1229)
    begin
        if (((icmp_ln325_reg_1229 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_loop_exit_ready_pp0_iter4_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to5_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to5 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to5 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_acc_load_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage2, first_iter_6_reg_1246_pp0_iter4_reg, acc_3_reg_1309_pp0_iter4_reg, acc_fu_234, ap_block_pp0_stage2, grp_fu_2080_p_dout0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
            if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (first_iter_6_reg_1246_pp0_iter4_reg = ap_const_lv1_1))) then 
                ap_sig_allocacmp_acc_load <= acc_3_reg_1309_pp0_iter4_reg;
            elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                ap_sig_allocacmp_acc_load <= grp_fu_2080_p_dout0;
            else 
                ap_sig_allocacmp_acc_load <= acc_fu_234;
            end if;
        else 
            ap_sig_allocacmp_acc_load <= acc_fu_234;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_202, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_202;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten59_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten59_fu_230)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten59_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten59_load <= indvar_flatten59_fu_230;
        end if; 
    end process;


    ap_sig_allocacmp_o_2_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, o_2_fu_206)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_o_2_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_o_2_load <= o_2_fu_206;
        end if; 
    end process;

    first_iter_6_fu_613_p2 <= "1" when (select_ln325_fu_597_p3 = ap_const_lv6_0) else "0";
    grp_fu_2080_p_ce <= ap_const_logic_1;
    grp_fu_2080_p_din0 <= ap_sig_allocacmp_acc_load;
    grp_fu_2080_p_din1 <= mul_i_reg_1314;
    grp_fu_2080_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_2084_p_ce <= ap_const_logic_1;
    grp_fu_2084_p_din0 <= grp_fu_515_p0;
    grp_fu_2084_p_din1 <= grp_fu_515_p1;
    grp_fu_2102_p_ce <= ap_const_logic_1;
    grp_fu_2102_p_din0 <= grp_fu_521_p0;

    grp_fu_515_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage2, tmp_5_reg_1260_pp0_iter3_reg, ap_CS_fsm_pp0_stage1, conv1_i26_i_reg_1294, conv1_i_i_reg_1299, ap_block_pp0_stage0, ap_block_pp0_stage2, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_515_p0 <= tmp_5_reg_1260_pp0_iter3_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_515_p0 <= conv1_i_i_reg_1299;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_515_p0 <= conv1_i26_i_reg_1294;
        else 
            grp_fu_515_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_515_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, mul_i27_i_reg_1304, ap_block_pp0_stage0, ap_block_pp0_stage2, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_515_p1 <= mul_i27_i_reg_1304;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_515_p1 <= ap_const_lv32_3ACB62BF;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_515_p1 <= ap_const_lv32_3B9B1DD3;
        else 
            grp_fu_515_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_521_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, sext_ln38_5_fu_855_p1, sext_ln38_3_fu_859_p1, ap_block_pp0_stage0, ap_block_pp0_stage2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_521_p0 <= sext_ln38_3_fu_859_p1;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_521_p0 <= sext_ln38_5_fu_855_p1;
        else 
            grp_fu_521_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln325_fu_567_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten59_load = ap_const_lv8_A0) else "0";
    icmp_ln327_1_fu_803_p2 <= "1" when (add_ln327_fu_797_p2 = ap_const_lv6_20) else "0";
    icmp_ln327_fu_591_p2 <= "1" when (ap_sig_allocacmp_i_load = ap_const_lv6_20) else "0";
    mux_case_11121455_out <= mux_case_11121455_fu_242;

    mux_case_11121455_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln325_reg_1229_pp0_iter4_reg, ap_block_pp0_stage2_11001, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln325_reg_1229_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            mux_case_11121455_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_11121455_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_21141507_out <= mux_case_21141507_fu_246;

    mux_case_21141507_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln325_reg_1229_pp0_iter4_reg, ap_block_pp0_stage2_11001, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln325_reg_1229_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            mux_case_21141507_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_21141507_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_31161559_out <= mux_case_31161559_fu_250;

    mux_case_31161559_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln325_reg_1229_pp0_iter4_reg, ap_block_pp0_stage2_11001, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln325_reg_1229_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            mux_case_31161559_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_31161559_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_411816011_out <= mux_case_411816011_fu_254;

    mux_case_411816011_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln325_reg_1229_pp0_iter4_reg, ap_block_pp0_stage2_11001, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln325_reg_1229_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            mux_case_411816011_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_411816011_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mx_33_out <= mx_33_fu_238;

    mx_33_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln325_reg_1229_pp0_iter4_reg, ap_block_pp0_stage2_11001, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (icmp_ln325_reg_1229_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            mx_33_out_ap_vld <= ap_const_logic_1;
        else 
            mx_33_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_b_address0 <= zext_ln325_fu_619_p1(3 - 1 downto 0);

    output_b_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            output_b_ce0_local <= ap_const_logic_1;
        else 
            output_b_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_w_address0 <= zext_ln329_1_fu_652_p1(8 - 1 downto 0);

    output_w_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            output_w_ce0_local <= ap_const_logic_1;
        else 
            output_w_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln325_1_fu_901_p3 <= 
        mux_case_411816011_fu_254 when (icmp_ln327_reg_1233_pp0_iter4_reg(0) = '1') else 
        mux_case_4118159_fu_226;
    select_ln325_2_fu_908_p3 <= 
        mux_case_31161559_fu_250 when (icmp_ln327_reg_1233_pp0_iter4_reg(0) = '1') else 
        mux_case_3116154_fu_222;
    select_ln325_3_fu_915_p3 <= 
        mux_case_21141507_fu_246 when (icmp_ln327_reg_1233_pp0_iter4_reg(0) = '1') else 
        mux_case_2114149_fu_218;
    select_ln325_4_fu_922_p3 <= 
        mux_case_11121455_fu_242 when (icmp_ln327_reg_1233_pp0_iter4_reg(0) = '1') else 
        mux_case_1112144_fu_214;
    select_ln325_5_fu_929_p3 <= 
        mx_33_fu_238 when (icmp_ln327_reg_1233_pp0_iter4_reg(0) = '1') else 
        empty_fu_210;
    select_ln325_6_fu_605_p3 <= 
        add_ln325_fu_585_p2 when (icmp_ln327_fu_591_p2(0) = '1') else 
        ap_sig_allocacmp_o_2_load;
    select_ln325_fu_597_p3 <= 
        ap_const_lv6_0 when (icmp_ln327_fu_591_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
        sext_ln38_3_fu_859_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln38_reg_1279),32));

        sext_ln38_4_fu_836_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(output_w_q0),9));

        sext_ln38_5_fu_855_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln38_1_reg_1274),32));

        sext_ln38_fu_846_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(output_b_load_reg_1269),9));

    tmp_5_fu_661_p65 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_5_fu_661_p66 <= select_ln325_fu_597_p3(5 - 1 downto 0);
    tmp_fu_632_p3 <= (select_ln325_fu_597_p3 & ap_const_lv2_0);
    zext_ln325_fu_619_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln325_6_fu_605_p3),64));
    zext_ln326_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln325_6_fu_605_p3),8));
    zext_ln329_1_fu_652_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln329_fu_646_p2),64));
    zext_ln329_fu_628_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln325_fu_597_p3),8));
end behav;
