// Auto-generated by Phase 3 quantization script
// Layer: s1_conv_seq  Type: Conv1D
// Weight shape: (7, 1, 8)  (kernel, in_channels, out_filters)

#pragma once
#include <cstdint>

#define S1_CONV_SEQ_KERNEL  7
#define S1_CONV_SEQ_IN_CH   1
#define S1_CONV_SEQ_OUT_CH  8
#define S1_CONV_SEQ_W_SCALE 0.00928567f
#define S1_CONV_SEQ_W_ZP    55

static const int8_t s1_conv_seq_w[7][1][8] = 
{{{92, 9, 111, 63, 50, 38, -21, 37}}, {{-25, -13, 112, 87, 83, 32, 67, 76}}, {{50, 26, 81, -77, 95, 127, 100, 64}}, {{108, 37, 79, 33, 61, 67, 56, 101}}, {{89, 102, -13, 112, 97, -13, 23, -5}}, {{6, 118, 31, 47, -3, 40, 81, 9}}, {{12, 78, -5, 69, -62, 99, 112, -128}}};