// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_219_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        acc_19,
        zext_ln221,
        zext_ln222,
        zext_ln214,
        acc_24_out,
        acc_24_out_ap_vld,
        s2_pool_address0,
        s2_pool_ce0,
        s2_pool_q0,
        grp_fu_2080_p_din0,
        grp_fu_2080_p_din1,
        grp_fu_2080_p_opcode,
        grp_fu_2080_p_dout0,
        grp_fu_2080_p_ce,
        grp_fu_2084_p_din0,
        grp_fu_2084_p_din1,
        grp_fu_2084_p_dout0,
        grp_fu_2084_p_ce,
        grp_fu_2102_p_din0,
        grp_fu_2102_p_dout0,
        grp_fu_2102_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] acc_19;
input  [9:0] zext_ln221;
input  [6:0] zext_ln222;
input  [4:0] zext_ln214;
output  [31:0] acc_24_out;
output   acc_24_out_ap_vld;
output  [9:0] s2_pool_address0;
output   s2_pool_ce0;
input  [31:0] s2_pool_q0;
output  [31:0] grp_fu_2080_p_din0;
output  [31:0] grp_fu_2080_p_din1;
output  [0:0] grp_fu_2080_p_opcode;
input  [31:0] grp_fu_2080_p_dout0;
output   grp_fu_2080_p_ce;
output  [31:0] grp_fu_2084_p_din0;
output  [31:0] grp_fu_2084_p_din1;
input  [31:0] grp_fu_2084_p_dout0;
output   grp_fu_2084_p_ce;
output  [31:0] grp_fu_2102_p_din0;
input  [31:0] grp_fu_2102_p_dout0;
output   grp_fu_2102_p_ce;

reg ap_idle;
reg acc_24_out_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln219_reg_249;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [11:0] s3_conv_w_address0;
wire   [7:0] s3_conv_w_q0;
wire    ap_block_pp0_stage0_11001;
reg   [4:0] ic_4_reg_244;
reg   [4:0] ic_4_reg_244_pp0_iter1_reg;
wire   [0:0] icmp_ln219_fu_144_p2;
reg   [0:0] icmp_ln219_reg_249_pp0_iter1_reg;
reg   [0:0] icmp_ln219_reg_249_pp0_iter2_reg;
reg   [0:0] icmp_ln219_reg_249_pp0_iter3_reg;
reg   [0:0] icmp_ln219_reg_249_pp0_iter4_reg;
wire   [8:0] add_ln38_fu_188_p2;
reg   [8:0] add_ln38_reg_258;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire  signed [31:0] sext_ln38_fu_194_p1;
wire    ap_block_pp0_stage2_11001;
reg   [31:0] conv1_i_i5_reg_268;
reg   [31:0] s2_pool_load_reg_278;
reg   [31:0] mul_i_i5_reg_283;
reg   [31:0] mul_i6_reg_288;
wire    ap_block_pp0_stage1_subdone;
wire   [63:0] zext_ln222_1_fu_174_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln221_3_fu_206_p1;
reg   [31:0] acc_fu_54;
reg   [31:0] ap_sig_allocacmp_acc_load_6;
wire    ap_block_pp0_stage1;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter4_stage1;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [4:0] ic_fu_58;
wire   [4:0] add_ln219_fu_150_p2;
reg   [4:0] ap_sig_allocacmp_ic_4;
wire    ap_block_pp0_stage1_01001;
reg    s3_conv_w_ce0_local;
reg    s2_pool_ce0_local;
reg   [31:0] grp_fu_123_p0;
reg   [31:0] grp_fu_123_p1;
wire    ap_block_pp0_stage2;
wire   [6:0] zext_ln221_1_fu_156_p1;
wire   [6:0] add_ln222_fu_160_p2;
wire   [11:0] add_ln222_1_fu_166_p3;
wire  signed [8:0] sext_ln38_6_fu_184_p1;
wire   [9:0] zext_ln221_2_fu_198_p1;
wire   [9:0] add_ln221_fu_201_p2;
wire    ap_block_pp0_stage1_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to5;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 acc_fu_54 = 32'd0;
#0 ic_fu_58 = 5'd0;
#0 ap_done_reg = 1'b0;
end

ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_219_4_s3_conv_w_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 2560 ),
    .AddressWidth( 12 ))
s3_conv_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(s3_conv_w_address0),
    .ce0(s3_conv_w_ce0_local),
    .q0(s3_conv_w_q0)
);

ecg_cnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        acc_fu_54 <= acc_19;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        acc_fu_54 <= grp_fu_2080_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter4_stage1) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter4_stage1) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter4_stage1) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter4_stage1) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln219_fu_144_p2 == 1'd0))) begin
            ic_fu_58 <= add_ln219_fu_150_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ic_fu_58 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln38_reg_258 <= add_ln38_fu_188_p2;
        s2_pool_load_reg_278 <= s2_pool_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        conv1_i_i5_reg_268 <= grp_fu_2102_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ic_4_reg_244 <= ap_sig_allocacmp_ic_4;
        ic_4_reg_244_pp0_iter1_reg <= ic_4_reg_244;
        icmp_ln219_reg_249 <= icmp_ln219_fu_144_p2;
        icmp_ln219_reg_249_pp0_iter1_reg <= icmp_ln219_reg_249;
        icmp_ln219_reg_249_pp0_iter2_reg <= icmp_ln219_reg_249_pp0_iter1_reg;
        icmp_ln219_reg_249_pp0_iter3_reg <= icmp_ln219_reg_249_pp0_iter2_reg;
        icmp_ln219_reg_249_pp0_iter4_reg <= icmp_ln219_reg_249_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_i6_reg_288 <= grp_fu_2084_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul_i_i5_reg_283 <= grp_fu_2084_p_dout0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln219_reg_249_pp0_iter4_reg == 1'd1))) begin
        acc_24_out_ap_vld = 1'b1;
    end else begin
        acc_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln219_reg_249 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln219_reg_249_pp0_iter4_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_acc_load_6 = grp_fu_2080_p_dout0;
    end else begin
        ap_sig_allocacmp_acc_load_6 = acc_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ic_4 = 5'd0;
    end else begin
        ap_sig_allocacmp_ic_4 = ic_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_123_p0 = s2_pool_load_reg_278;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_123_p0 = conv1_i_i5_reg_268;
    end else begin
        grp_fu_123_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_123_p1 = mul_i_i5_reg_283;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_123_p1 = 32'd1015839378;
    end else begin
        grp_fu_123_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s2_pool_ce0_local = 1'b1;
    end else begin
        s2_pool_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s3_conv_w_ce0_local = 1'b1;
    end else begin
        s3_conv_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter4_stage1) & (ap_idle_pp0_0to3 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_24_out = acc_fu_54;

assign add_ln219_fu_150_p2 = (ap_sig_allocacmp_ic_4 + 5'd1);

assign add_ln221_fu_201_p2 = (zext_ln221 + zext_ln221_2_fu_198_p1);

assign add_ln222_1_fu_166_p3 = {{add_ln222_fu_160_p2}, {zext_ln214}};

assign add_ln222_fu_160_p2 = (zext_ln222 + zext_ln221_1_fu_156_p1);

assign add_ln38_fu_188_p2 = ($signed(sext_ln38_6_fu_184_p1) + $signed(9'd486));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_ready = ap_ready_sig;

assign grp_fu_2080_p_ce = 1'b1;

assign grp_fu_2080_p_din0 = ap_sig_allocacmp_acc_load_6;

assign grp_fu_2080_p_din1 = mul_i6_reg_288;

assign grp_fu_2080_p_opcode = 2'd0;

assign grp_fu_2084_p_ce = 1'b1;

assign grp_fu_2084_p_din0 = grp_fu_123_p0;

assign grp_fu_2084_p_din1 = grp_fu_123_p1;

assign grp_fu_2102_p_ce = 1'b1;

assign grp_fu_2102_p_din0 = sext_ln38_fu_194_p1;

assign icmp_ln219_fu_144_p2 = ((ap_sig_allocacmp_ic_4 == 5'd16) ? 1'b1 : 1'b0);

assign s2_pool_address0 = zext_ln221_3_fu_206_p1;

assign s2_pool_ce0 = s2_pool_ce0_local;

assign s3_conv_w_address0 = zext_ln222_1_fu_174_p1;

assign sext_ln38_6_fu_184_p1 = $signed(s3_conv_w_q0);

assign sext_ln38_fu_194_p1 = $signed(add_ln38_reg_258);

assign zext_ln221_1_fu_156_p1 = ap_sig_allocacmp_ic_4;

assign zext_ln221_2_fu_198_p1 = ic_4_reg_244_pp0_iter1_reg;

assign zext_ln221_3_fu_206_p1 = add_ln221_fu_201_p2;

assign zext_ln222_1_fu_174_p1 = add_ln222_1_fu_166_p3;

endmodule //ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_219_4
