# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.srcs/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/ecg_system_ecg_cnn_top_0_0.xci
# IP: The module: 'ecg_system_ecg_cnn_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_fadd_32ns_32ns_32_4_full_dsp_1_ip/ecg_cnn_top_fadd_32ns_32ns_32_4_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_fadd_32ns_32ns_32_4_full_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_fadd_32ns_32ns_32_4_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_faddfsub_32ns_32ns_32_4_full_dsp_1_ip/ecg_cnn_top_faddfsub_32ns_32ns_32_4_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_faddfsub_32ns_32ns_32_4_full_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_faddfsub_32ns_32ns_32_4_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip/ecg_cnn_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_fdiv_32ns_32ns_32_12_no_dsp_1_ip/ecg_cnn_top_fdiv_32ns_32ns_32_12_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_fdiv_32ns_32ns_32_12_no_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_fdiv_32ns_32ns_32_12_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_fexp_32ns_32ns_32_8_full_dsp_1_ip/ecg_cnn_top_fexp_32ns_32ns_32_8_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_fexp_32ns_32ns_32_8_full_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_fexp_32ns_32ns_32_8_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_fmul_32ns_32ns_32_3_max_dsp_1_ip/ecg_cnn_top_fmul_32ns_32ns_32_3_max_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_fmul_32ns_32ns_32_3_max_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_fmul_32ns_32ns_32_3_max_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_sitofp_32s_32_4_no_dsp_1_ip/ecg_cnn_top_sitofp_32s_32_4_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_sitofp_32s_32_4_no_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_sitofp_32s_32_4_no_dsp_1_ip} -quiet] -quiet

# XDC: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/constraints/ecg_cnn_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ecg_system_ecg_cnn_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.srcs/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/ecg_system_ecg_cnn_top_0_0.xci
# IP: The module: 'ecg_system_ecg_cnn_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_fadd_32ns_32ns_32_4_full_dsp_1_ip/ecg_cnn_top_fadd_32ns_32ns_32_4_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_fadd_32ns_32ns_32_4_full_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_fadd_32ns_32ns_32_4_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_faddfsub_32ns_32ns_32_4_full_dsp_1_ip/ecg_cnn_top_faddfsub_32ns_32ns_32_4_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_faddfsub_32ns_32ns_32_4_full_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_faddfsub_32ns_32ns_32_4_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip/ecg_cnn_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_fcmp_32ns_32ns_1_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_fdiv_32ns_32ns_32_12_no_dsp_1_ip/ecg_cnn_top_fdiv_32ns_32ns_32_12_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_fdiv_32ns_32ns_32_12_no_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_fdiv_32ns_32ns_32_12_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_fexp_32ns_32ns_32_8_full_dsp_1_ip/ecg_cnn_top_fexp_32ns_32ns_32_8_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_fexp_32ns_32ns_32_8_full_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_fexp_32ns_32ns_32_8_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_fmul_32ns_32ns_32_3_max_dsp_1_ip/ecg_cnn_top_fmul_32ns_32ns_32_3_max_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_fmul_32ns_32ns_32_3_max_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_fmul_32ns_32ns_32_3_max_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/hdl/ip/ecg_cnn_top_sitofp_32s_32_4_no_dsp_1_ip/ecg_cnn_top_sitofp_32s_32_4_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecg_cnn_top_sitofp_32s_32_4_no_dsp_1_ip || ORIG_REF_NAME==ecg_cnn_top_sitofp_32s_32_4_no_dsp_1_ip} -quiet] -quiet

# XDC: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_ecg_cnn_top_0_0/constraints/ecg_cnn_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ecg_system_ecg_cnn_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
