// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_341_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_OUTPUT_BUS_0_AWVALID,
        m_axi_OUTPUT_BUS_0_AWREADY,
        m_axi_OUTPUT_BUS_0_AWADDR,
        m_axi_OUTPUT_BUS_0_AWID,
        m_axi_OUTPUT_BUS_0_AWLEN,
        m_axi_OUTPUT_BUS_0_AWSIZE,
        m_axi_OUTPUT_BUS_0_AWBURST,
        m_axi_OUTPUT_BUS_0_AWLOCK,
        m_axi_OUTPUT_BUS_0_AWCACHE,
        m_axi_OUTPUT_BUS_0_AWPROT,
        m_axi_OUTPUT_BUS_0_AWQOS,
        m_axi_OUTPUT_BUS_0_AWREGION,
        m_axi_OUTPUT_BUS_0_AWUSER,
        m_axi_OUTPUT_BUS_0_WVALID,
        m_axi_OUTPUT_BUS_0_WREADY,
        m_axi_OUTPUT_BUS_0_WDATA,
        m_axi_OUTPUT_BUS_0_WSTRB,
        m_axi_OUTPUT_BUS_0_WLAST,
        m_axi_OUTPUT_BUS_0_WID,
        m_axi_OUTPUT_BUS_0_WUSER,
        m_axi_OUTPUT_BUS_0_ARVALID,
        m_axi_OUTPUT_BUS_0_ARREADY,
        m_axi_OUTPUT_BUS_0_ARADDR,
        m_axi_OUTPUT_BUS_0_ARID,
        m_axi_OUTPUT_BUS_0_ARLEN,
        m_axi_OUTPUT_BUS_0_ARSIZE,
        m_axi_OUTPUT_BUS_0_ARBURST,
        m_axi_OUTPUT_BUS_0_ARLOCK,
        m_axi_OUTPUT_BUS_0_ARCACHE,
        m_axi_OUTPUT_BUS_0_ARPROT,
        m_axi_OUTPUT_BUS_0_ARQOS,
        m_axi_OUTPUT_BUS_0_ARREGION,
        m_axi_OUTPUT_BUS_0_ARUSER,
        m_axi_OUTPUT_BUS_0_RVALID,
        m_axi_OUTPUT_BUS_0_RREADY,
        m_axi_OUTPUT_BUS_0_RDATA,
        m_axi_OUTPUT_BUS_0_RLAST,
        m_axi_OUTPUT_BUS_0_RID,
        m_axi_OUTPUT_BUS_0_RFIFONUM,
        m_axi_OUTPUT_BUS_0_RUSER,
        m_axi_OUTPUT_BUS_0_RRESP,
        m_axi_OUTPUT_BUS_0_BVALID,
        m_axi_OUTPUT_BUS_0_BREADY,
        m_axi_OUTPUT_BUS_0_BRESP,
        m_axi_OUTPUT_BUS_0_BID,
        m_axi_OUTPUT_BUS_0_BUSER,
        sext_ln341,
        mux_case_0135169_reload,
        mux_case_1137172_reload,
        mux_case_2139175_reload,
        mux_case_3141178_reload,
        mux_case_4143181_reload,
        se_reload,
        grp_fu_2097_p_din0,
        grp_fu_2097_p_din1,
        grp_fu_2097_p_dout0,
        grp_fu_2097_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_OUTPUT_BUS_0_AWVALID;
input   m_axi_OUTPUT_BUS_0_AWREADY;
output  [63:0] m_axi_OUTPUT_BUS_0_AWADDR;
output  [0:0] m_axi_OUTPUT_BUS_0_AWID;
output  [31:0] m_axi_OUTPUT_BUS_0_AWLEN;
output  [2:0] m_axi_OUTPUT_BUS_0_AWSIZE;
output  [1:0] m_axi_OUTPUT_BUS_0_AWBURST;
output  [1:0] m_axi_OUTPUT_BUS_0_AWLOCK;
output  [3:0] m_axi_OUTPUT_BUS_0_AWCACHE;
output  [2:0] m_axi_OUTPUT_BUS_0_AWPROT;
output  [3:0] m_axi_OUTPUT_BUS_0_AWQOS;
output  [3:0] m_axi_OUTPUT_BUS_0_AWREGION;
output  [0:0] m_axi_OUTPUT_BUS_0_AWUSER;
output   m_axi_OUTPUT_BUS_0_WVALID;
input   m_axi_OUTPUT_BUS_0_WREADY;
output  [31:0] m_axi_OUTPUT_BUS_0_WDATA;
output  [3:0] m_axi_OUTPUT_BUS_0_WSTRB;
output   m_axi_OUTPUT_BUS_0_WLAST;
output  [0:0] m_axi_OUTPUT_BUS_0_WID;
output  [0:0] m_axi_OUTPUT_BUS_0_WUSER;
output   m_axi_OUTPUT_BUS_0_ARVALID;
input   m_axi_OUTPUT_BUS_0_ARREADY;
output  [63:0] m_axi_OUTPUT_BUS_0_ARADDR;
output  [0:0] m_axi_OUTPUT_BUS_0_ARID;
output  [31:0] m_axi_OUTPUT_BUS_0_ARLEN;
output  [2:0] m_axi_OUTPUT_BUS_0_ARSIZE;
output  [1:0] m_axi_OUTPUT_BUS_0_ARBURST;
output  [1:0] m_axi_OUTPUT_BUS_0_ARLOCK;
output  [3:0] m_axi_OUTPUT_BUS_0_ARCACHE;
output  [2:0] m_axi_OUTPUT_BUS_0_ARPROT;
output  [3:0] m_axi_OUTPUT_BUS_0_ARQOS;
output  [3:0] m_axi_OUTPUT_BUS_0_ARREGION;
output  [0:0] m_axi_OUTPUT_BUS_0_ARUSER;
input   m_axi_OUTPUT_BUS_0_RVALID;
output   m_axi_OUTPUT_BUS_0_RREADY;
input  [31:0] m_axi_OUTPUT_BUS_0_RDATA;
input   m_axi_OUTPUT_BUS_0_RLAST;
input  [0:0] m_axi_OUTPUT_BUS_0_RID;
input  [8:0] m_axi_OUTPUT_BUS_0_RFIFONUM;
input  [0:0] m_axi_OUTPUT_BUS_0_RUSER;
input  [1:0] m_axi_OUTPUT_BUS_0_RRESP;
input   m_axi_OUTPUT_BUS_0_BVALID;
output   m_axi_OUTPUT_BUS_0_BREADY;
input  [1:0] m_axi_OUTPUT_BUS_0_BRESP;
input  [0:0] m_axi_OUTPUT_BUS_0_BID;
input  [0:0] m_axi_OUTPUT_BUS_0_BUSER;
input  [61:0] sext_ln341;
input  [31:0] mux_case_0135169_reload;
input  [31:0] mux_case_1137172_reload;
input  [31:0] mux_case_2139175_reload;
input  [31:0] mux_case_3141178_reload;
input  [31:0] mux_case_4143181_reload;
input  [31:0] se_reload;
output  [31:0] grp_fu_2097_p_din0;
output  [31:0] grp_fu_2097_p_din1;
input  [31:0] grp_fu_2097_p_dout0;
output   grp_fu_2097_p_ce;

reg ap_idle;
reg m_axi_OUTPUT_BUS_0_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln341_fu_142_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    OUTPUT_BUS_blk_n_W;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [2:0] o_1_reg_234;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] tmp_8_fu_159_p13;
reg   [31:0] div_i1_reg_248;
wire    ap_block_pp0_stage0_01001_grp1;
reg   [2:0] o_fu_72;
wire   [2:0] add_ln341_fu_148_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_o_1;
wire    ap_block_pp0_stage0;
wire   [31:0] tmp_8_fu_159_p11;
reg    grp_fu_126_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_8_fu_159_p1;
wire   [2:0] tmp_8_fu_159_p3;
wire   [2:0] tmp_8_fu_159_p5;
wire   [2:0] tmp_8_fu_159_p7;
wire  signed [2:0] tmp_8_fu_159_p9;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 o_fu_72 = 3'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) ecg_cnn_top_sparsemux_11_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_11_3_32_1_1_U325(
    .din0(mux_case_0135169_reload),
    .din1(mux_case_1137172_reload),
    .din2(mux_case_2139175_reload),
    .din3(mux_case_3141178_reload),
    .din4(mux_case_4143181_reload),
    .def(tmp_8_fu_159_p11),
    .sel(o_1_reg_234),
    .dout(tmp_8_fu_159_p13)
);

ecg_cnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter12_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln341_fu_142_p2 == 1'd0))) begin
            o_fu_72 <= add_ln341_fu_148_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            o_fu_72 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        o_1_reg_234 <= ap_sig_allocacmp_o_1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        div_i1_reg_248 <= grp_fu_2097_p_dout0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        OUTPUT_BUS_blk_n_W = m_axi_OUTPUT_BUS_0_WREADY;
    end else begin
        OUTPUT_BUS_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln341_fu_142_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter12_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_o_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_o_1 = o_fu_72;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        grp_fu_126_ce = 1'b1;
    end else begin
        grp_fu_126_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_OUTPUT_BUS_0_WVALID = 1'b1;
    end else begin
        m_axi_OUTPUT_BUS_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln341_fu_148_p2 = (ap_sig_allocacmp_o_1 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_OUTPUT_BUS_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_OUTPUT_BUS_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_OUTPUT_BUS_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_2097_p_ce = grp_fu_126_ce;

assign grp_fu_2097_p_din0 = tmp_8_fu_159_p13;

assign grp_fu_2097_p_din1 = se_reload;

assign icmp_ln341_fu_142_p2 = ((ap_sig_allocacmp_o_1 == 3'd5) ? 1'b1 : 1'b0);

assign m_axi_OUTPUT_BUS_0_ARADDR = 64'd0;

assign m_axi_OUTPUT_BUS_0_ARBURST = 2'd0;

assign m_axi_OUTPUT_BUS_0_ARCACHE = 4'd0;

assign m_axi_OUTPUT_BUS_0_ARID = 1'd0;

assign m_axi_OUTPUT_BUS_0_ARLEN = 32'd0;

assign m_axi_OUTPUT_BUS_0_ARLOCK = 2'd0;

assign m_axi_OUTPUT_BUS_0_ARPROT = 3'd0;

assign m_axi_OUTPUT_BUS_0_ARQOS = 4'd0;

assign m_axi_OUTPUT_BUS_0_ARREGION = 4'd0;

assign m_axi_OUTPUT_BUS_0_ARSIZE = 3'd0;

assign m_axi_OUTPUT_BUS_0_ARUSER = 1'd0;

assign m_axi_OUTPUT_BUS_0_ARVALID = 1'b0;

assign m_axi_OUTPUT_BUS_0_AWADDR = 64'd0;

assign m_axi_OUTPUT_BUS_0_AWBURST = 2'd0;

assign m_axi_OUTPUT_BUS_0_AWCACHE = 4'd0;

assign m_axi_OUTPUT_BUS_0_AWID = 1'd0;

assign m_axi_OUTPUT_BUS_0_AWLEN = 32'd0;

assign m_axi_OUTPUT_BUS_0_AWLOCK = 2'd0;

assign m_axi_OUTPUT_BUS_0_AWPROT = 3'd0;

assign m_axi_OUTPUT_BUS_0_AWQOS = 4'd0;

assign m_axi_OUTPUT_BUS_0_AWREGION = 4'd0;

assign m_axi_OUTPUT_BUS_0_AWSIZE = 3'd0;

assign m_axi_OUTPUT_BUS_0_AWUSER = 1'd0;

assign m_axi_OUTPUT_BUS_0_AWVALID = 1'b0;

assign m_axi_OUTPUT_BUS_0_BREADY = 1'b0;

assign m_axi_OUTPUT_BUS_0_RREADY = 1'b0;

assign m_axi_OUTPUT_BUS_0_WDATA = div_i1_reg_248;

assign m_axi_OUTPUT_BUS_0_WID = 1'd0;

assign m_axi_OUTPUT_BUS_0_WLAST = 1'b0;

assign m_axi_OUTPUT_BUS_0_WSTRB = 4'd15;

assign m_axi_OUTPUT_BUS_0_WUSER = 1'd0;

assign tmp_8_fu_159_p11 = 'bx;

endmodule //ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_341_5
