// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_231_5_VITIS_LOOP_232_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tmp_1_address0,
        tmp_1_ce0,
        tmp_1_q0,
        tmp_1_address1,
        tmp_1_ce1,
        tmp_1_q1,
        tmp_1_address2,
        tmp_1_ce2,
        tmp_1_q2,
        s3_out_address0,
        s3_out_ce0,
        s3_out_we0,
        s3_out_d0,
        grp_fu_2105_p_din0,
        grp_fu_2105_p_din1,
        grp_fu_2105_p_opcode,
        grp_fu_2105_p_dout0,
        grp_fu_2105_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] tmp_1_address0;
output   tmp_1_ce0;
input  [31:0] tmp_1_q0;
output  [10:0] tmp_1_address1;
output   tmp_1_ce1;
input  [31:0] tmp_1_q1;
output  [10:0] tmp_1_address2;
output   tmp_1_ce2;
input  [31:0] tmp_1_q2;
output  [9:0] s3_out_address0;
output   s3_out_ce0;
output   s3_out_we0;
output  [31:0] s3_out_d0;
output  [31:0] grp_fu_2105_p_din0;
output  [31:0] grp_fu_2105_p_din1;
output  [4:0] grp_fu_2105_p_opcode;
input  [0:0] grp_fu_2105_p_dout0;
output   grp_fu_2105_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln231_fu_139_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [9:0] add_ln236_fu_209_p2;
reg   [9:0] add_ln236_reg_380;
reg   [9:0] add_ln236_reg_380_pp0_iter1_reg;
reg   [9:0] add_ln236_reg_380_pp0_iter2_reg;
wire   [10:0] tmp_10_fu_215_p3;
reg   [10:0] tmp_10_reg_385;
reg   [10:0] tmp_10_reg_385_pp0_iter1_reg;
wire   [10:0] add_ln235_fu_228_p2;
reg   [10:0] add_ln235_reg_395;
reg   [10:0] add_ln235_reg_395_pp0_iter1_reg;
wire   [0:0] icmp_ln236_fu_296_p2;
reg   [0:0] icmp_ln236_reg_415;
wire   [0:0] icmp_ln236_1_fu_302_p2;
reg   [0:0] icmp_ln236_1_reg_420;
wire   [0:0] icmp_ln236_2_fu_308_p2;
reg   [0:0] icmp_ln236_2_reg_425;
wire   [0:0] icmp_ln236_3_fu_314_p2;
reg   [0:0] icmp_ln236_3_reg_430;
wire   [63:0] zext_ln234_fu_223_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln235_fu_234_p1;
wire   [63:0] zext_ln234_1_fu_346_p1;
wire   [63:0] zext_ln236_2_fu_351_p1;
reg   [5:0] c_fu_52;
wire   [5:0] add_ln232_fu_239_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_c_load;
reg   [4:0] t_fu_56;
wire   [4:0] select_ln231_1_fu_177_p3;
reg   [4:0] ap_sig_allocacmp_t_load;
reg   [9:0] indvar_flatten45_fu_60;
wire   [9:0] add_ln231_1_fu_145_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten45_load;
reg    tmp_1_ce2_local;
reg    tmp_1_ce1_local;
reg    tmp_1_ce0_local;
reg    s3_out_we0_local;
reg    s3_out_ce0_local;
wire   [0:0] icmp_ln232_fu_163_p2;
wire   [4:0] add_ln231_fu_157_p2;
wire   [5:0] select_ln231_fu_169_p3;
wire   [9:0] tmp_s_fu_185_p3;
wire   [9:0] zext_ln236_1_fu_205_p1;
wire   [10:0] tmp_9_fu_193_p3;
wire   [10:0] zext_ln236_fu_201_p1;
wire   [31:0] bitcast_ln236_fu_260_p1;
wire   [31:0] bitcast_ln236_1_fu_278_p1;
wire   [7:0] tmp_11_fu_264_p4;
wire   [22:0] trunc_ln236_fu_274_p1;
wire   [7:0] tmp_12_fu_282_p4;
wire   [22:0] trunc_ln236_1_fu_292_p1;
wire   [0:0] or_ln236_fu_320_p2;
wire   [0:0] or_ln236_1_fu_324_p2;
wire   [0:0] and_ln236_fu_328_p2;
wire   [0:0] and_ln236_1_fu_334_p2;
wire   [10:0] select_ln236_fu_340_p3;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 c_fu_52 = 6'd0;
#0 t_fu_56 = 5'd0;
#0 indvar_flatten45_fu_60 = 10'd0;
#0 ap_done_reg = 1'b0;
end

ecg_cnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln231_fu_139_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_52 <= add_ln232_fu_239_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_52 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln231_fu_139_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten45_fu_60 <= add_ln231_1_fu_145_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten45_fu_60 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln231_fu_139_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_56 <= select_ln231_1_fu_177_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_56 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln235_reg_395 <= add_ln235_fu_228_p2;
        add_ln235_reg_395_pp0_iter1_reg <= add_ln235_reg_395;
        add_ln236_reg_380 <= add_ln236_fu_209_p2;
        add_ln236_reg_380_pp0_iter1_reg <= add_ln236_reg_380;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln236_1_reg_420 <= icmp_ln236_1_fu_302_p2;
        icmp_ln236_2_reg_425 <= icmp_ln236_2_fu_308_p2;
        icmp_ln236_3_reg_430 <= icmp_ln236_3_fu_314_p2;
        icmp_ln236_reg_415 <= icmp_ln236_fu_296_p2;
        tmp_10_reg_385 <= tmp_10_fu_215_p3;
        tmp_10_reg_385_pp0_iter1_reg <= tmp_10_reg_385;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln236_reg_380_pp0_iter2_reg <= add_ln236_reg_380_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((icmp_ln231_fu_139_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 6'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten45_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten45_load = indvar_flatten45_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_t_load = 5'd0;
    end else begin
        ap_sig_allocacmp_t_load = t_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        s3_out_ce0_local = 1'b1;
    end else begin
        s3_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        s3_out_we0_local = 1'b1;
    end else begin
        s3_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tmp_1_ce0_local = 1'b1;
    end else begin
        tmp_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_1_ce1_local = 1'b1;
    end else begin
        tmp_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_1_ce2_local = 1'b1;
    end else begin
        tmp_1_ce2_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln231_1_fu_145_p2 = (ap_sig_allocacmp_indvar_flatten45_load + 10'd1);

assign add_ln231_fu_157_p2 = (ap_sig_allocacmp_t_load + 5'd1);

assign add_ln232_fu_239_p2 = (select_ln231_fu_169_p3 + 6'd1);

assign add_ln235_fu_228_p2 = (tmp_9_fu_193_p3 + zext_ln236_fu_201_p1);

assign add_ln236_fu_209_p2 = (tmp_s_fu_185_p3 + zext_ln236_1_fu_205_p1);

assign and_ln236_1_fu_334_p2 = (grp_fu_2105_p_dout0 & and_ln236_fu_328_p2);

assign and_ln236_fu_328_p2 = (or_ln236_fu_320_p2 & or_ln236_1_fu_324_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln236_1_fu_278_p1 = tmp_1_q1;

assign bitcast_ln236_fu_260_p1 = tmp_1_q2;

assign grp_fu_2105_p_ce = 1'b1;

assign grp_fu_2105_p_din0 = tmp_1_q2;

assign grp_fu_2105_p_din1 = tmp_1_q1;

assign grp_fu_2105_p_opcode = 5'd2;

assign icmp_ln231_fu_139_p2 = ((ap_sig_allocacmp_indvar_flatten45_load == 10'd736) ? 1'b1 : 1'b0);

assign icmp_ln232_fu_163_p2 = ((ap_sig_allocacmp_c_load == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln236_1_fu_302_p2 = ((trunc_ln236_fu_274_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln236_2_fu_308_p2 = ((tmp_12_fu_282_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln236_3_fu_314_p2 = ((trunc_ln236_1_fu_292_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln236_fu_296_p2 = ((tmp_11_fu_264_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln236_1_fu_324_p2 = (icmp_ln236_3_reg_430 | icmp_ln236_2_reg_425);

assign or_ln236_fu_320_p2 = (icmp_ln236_reg_415 | icmp_ln236_1_reg_420);

assign s3_out_address0 = zext_ln236_2_fu_351_p1;

assign s3_out_ce0 = s3_out_ce0_local;

assign s3_out_d0 = tmp_1_q0;

assign s3_out_we0 = s3_out_we0_local;

assign select_ln231_1_fu_177_p3 = ((icmp_ln232_fu_163_p2[0:0] == 1'b1) ? add_ln231_fu_157_p2 : ap_sig_allocacmp_t_load);

assign select_ln231_fu_169_p3 = ((icmp_ln232_fu_163_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_c_load);

assign select_ln236_fu_340_p3 = ((and_ln236_1_fu_334_p2[0:0] == 1'b1) ? tmp_10_reg_385_pp0_iter1_reg : add_ln235_reg_395_pp0_iter1_reg);

assign tmp_10_fu_215_p3 = {{select_ln231_1_fu_177_p3}, {select_ln231_fu_169_p3}};

assign tmp_11_fu_264_p4 = {{bitcast_ln236_fu_260_p1[30:23]}};

assign tmp_12_fu_282_p4 = {{bitcast_ln236_1_fu_278_p1[30:23]}};

assign tmp_1_address0 = zext_ln234_1_fu_346_p1;

assign tmp_1_address1 = zext_ln235_fu_234_p1;

assign tmp_1_address2 = zext_ln234_fu_223_p1;

assign tmp_1_ce0 = tmp_1_ce0_local;

assign tmp_1_ce1 = tmp_1_ce1_local;

assign tmp_1_ce2 = tmp_1_ce2_local;

assign tmp_9_fu_193_p3 = {{select_ln231_1_fu_177_p3}, {6'd32}};

assign tmp_s_fu_185_p3 = {{select_ln231_1_fu_177_p3}, {5'd0}};

assign trunc_ln236_1_fu_292_p1 = bitcast_ln236_1_fu_278_p1[22:0];

assign trunc_ln236_fu_274_p1 = bitcast_ln236_fu_260_p1[22:0];

assign zext_ln234_1_fu_346_p1 = select_ln236_fu_340_p3;

assign zext_ln234_fu_223_p1 = tmp_10_fu_215_p3;

assign zext_ln235_fu_234_p1 = add_ln235_fu_228_p2;

assign zext_ln236_1_fu_205_p1 = select_ln231_fu_169_p3;

assign zext_ln236_2_fu_351_p1 = add_ln236_reg_380_pp0_iter2_reg;

assign zext_ln236_fu_201_p1 = select_ln231_fu_169_p3;

endmodule //ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_231_5_VITIS_LOOP_232_6
