

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "36", "41", "44", "46", "49", "52", "55", "57", "60", "62", "65", "67", "70", "72", "76", "81", "85", "88", "92", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105"],
		"CDFG" : "ecg_cnn_top",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "313891", "EstimateLatencyMax" : "4259219",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "INPUT_BUS", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "INPUT_BUS_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_377_1_fu_1687", "Port" : "INPUT_BUS", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "OUTPUT_BUS", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "OUTPUT_BUS_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "OUTPUT_BUS_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "92", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_341_5_fu_2067", "Port" : "OUTPUT_BUS", "Inst_start_state" : "187", "Inst_end_state" : "188"}]},
			{"Name" : "input_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_in_2d_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_377_1_fu_1687", "Port" : "ecg_cnn_top_float_float_in_2d_2", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "36", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_fu_1696", "Port" : "ecg_cnn_top_float_float_in_2d_2", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "s1_seq_out", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_fu_1696", "Port" : "s1_seq_out", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "41", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_73_4_fu_1710", "Port" : "s1_seq_out", "Inst_start_state" : "16", "Inst_end_state" : "17"},
					{"ID" : "46", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_96_4_fu_1734", "Port" : "s1_seq_out", "Inst_start_state" : "31", "Inst_end_state" : "32"}]},
			{"Name" : "s1_conv_seq_w_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_fu_1696", "Port" : "s1_conv_seq_w_3", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "s1_bn_seq_scale", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_fu_1696", "Port" : "s1_bn_seq_scale", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "s1_bn_seq_bias", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_fu_1696", "Port" : "s1_bn_seq_bias", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "s1_conv_A_w", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "41", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_73_4_fu_1710", "Port" : "s1_conv_A_w", "Inst_start_state" : "16", "Inst_end_state" : "17"}]},
			{"Name" : "s1_bn_A_scale", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s1_bn_A_bias", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s1_A_out", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_113_1_VITIS_LOOP_114_2_fu_1724", "Port" : "s1_A_out", "Inst_start_state" : "29", "Inst_end_state" : "44"}]},
			{"Name" : "s1_B_out", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_113_1_VITIS_LOOP_114_2_fu_1724", "Port" : "s1_B_out", "Inst_start_state" : "29", "Inst_end_state" : "44"}]},
			{"Name" : "s1_pool", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "44", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_113_1_VITIS_LOOP_114_2_fu_1724", "Port" : "s1_pool", "Inst_start_state" : "29", "Inst_end_state" : "44"},
					{"ID" : "49", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_133_4_fu_1748", "Port" : "s1_pool", "Inst_start_state" : "47", "Inst_end_state" : "48"}]},
			{"Name" : "s1_conv_B_w", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "46", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_96_4_fu_1734", "Port" : "s1_conv_B_w", "Inst_start_state" : "31", "Inst_end_state" : "32"}]},
			{"Name" : "s1_bn_B_scale", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s1_bn_B_bias", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s2_conv_seq_w", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "49", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_133_4_fu_1748", "Port" : "s2_conv_seq_w", "Inst_start_state" : "47", "Inst_end_state" : "48"}]},
			{"Name" : "s2_bn_seq_scale", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s2_bn_seq_bias", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s2_seq_out", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "52", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_157_4_fu_1762", "Port" : "s2_seq_out", "Inst_start_state" : "63", "Inst_end_state" : "64"},
					{"ID" : "57", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_180_4_fu_1786", "Port" : "s2_seq_out", "Inst_start_state" : "78", "Inst_end_state" : "79"}]},
			{"Name" : "s2_conv_A_w", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "52", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_157_4_fu_1762", "Port" : "s2_conv_A_w", "Inst_start_state" : "63", "Inst_end_state" : "64"}]},
			{"Name" : "s2_bn_A_scale", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s2_bn_A_bias", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s2_A_out", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "55", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_197_1_VITIS_LOOP_198_2_fu_1776", "Port" : "s2_A_out", "Inst_start_state" : "76", "Inst_end_state" : "91"}]},
			{"Name" : "s2_B_out", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "55", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_197_1_VITIS_LOOP_198_2_fu_1776", "Port" : "s2_B_out", "Inst_start_state" : "76", "Inst_end_state" : "91"}]},
			{"Name" : "s2_pool", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "55", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_197_1_VITIS_LOOP_198_2_fu_1776", "Port" : "s2_pool", "Inst_start_state" : "76", "Inst_end_state" : "91"},
					{"ID" : "62", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_219_4_fu_1807", "Port" : "s2_pool", "Inst_start_state" : "94", "Inst_end_state" : "95"}]},
			{"Name" : "s2_conv_B_w", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "57", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_180_4_fu_1786", "Port" : "s2_conv_B_w", "Inst_start_state" : "78", "Inst_end_state" : "79"}]},
			{"Name" : "s2_bn_B_scale", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s2_bn_B_bias", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s3_out", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "60", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_231_5_VITIS_LOOP_232_6_fu_1800", "Port" : "s3_out", "Inst_start_state" : "92", "Inst_end_state" : "108"},
					{"ID" : "67", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_254_4_fu_1828", "Port" : "s3_out", "Inst_start_state" : "111", "Inst_end_state" : "112"}]},
			{"Name" : "s3_conv_w", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "62", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_219_4_fu_1807", "Port" : "s3_conv_w", "Inst_start_state" : "94", "Inst_end_state" : "95"}]},
			{"Name" : "s3_bn_scale", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s3_bn_bias", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s4_out", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "65", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_266_5_VITIS_LOOP_267_6_fu_1821", "Port" : "s4_out", "Inst_start_state" : "109", "Inst_end_state" : "125"},
					{"ID" : "70", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_282_2_fu_1842", "Port" : "s4_out", "Inst_start_state" : "126", "Inst_end_state" : "127"}]},
			{"Name" : "s4_conv_w", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "67", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_254_4_fu_1828", "Port" : "s4_conv_w", "Inst_start_state" : "111", "Inst_end_state" : "112"}]},
			{"Name" : "s4_bn_scale", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s4_bn_bias", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_8", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_9", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_15", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_16", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_17", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_18", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_19", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_20", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_21", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_22", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_23", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_24", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_25", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_26", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_27", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_28", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_29", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_30", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_31", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_32", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_33", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_34", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_35", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_36", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_37", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_38", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_39", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_40", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_41", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_42", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_43", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_44", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_45", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_46", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_47", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_48", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_49", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_50", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_51", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_52", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_53", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_54", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_55", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_56", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_57", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_58", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_59", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_60", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_61", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_62", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_63", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "fc1_b", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "fc1_w", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "72", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_296_2_fu_1850", "Port" : "fc1_w", "Inst_start_state" : "150", "Inst_end_state" : "151"}]},
			{"Name" : "fc1_bn_scale", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "fc1_bn_bias", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_15", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_16", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_17", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_18", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_15", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_16", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_17", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_18", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_19", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_20", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_21", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_22", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_23", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_24", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_25", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_26", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_27", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_28", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_29", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_30", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_31", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_32", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_33", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_34", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_35", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_36", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_37", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_38", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_39", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_40", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_41", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_42", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_43", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_44", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_45", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_46", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_47", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_48", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_49", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_50", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_51", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_52", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_53", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_54", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_55", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_56", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_57", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_58", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_59", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_60", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_61", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_62", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_63", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "fc2_b", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "fc2_w", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "81", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_310_2_fu_1968", "Port" : "fc2_w", "Inst_start_state" : "171", "Inst_end_state" : "172"}]},
			{"Name" : "fc2_bn_scale", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "fc2_bn_bias", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_19", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_20", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_21", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_22", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_23", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_24", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_25", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_26", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_27", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_15", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_16", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_17", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_18", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_19", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_20", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_21", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_22", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_23", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_24", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_25", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_26", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_27", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_28", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_29", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_30", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_31", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "output_w", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "76", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2_fu_1923", "Port" : "output_w", "Inst_start_state" : "162", "Inst_end_state" : "182"}]},
			{"Name" : "output_b", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "76", "SubInstance" : "grp_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2_fu_1923", "Port" : "output_b", "Inst_start_state" : "162", "Inst_end_state" : "182"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_70_3", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state16", "LastState" : ["ap_ST_fsm_state19"], "QuitState" : ["ap_ST_fsm_state16"], "PreState" : ["ap_ST_fsm_state15"], "PostState" : ["ap_ST_fsm_state20"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_68_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state15", "LastState" : ["ap_ST_fsm_state28"], "QuitState" : ["ap_ST_fsm_state15"], "PreState" : ["ap_ST_fsm_state14"], "PostState" : ["ap_ST_fsm_state14"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_67_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state14", "LastState" : ["ap_ST_fsm_state15"], "QuitState" : ["ap_ST_fsm_state14"], "PreState" : ["ap_ST_fsm_state13"], "PostState" : ["ap_ST_fsm_state29"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_93_3", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state31", "LastState" : ["ap_ST_fsm_state34"], "QuitState" : ["ap_ST_fsm_state31"], "PreState" : ["ap_ST_fsm_state30"], "PostState" : ["ap_ST_fsm_state35"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_91_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state30", "LastState" : ["ap_ST_fsm_state43"], "QuitState" : ["ap_ST_fsm_state30"], "PreState" : ["ap_ST_fsm_state29"], "PostState" : ["ap_ST_fsm_state29"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_90_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state29", "LastState" : ["ap_ST_fsm_state30"], "QuitState" : ["ap_ST_fsm_state29"], "PreState" : ["ap_ST_fsm_state14"], "PostState" : ["ap_ST_fsm_state44"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_130_3", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state47", "LastState" : ["ap_ST_fsm_state50"], "QuitState" : ["ap_ST_fsm_state47"], "PreState" : ["ap_ST_fsm_state46"], "PostState" : ["ap_ST_fsm_state51"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_128_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state46", "LastState" : ["ap_ST_fsm_state60"], "QuitState" : ["ap_ST_fsm_state46"], "PreState" : ["ap_ST_fsm_state45"], "PostState" : ["ap_ST_fsm_state45"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_127_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state45", "LastState" : ["ap_ST_fsm_state46"], "QuitState" : ["ap_ST_fsm_state45"], "PreState" : ["ap_ST_fsm_state44"], "PostState" : ["ap_ST_fsm_state61"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_154_3", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state63", "LastState" : ["ap_ST_fsm_state66"], "QuitState" : ["ap_ST_fsm_state63"], "PreState" : ["ap_ST_fsm_state62"], "PostState" : ["ap_ST_fsm_state67"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_152_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state62", "LastState" : ["ap_ST_fsm_state75"], "QuitState" : ["ap_ST_fsm_state62"], "PreState" : ["ap_ST_fsm_state61"], "PostState" : ["ap_ST_fsm_state61"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_151_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state61", "LastState" : ["ap_ST_fsm_state62"], "QuitState" : ["ap_ST_fsm_state61"], "PreState" : ["ap_ST_fsm_state45"], "PostState" : ["ap_ST_fsm_state76"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_177_3", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state78", "LastState" : ["ap_ST_fsm_state81"], "QuitState" : ["ap_ST_fsm_state78"], "PreState" : ["ap_ST_fsm_state77"], "PostState" : ["ap_ST_fsm_state82"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_175_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state77", "LastState" : ["ap_ST_fsm_state90"], "QuitState" : ["ap_ST_fsm_state77"], "PreState" : ["ap_ST_fsm_state76"], "PostState" : ["ap_ST_fsm_state76"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_174_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state76", "LastState" : ["ap_ST_fsm_state77"], "QuitState" : ["ap_ST_fsm_state76"], "PreState" : ["ap_ST_fsm_state61"], "PostState" : ["ap_ST_fsm_state91"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_216_3", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state94", "LastState" : ["ap_ST_fsm_state97"], "QuitState" : ["ap_ST_fsm_state94"], "PreState" : ["ap_ST_fsm_state93"], "PostState" : ["ap_ST_fsm_state98"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_214_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state93", "LastState" : ["ap_ST_fsm_state107"], "QuitState" : ["ap_ST_fsm_state93"], "PreState" : ["ap_ST_fsm_state92"], "PostState" : ["ap_ST_fsm_state92"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_213_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state92", "LastState" : ["ap_ST_fsm_state93"], "QuitState" : ["ap_ST_fsm_state92"], "PreState" : ["ap_ST_fsm_state91"], "PostState" : ["ap_ST_fsm_state108"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_251_3", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state111", "LastState" : ["ap_ST_fsm_state114"], "QuitState" : ["ap_ST_fsm_state111"], "PreState" : ["ap_ST_fsm_state110"], "PostState" : ["ap_ST_fsm_state115"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_249_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state110", "LastState" : ["ap_ST_fsm_state124"], "QuitState" : ["ap_ST_fsm_state110"], "PreState" : ["ap_ST_fsm_state109"], "PostState" : ["ap_ST_fsm_state109"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_248_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state109", "LastState" : ["ap_ST_fsm_state110"], "QuitState" : ["ap_ST_fsm_state109"], "PreState" : ["ap_ST_fsm_state108"], "PostState" : ["ap_ST_fsm_state125"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_280_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state126", "LastState" : ["ap_ST_fsm_state140"], "QuitState" : ["ap_ST_fsm_state126"], "PreState" : ["ap_ST_fsm_state125"], "PostState" : ["ap_ST_fsm_state141"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_294_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state141", "LastState" : ["ap_ST_fsm_state161"], "QuitState" : ["ap_ST_fsm_state141"], "PreState" : ["ap_ST_fsm_state126"], "PostState" : ["ap_ST_fsm_state162"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_308_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "193", "FirstState" : "ap_ST_fsm_state162", "LastState" : ["ap_ST_fsm_state181"], "QuitState" : ["ap_ST_fsm_state162"], "PreState" : ["ap_ST_fsm_state141"], "PostState" : ["ap_ST_fsm_state182"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.ecg_cnn_top_float_float_in_2d_2_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s1_seq_out_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s1_bn_A_scale_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s1_bn_A_bias_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s1_A_out_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s1_B_out_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s1_pool_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s1_bn_B_scale_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s1_bn_B_bias_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s2_bn_seq_scale_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s2_bn_seq_bias_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s2_seq_out_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s2_bn_A_scale_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s2_bn_A_bias_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s2_A_out_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s2_B_out_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s2_pool_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s2_bn_B_scale_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s2_bn_B_bias_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s3_out_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s3_bn_scale_U", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s3_bn_bias_U", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s4_out_U", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s4_bn_scale_U", "Parent" : "0"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s4_bn_bias_U", "Parent" : "0"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fc1_b_U", "Parent" : "0"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fc1_bn_scale_U", "Parent" : "0"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fc1_bn_bias_U", "Parent" : "0"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fc2_b_U", "Parent" : "0"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fc2_bn_scale_U", "Parent" : "0"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fc2_bn_bias_U", "Parent" : "0"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tmp_U", "Parent" : "0"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tmp_1_U", "Parent" : "0"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_377_1_fu_1687", "Parent" : "0", "Child" : ["35"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_377_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "189", "EstimateLatencyMax" : "189",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "INPUT_BUS", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "INPUT_BUS_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln377", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_in_2d_2", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_377_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_377_1_fu_1687.flow_control_loop_pipe_sequential_init_U", "Parent" : "34"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_fu_1696", "Parent" : "0", "Child" : ["37", "38", "39", "40"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "31272", "EstimateLatencyMax" : "31272",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s1_seq_out", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "ecg_cnn_top_float_float_in_2d_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s1_conv_seq_w_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s1_bn_seq_scale", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s1_bn_seq_bias", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter8", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter8", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_fu_1696.s1_conv_seq_w_3_U", "Parent" : "36"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_fu_1696.s1_bn_seq_scale_U", "Parent" : "36"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_fu_1696.s1_bn_seq_bias_U", "Parent" : "36"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_fu_1696.flow_control_loop_pipe_sequential_init_U", "Parent" : "36"},
	{"ID" : "41", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_73_4_fu_1710", "Parent" : "0", "Child" : ["42", "43"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_73_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "39", "EstimateLatencyMax" : "39",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln76", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln68", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln75", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "s1_seq_out", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s1_conv_A_w", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_73_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_73_4_fu_1710.s1_conv_A_w_U", "Parent" : "41"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_73_4_fu_1710.flow_control_loop_pipe_sequential_init_U", "Parent" : "41"},
	{"ID" : "44", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_113_1_VITIS_LOOP_114_2_fu_1724", "Parent" : "0", "Child" : ["45"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_113_1_VITIS_LOOP_114_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "754", "EstimateLatencyMax" : "754",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s1_A_out", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s1_B_out", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s1_pool", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_113_1_VITIS_LOOP_114_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter9", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter9", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_113_1_VITIS_LOOP_114_2_fu_1724.flow_control_loop_pipe_sequential_init_U", "Parent" : "44"},
	{"ID" : "46", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_96_4_fu_1734", "Parent" : "0", "Child" : ["47", "48"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_96_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "39", "EstimateLatencyMax" : "39",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln99", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln91", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln98", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "s1_seq_out", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s1_conv_B_w", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_96_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_96_4_fu_1734.s1_conv_B_w_U", "Parent" : "46"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_96_4_fu_1734.flow_control_loop_pipe_sequential_init_U", "Parent" : "46"},
	{"ID" : "49", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_133_4_fu_1748", "Parent" : "0", "Child" : ["50", "51"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_133_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "39", "EstimateLatencyMax" : "39",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln135", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln136", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln128", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "s1_pool", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s2_conv_seq_w", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_133_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_133_4_fu_1748.s2_conv_seq_w_U", "Parent" : "49"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_133_4_fu_1748.flow_control_loop_pipe_sequential_init_U", "Parent" : "49"},
	{"ID" : "52", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_157_4_fu_1762", "Parent" : "0", "Child" : ["53", "54"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_157_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "63", "EstimateLatencyMax" : "63",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln160", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln152", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln159", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_16_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "s2_seq_out", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s2_conv_A_w", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_157_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_157_4_fu_1762.s2_conv_A_w_U", "Parent" : "52"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_157_4_fu_1762.flow_control_loop_pipe_sequential_init_U", "Parent" : "52"},
	{"ID" : "55", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_197_1_VITIS_LOOP_198_2_fu_1776", "Parent" : "0", "Child" : ["56"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_197_1_VITIS_LOOP_198_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "746", "EstimateLatencyMax" : "746",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s2_A_out", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s2_B_out", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s2_pool", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_197_1_VITIS_LOOP_198_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter9", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter9", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_197_1_VITIS_LOOP_198_2_fu_1776.flow_control_loop_pipe_sequential_init_U", "Parent" : "55"},
	{"ID" : "57", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_180_4_fu_1786", "Parent" : "0", "Child" : ["58", "59"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_180_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "63", "EstimateLatencyMax" : "63",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln183", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln175", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln182", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_20_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "s2_seq_out", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s2_conv_B_w", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_180_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_180_4_fu_1786.s2_conv_B_w_U", "Parent" : "57"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_180_4_fu_1786.flow_control_loop_pipe_sequential_init_U", "Parent" : "57"},
	{"ID" : "60", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_231_5_VITIS_LOOP_232_6_fu_1800", "Parent" : "0", "Child" : ["61"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_231_5_VITIS_LOOP_232_6",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "740", "EstimateLatencyMax" : "740",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s3_out", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_231_5_VITIS_LOOP_232_6", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_231_5_VITIS_LOOP_232_6_fu_1800.flow_control_loop_pipe_sequential_init_U", "Parent" : "60"},
	{"ID" : "62", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_219_4_fu_1807", "Parent" : "0", "Child" : ["63", "64"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_219_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "63", "EstimateLatencyMax" : "63",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_19", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln221", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln222", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln214", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_24_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "s2_pool", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s3_conv_w", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_219_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_219_4_fu_1807.s3_conv_w_U", "Parent" : "62"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_219_4_fu_1807.flow_control_loop_pipe_sequential_init_U", "Parent" : "62"},
	{"ID" : "65", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_266_5_VITIS_LOOP_267_6_fu_1821", "Parent" : "0", "Child" : ["66"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_266_5_VITIS_LOOP_267_6",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "708", "EstimateLatencyMax" : "708",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "tmp", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s4_out", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_266_5_VITIS_LOOP_267_6", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_266_5_VITIS_LOOP_267_6_fu_1821.flow_control_loop_pipe_sequential_init_U", "Parent" : "65"},
	{"ID" : "67", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_254_4_fu_1828", "Parent" : "0", "Child" : ["68", "69"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_254_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "111", "EstimateLatencyMax" : "111",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_23", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln256", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln257", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln249", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_28_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "s3_out", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "s4_conv_w", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_254_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_254_4_fu_1828.s4_conv_w_U", "Parent" : "67"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_254_4_fu_1828.flow_control_loop_pipe_sequential_init_U", "Parent" : "67"},
	{"ID" : "70", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_282_2_fu_1842", "Parent" : "0", "Child" : ["71"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_282_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "37", "EstimateLatencyMax" : "37",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "zext_ln280", "Type" : "None", "Direction" : "I"},
			{"Name" : "s_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "s4_out", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_282_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "71", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_282_2_fu_1842.flow_control_loop_pipe_sequential_init_U", "Parent" : "70"},
	{"ID" : "72", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_296_2_fu_1850", "Parent" : "0", "Child" : ["73", "74", "75"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_296_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "207", "EstimateLatencyMax" : "207",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_27", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln294", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_1_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_2_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_3_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_4_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_5_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_6_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_7_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_8_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_9_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_10_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_93", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_94", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_95", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_96", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_97", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_16_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_17_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_18_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_19_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_20_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_98", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_99", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_100", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_101", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_102", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_26_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_27_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_28_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_29_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_30_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_103", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_104", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_105", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_106", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_107", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_36_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_37_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_38_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_39_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_40_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_108", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_109", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_110", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_111", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_112", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_46_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_47_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_48_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_49_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_50_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_113", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_114", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_115", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_116", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_117", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_56_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_57_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_58_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_59_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7gap_out_60_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_118", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out_119", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_gap_out", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_31_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "fc1_w", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_296_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "73", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_296_2_fu_1850.fc1_w_U", "Parent" : "72"},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_296_2_fu_1850.sparsemux_129_6_32_1_1_U112", "Parent" : "72"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_296_2_fu_1850.flow_control_loop_pipe_sequential_init_U", "Parent" : "72"},
	{"ID" : "76", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2_fu_1923", "Parent" : "0", "Child" : ["77", "78", "79", "80"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "496", "EstimateLatencyMax" : "496",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "ecg_cnn_top_float_float_fc2_out_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_19_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_20_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_21_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_22_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_23_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_24_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_25_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_26_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_27_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_10_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_56", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_57", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_58", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_59", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_60", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_16_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_17_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_18_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_19_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_20_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_61", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_62", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_63", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_64", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out_65", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_26_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_27_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_28_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_29_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc2_out_30_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc2_out", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_411816011_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mux_case_31161559_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mux_case_21141507_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mux_case_11121455_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mx_33_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "output_w", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "output_b", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_325_1_VITIS_LOOP_327_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2_fu_1923.output_w_U", "Parent" : "76"},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2_fu_1923.output_b_U", "Parent" : "76"},
	{"ID" : "79", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2_fu_1923.sparsemux_65_5_32_1_1_U257", "Parent" : "76"},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_327_2_fu_1923.flow_control_loop_pipe_sequential_init_U", "Parent" : "76"},
	{"ID" : "81", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_310_2_fu_1968", "Parent" : "0", "Child" : ["82", "83", "84"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_310_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "207", "EstimateLatencyMax" : "207",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_30", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln308", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_10_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_11_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_12_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_13_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_14_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_15_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_16_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_17_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_18_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_10_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_66", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_67", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_68", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_69", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_70", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_16_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_17_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_18_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_19_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_20_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_71", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_72", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_73", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_74", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_75", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_26_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_27_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_28_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_29_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_30_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_76", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_77", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_78", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_79", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_80", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_36_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_37_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_38_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_39_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_40_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_81", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_82", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_83", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_84", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_85", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_46_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_47_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_48_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_49_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_50_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_86", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_87", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_88", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_89", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_90", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_56_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_57_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_58_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_59_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ11ecg_cnn_topPfS_E7fc1_out_60_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_91", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out_92", "Type" : "None", "Direction" : "I"},
			{"Name" : "ecg_cnn_top_float_float_fc1_out", "Type" : "None", "Direction" : "I"},
			{"Name" : "acc_34_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "fc2_w", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_310_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "82", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_310_2_fu_1968.fc2_w_U", "Parent" : "81"},
	{"ID" : "83", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_310_2_fu_1968.sparsemux_129_6_32_1_1_U185", "Parent" : "81"},
	{"ID" : "84", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_310_2_fu_1968.flow_control_loop_pipe_sequential_init_U", "Parent" : "81"},
	{"ID" : "85", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_336_3_fu_2041", "Parent" : "0", "Child" : ["86", "87"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_336_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "mx_33_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_11121455_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_21141507_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_31161559_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_411816011_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mx_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_336_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "86", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_336_3_fu_2041.sparsemux_9_3_32_1_1_U299", "Parent" : "85"},
	{"ID" : "87", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_336_3_fu_2041.flow_control_loop_pipe_sequential_init_U", "Parent" : "85"},
	{"ID" : "88", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_340_4_fu_2051", "Parent" : "0", "Child" : ["89", "90", "91"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_340_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "39", "EstimateLatencyMax" : "39",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "mx_33_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_11121455_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_21141507_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_31161559_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_411816011_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mx_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_4143181_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mux_case_3141178_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mux_case_2139175_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mux_case_1137172_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "mux_case_0135169_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "se_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_340_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "5", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "89", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_340_4_fu_2051.fexp_32ns_32ns_32_8_full_dsp_1_U308", "Parent" : "88"},
	{"ID" : "90", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_340_4_fu_2051.sparsemux_11_3_32_1_1_U309", "Parent" : "88"},
	{"ID" : "91", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_340_4_fu_2051.flow_control_loop_pipe_sequential_init_U", "Parent" : "88"},
	{"ID" : "92", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_341_5_fu_2067", "Parent" : "0", "Child" : ["93", "94"],
		"CDFG" : "ecg_cnn_top_Pipeline_VITIS_LOOP_341_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "19", "EstimateLatencyMax" : "19",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "OUTPUT_BUS", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "OUTPUT_BUS_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln341", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_0135169_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_1137172_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_2139175_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_3141178_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "mux_case_4143181_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "se_reload", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_341_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter13", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter13", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "93", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_341_5_fu_2067.sparsemux_11_3_32_1_1_U325", "Parent" : "92"},
	{"ID" : "94", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_ecg_cnn_top_Pipeline_VITIS_LOOP_341_5_fu_2067.flow_control_loop_pipe_sequential_init_U", "Parent" : "92"},
	{"ID" : "95", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "96", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.INPUT_BUS_m_axi_U", "Parent" : "0"},
	{"ID" : "97", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.OUTPUT_BUS_m_axi_U", "Parent" : "0"},
	{"ID" : "98", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.faddfsub_32ns_32ns_32_4_full_dsp_1_U334", "Parent" : "0"},
	{"ID" : "99", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fmul_32ns_32ns_32_3_max_dsp_1_U335", "Parent" : "0"},
	{"ID" : "100", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fdiv_32ns_32ns_32_12_no_dsp_1_U336", "Parent" : "0"},
	{"ID" : "101", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sitofp_32s_32_4_no_dsp_1_U337", "Parent" : "0"},
	{"ID" : "102", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fcmp_32ns_32ns_1_2_no_dsp_1_U338", "Parent" : "0"},
	{"ID" : "103", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fadd_32ns_32ns_32_4_full_dsp_1_U339", "Parent" : "0"},
	{"ID" : "104", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fcmp_32ns_32ns_1_2_no_dsp_1_U340", "Parent" : "0"},
	{"ID" : "105", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fcmp_32ns_32ns_1_2_no_dsp_1_U341", "Parent" : "0"}]}
