-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity ecg_cnn_top_s3_bn_bias_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of ecg_cnn_top_s3_bn_bias_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111110000010010001000000110110", 1 => "00111111001110111000101100100001", 2 => "00111111001001100101110100011010", 3 => "00111101100100110110100100001111", 
    4 => "00111111000010011111000000011001", 5 => "00111110010111010101000001001100", 6 => "00111111000000011011100010001000", 7 => "10111110001111101000010010000000", 
    8 => "00111101010000111000000000110000", 9 => "00111111000001110010111001101101", 10 => "00111111010000001101110100100000", 11 => "00111110110110000001100111000101", 
    12 => "00111111001010010000011001010011", 13 => "10111110001000001010100010000111", 14 => "00111110111110111110111000111000", 15 => "10111110111000000010011100101001", 
    16 => "00111111010101010011111000101001", 17 => "00111110101110111100110101111001", 18 => "00111111010000011101011111011100", 19 => "10111110101101001100111011100100", 
    20 => "10111110001110110100000010101000", 21 => "10111100111101101111110010011100", 22 => "10111101100000101010100100010101", 23 => "10111101000101000110111111100111", 
    24 => "10111110000001101110110000100010", 25 => "00111101100010010011010100000000", 26 => "10111100111110101101001001011111", 27 => "00111111010001100101100000100101", 
    28 => "00111111001011001101110001011100", 29 => "00111110010001100011100100000000", 30 => "10111101100100111111000100001011", 31 => "00111111011011101011011101111100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

