-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_s1_conv_bkb is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 56
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of ecg_cnn_top_ecg_cnn_top_Pipeline_VITIS_LOOP_47_1_VITIS_LOOP_48_2_VITIS_LOOP_50_3_s1_conv_bkb is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "01011100", 1 => "00001001", 2 => "01101111", 3 => "00111111", 
    4 => "00110010", 5 => "00100110", 6 => "11101011", 7 => "00100101", 
    8 => "11100111", 9 => "11110011", 10 => "01110000", 11 => "01010111", 
    12 => "01010011", 13 => "00100000", 14 => "01000011", 15 => "01001100", 
    16 => "00110010", 17 => "00011010", 18 => "01010001", 19 => "10110011", 
    20 => "01011111", 21 => "01111111", 22 => "01100100", 23 => "01000000", 
    24 => "01101100", 25 => "00100101", 26 => "01001111", 27 => "00100001", 
    28 => "00111101", 29 => "01000011", 30 => "00111000", 31 => "01100101", 
    32 => "01011001", 33 => "01100110", 34 => "11110011", 35 => "01110000", 
    36 => "01100001", 37 => "11110011", 38 => "00010111", 39 => "11111011", 
    40 => "00000110", 41 => "01110110", 42 => "00011111", 43 => "00101111", 
    44 => "11111101", 45 => "00101000", 46 => "01010001", 47 => "00001001", 
    48 => "00001100", 49 => "01001110", 50 => "11111011", 51 => "01000101", 
    52 => "11000010", 53 => "01100011", 54 => "01110000", 55 => "10000000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

