-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity ecg_cnn_top_s3_bn_scale_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of ecg_cnn_top_s3_bn_scale_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110000101101001010101010011", 1 => "00111110001000000100101010010011", 2 => "00111110001000001100001111100100", 3 => "00111110000100100101111011110001", 
    4 => "00111110000100000011101001000001", 5 => "00111110000110000100111011011011", 6 => "00111110000111001010011110101000", 7 => "00111101111100110111100110101110", 
    8 => "00111110000100011101001110100011", 9 => "00111101111010111100111011101001", 10 => "00111110001001101001000011101101", 11 => "00111110001000110000000001100100", 
    12 => "00111110000100111101011001110100", 13 => "00111101101001101010111010010001", 14 => "00111110000001000110111000001011", 15 => "00111101101000110110100010110101", 
    16 => "00111110000001110010110111001111", 17 => "00111110000101110011100010010111", 18 => "00111110000101100001110010011011", 19 => "00111101101101101010000010000100", 
    20 => "00111101101011110111011011101111", 21 => "00111101110011000000111001110010", 22 => "00111101110101011111110000111101", 23 => "00111101110101100110001110001010", 
    24 => "00111101101011110101011110010111", 25 => "00111110000100001101100011101000", 26 => "00111110000011011101000000001000", 27 => "00111110000000000010110000001110", 
    28 => "00111101111101100000010001010010", 29 => "00111110000011100000101100011101", 30 => "00111101111101011110111110111101", 31 => "00111101111011100001010010010000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

