-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity ecg_cnn_top_fc2_bn_scale_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of ecg_cnn_top_fc2_bn_scale_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101111010000001101111010011", 1 => "00111110000010100110010011010110", 2 => "00111101111100100100011011000100", 3 => "00111110000100011011110111011111", 
    4 => "00111101111011111001110110000001", 5 => "00111110000010000111001001010110", 6 => "00111101110101010100000011011001", 7 => "00111110000001010011000101000100", 
    8 => "00111101111100011100010010000101", 9 => "00111101111010010000000100111001", 10 => "00111101111000010111001010011000", 11 => "00111110000100010011101110011100", 
    12 => "00111110000001010001011001111010", 13 => "00111110000111000101011001000111", 14 => "00111101110110101010000100110110", 15 => "00111110000000100001000100101000", 
    16 => "00111110000001010010110100100110", 17 => "00111101111011001011010100001011", 18 => "00111110001000111000110110011010", 19 => "00111101111001100011111110100010", 
    20 => "00111110000111000001100101000000", 21 => "00111101111001001000111110010010", 22 => "00111110000001000101100010011011", 23 => "00111101111100011001111001100111", 
    24 => "00111101110101111000110111000010", 25 => "00111110001010001101110011111010", 26 => "00111110000010011010100110111101", 27 => "00111110000010001000110000101010", 
    28 => "00111101111000010111100110100010", 29 => "00111101111001000011111010001101", 30 => "00111110000001001101010101110100", 31 => "00111110000010011100001010011000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

