# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.srcs/sources_1/bd/ecg_system/ip/ecg_system_axi_mem_intercon_imp_xbar_0/ecg_system_axi_mem_intercon_imp_xbar_0.xci
# IP: The module: 'ecg_system_axi_mem_intercon_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_axi_mem_intercon_imp_xbar_0/ecg_system_axi_mem_intercon_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ecg_system_axi_mem_intercon_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.srcs/sources_1/bd/ecg_system/ip/ecg_system_axi_mem_intercon_imp_xbar_0/ecg_system_axi_mem_intercon_imp_xbar_0.xci
# IP: The module: 'ecg_system_axi_mem_intercon_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rohit Kumawat/ecg_fpga_system/ecg_fpga_system.gen/sources_1/bd/ecg_system/ip/ecg_system_axi_mem_intercon_imp_xbar_0/ecg_system_axi_mem_intercon_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ecg_system_axi_mem_intercon_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
